### PR TITLE
Move math bindings to CBLAS and LAPACKE

### PR DESCRIPTION
**Pull request by robertodr**
## Description
What it says on the tin: use standardized C bindings to BLAS and LAPACK.

## Todos
Notable points (developer or user-interest) that this PR has or will accomplish.
- [x] BLAS level 1, 2, and 3 moved to CBLAS
- [x] Conda install `mkl-include` on Travis
- [x] LAPACK moved to LAPACKE
- [x] Remove use of `check_fortran_function_exists` to check for newere LAPACK subroutines
- [x] Remove duplicated name-mangling headers

## Questions
- Should the bindings be someplace more central, rather than in `libqt`? It could encourage _not rewriting them_ in other modules...

## Checklist
- [ ] Tests added for any new features
- [x] [All or relevant fraction of full tests run](http://psicode.org/psi4manual/master/build_planning.html#how-to-run-a-subset-of-tests)

## Status
- [ ] Ready for review
- [ ] Ready for merge

### CODE REVIEW

**Comment by andysim** [comment]
@jturney should've written this and called it JetPACK.  I'm not sure there's a more central location; the libqt library (math routines from the original 'quantum trio') is about as central a math library as we have.  I agree that avoiding duplication would be very good though.

**Comment by robertodr** [comment]
The reason for the tests failing seems to be inconsistencies in the way LAPACK functions are used. To get this fully working I'd need to inspect _all call points_ to BLAS and LAPACK in the code. Given we agreed on transitioning to xtensor, this seems quite the waste of effort.

**Comment by loriab** [comment]
So much good stuff -- should anything be salvaged before closing in favor of xtensor?

**Comment by robertodr** [comment]
Some stuff can probably be salvaged, but even if this is closed I will still be able to browse the diffs.

**Pull request closed without merging**
