### PR TITLE
Remove long-deprecated LAPACK functions

### PR DESCRIPTION
**Pull request by TiborGY**
## Description

Psi4 has wrappers for seven LAPACK functions which have been marked as deprecated by the LAPACK devs for a long time. These functions have also been marked as deprecated within Psi4. Luckily they are not marked as `PSI_API`, nor are they used by Psi4. This PR removes them.

Note that the default git diff algorithm is getting confused by the repetitive text in `lapack_intfc.cc` and incorrectly indicates that some lines were added. The correct diff can be obtained with `--diff-algorithm=minimal` :
```
$ git diff --stat --diff-algorithm=minimal master remove_deprecated_lapack
 psi4/src/export_blas_lapack.cc            |    7 -
 psi4/src/psi4/libmints/psimath.cc         |   50 --
 psi4/src/psi4/libmints/psimath.h          |   27 -
 psi4/src/psi4/libqt/CMakeLists.txt        |   19 -
 psi4/src/psi4/libqt/lapack_intfc.cc       | 1021 -----------------------------
 psi4/src/psi4/libqt/lapack_intfc_mangle.h |   35 -
 psi4/src/psi4/libqt/qt.h                  |   25 -
 7 files changed, 1184 deletions(-)
```

## User API & Changelog headlines

- [x] Psi4 now requires the LAPACK library to provide `DGGSVD3` and `DGGSVP3`.

## Dev notes & details

- [x] Fortran, C and C++ style wrappers for `DGEGS`, `DGEGV,` `DGELSX,` `DGEQPF,` `DGGSVD,` `DGGSVP` and `DTZRQF` are removed.
- [x] CMake checks for the availability of  `DGGSVD3` and `DGGSVP3` are removed.

## Checklist
- [x] No new features
- [x] CI tests are passing

## Status
- [x] Ready for review
- [x] Ready for merge

### CODE REVIEW

**Review by loriab — APPROVED** [review]
Thanks for the deprecation follow up

**Comment by TiborGY** [comment]
May I ask for a merge on this? If concerns regarding Accelerate are blocking this, please let me know.
I made the assumption that all reasonable LAPACK implementations should be providing DGGSVD3 and DGGSVP3 at this point.

**Comment by loriab** [comment]
Sorry, I knew I should have merged this this afternoon. If you make this change https://github.com/psi4/psi4/pull/2895/files#diff-9886b1fe077112c3a9952964ed992dc3cd38b48d0a506a6b7a00241e4669d2b1R243 that should fix Linux Eco CI. And I think the Windows Azure error is a fluke.

**Comment by TiborGY** [comment]
Done. PR has been rebased and the QCArchive pin has been added.

**Pull request merged**
