### PR TITLE
Update Windows tests on Azure

### PR DESCRIPTION
**Pull request by raimis**
## Description
This is part of *Psi4* porting to Windows (#933).

## Todos
Notable points (developer or user-interest) that this PR has or will accomplish.
- [x] Add the OpenMP test to Azure
- [x] Add failing ctests to Azure
- [x] Update pytest

## Checklist
- [x] ~~Tests added for any new features~~
- [x] [All or relevant fraction of full tests run](http://psicode.org/psi4manual/master/build_planning.html#how-to-run-a-subset-of-tests)

## Status
- [x] Ready for review
- [x] Ready for merge

### CODE REVIEW

**Comment by raimis** [comment]
Partially, I'm running these test with `python psi4 --test`:
```
2018-12-05T15:54:19.2192346Z ============================= test session starts =============================
2018-12-05T15:54:19.2192531Z platform win32 -- Python 3.6.6, pytest-4.0.1, py-1.7.0, pluggy-0.8.0 -- C:\tools\miniconda3\python.exe
2018-12-05T15:54:19.2193957Z cachedir: .pytest_cache
2018-12-05T15:54:19.2194153Z rootdir: D:\a\1\b\install, inifile:
2018-12-05T15:54:19.5028575Z collecting ... collected 43 items / 21 deselected
2018-12-05T15:54:19.5042204Z 
2018-12-05T15:54:19.5056742Z ..\lib\psi4\tests\test_addons.py::test_gdma SKIPPED                      [  4%]
2018-12-05T15:54:19.5070445Z ..\lib\psi4\tests\test_addons.py::test_mrcc SKIPPED                      [  9%]
2018-12-05T15:54:19.5085682Z ..\lib\psi4\tests\test_addons.py::test_chemps2 SKIPPED                   [ 13%]
2018-12-05T15:54:19.5098425Z ..\lib\psi4\tests\test_addons.py::test_dftd3 SKIPPED                     [ 18%]
2018-12-05T15:54:19.5111431Z ..\lib\psi4\tests\test_addons.py::test_libefp SKIPPED                    [ 22%]
2018-12-05T15:54:19.5124637Z ..\lib\psi4\tests\test_addons.py::test_pcmsolver SKIPPED                 [ 27%]
2018-12-05T15:54:19.5137383Z ..\lib\psi4\tests\test_addons.py::test_erd SKIPPED                       [ 31%]
2018-12-05T15:54:19.5159968Z ..\lib\psi4\tests\test_addons.py::test_simint SKIPPED                    [ 36%]
2018-12-05T15:54:21.2422176Z ..\lib\psi4\tests\test_addons.py::test_json PASSED                       [ 40%]
2018-12-05T15:54:21.2458012Z ..\lib\psi4\tests\test_addons.py::test_cfour SKIPPED                     [ 45%]
2018-12-05T15:54:21.2473322Z ..\lib\psi4\tests\test_addons.py::test_v2rdm_casscf SKIPPED              [ 50%]
2018-12-05T15:54:21.2488441Z ..\lib\psi4\tests\test_addons.py::test_gpu_dfcc SKIPPED                  [ 54%]
2018-12-05T15:54:21.2503496Z ..\lib\psi4\tests\test_addons.py::test_grimme_3c SKIPPED                 [ 59%]
2018-12-05T15:54:21.2517677Z ..\lib\psi4\tests\test_addons.py::test_dkh SKIPPED                       [ 63%]
2018-12-05T15:54:21.2531717Z ..\lib\psi4\tests\test_addons.py::test_snsmp2 SKIPPED                    [ 68%]
2018-12-05T15:54:21.2547307Z ..\lib\psi4\tests\test_addons.py::test_resp SKIPPED                      [ 72%]
2018-12-05T15:54:23.0849642Z ..\lib\psi4\tests\test_psi4.py::test_psi4_basic PASSED                   [ 77%]
2018-12-05T15:54:34.9658940Z ..\lib\psi4\tests\test_psi4.py::test_psi4_cc PASSED                      [ 81%]
2018-12-05T15:54:39.2671697Z ..\lib\psi4\tests\test_psi4.py::test_psi4_cas PASSED                     [ 86%]
2018-12-05T15:55:14.7785164Z ..\lib\psi4\tests\test_psi4.py::test_psi4_dfmp2 PASSED                   [ 90%]
2018-12-05T15:55:32.0037962Z ..\lib\psi4\tests\test_psi4.py::test_psi4_sapt PASSED                    [ 95%]
2018-12-05T15:55:39.8034520Z ..\lib\psi4\tests\test_psi4.py::test_psi4_scfproperty PASSED             [100%]
2018-12-05T15:55:39.8037151Z =========================== short test summary info ===========================
2018-12-05T15:55:39.8038147Z SKIP [1] lib\psi4\tests\test_addons.py:43: Psi4 not compiled with gdma. Rebuild with -DENABLE_gdma
2018-12-05T15:55:39.8039347Z SKIP [1] lib\psi4\tests\test_addons.py:100: Psi4 not detecting MRCC. Add `dmrcc` to envvar PSIPATH or PATH
2018-12-05T15:55:39.8040544Z SKIP [1] lib\psi4\tests\test_addons.py:125: Psi4 not compiled with CheMPS2. Rebuild with -DENABLE_CheMPS2
2018-12-05T15:55:39.8041756Z SKIP [1] lib\psi4\tests\test_addons.py:173: Psi4 not detecting DFTD3. Add `dftd3` to envvar PSIPATH or PATH
2018-12-05T15:55:39.8042653Z SKIP [1] lib\psi4\tests\test_addons.py:333: Psi4 not compiled with libefp. Rebuild with -DENABLE_libefp
2018-12-05T15:55:39.8043475Z SKIP [1] lib\psi4\tests\test_addons.py:392: Psi4 not compiled with PCMSolver. Rebuild with -DENABLE_PCMSolver
2018-12-05T15:55:39.8044251Z SKIP [1] lib\psi4\tests\test_addons.py:634: Psi4 not compiled with erd. Rebuild with -DENABLE_erd
2018-12-05T15:55:39.8045164Z SKIP [1] lib\psi4\tests\test_addons.py:643: Psi4 not compiled with simint. Rebuild with -DENABLE_simint
2018-12-05T15:55:39.8046429Z SKIP [1] lib\psi4\tests\test_addons.py:686: Psi4 not detecting CFOUR. Add `xcfour` to envvar PSIPATH or PATH
2018-12-05T15:55:39.8046725Z SKIP [1] lib\psi4\tests\test_addons.py:720: Psi4 not detecting plugin v2rdm_casscf. Build plugin if necessary and add to envvar PYTHONPATH
2018-12-05T15:55:39.8047954Z SKIP [1] lib\psi4\tests\test_addons.py:773: Psi4 not detecting plugin gpu_dfcc. Build plugin if necessary and add to envvar PYTHONPATH
2018-12-05T15:55:39.8048914Z SKIP [1] lib\psi4\tests\test_addons.py:810: Psi4 not detecting GCP. Add `gcp` to envvar PSIPATH or PATH
2018-12-05T15:55:39.8050115Z SKIP [1] lib\psi4\tests\test_addons.py:838: Psi4 not compiled with dkh. Rebuild with -DENABLE_dkh
2018-12-05T15:55:39.8051342Z SKIP [1] lib\psi4\tests\test_addons.py:923: Psi4 not detecting plugin snsmp2. Build plugin if necessary and add to envvar PYTHONPATH (or rebuild Psi with -DENABLE_snsmp2)
2018-12-05T15:55:39.8052689Z SKIP [1] lib\psi4\tests\test_addons.py:940: Psi4 not detecting plugin resp. Build plugin if necessary and add to envvar PYTHONPATH (or rebuild Psi with -DENABLE_resp)
2018-12-05T15:55:39.8053679Z 
2018-12-05T15:55:39.8055000Z ============ 7 passed, 15 skipped, 21 deselected in 80.60 seconds =============
```

**Comment by raimis** [comment]
@loriab you mean, the command has to be changed to an equivalent of
 ```bash
PYTHONPATH=stage/lib/ pytest -v -rws --durations=5 stage/lib/psi4/tests/
```

**Comment by loriab** [comment]
@raimis Yes, either the `pytest` command you show or `make pytest` will do.

Right now you're only running the smoke pytests (which admittedly for a long time were all there were) https://github.com/psi4/psi4/blob/master/psi4/extras.py#L158 . It'd be good to run them all. I probably ought to make a `psi4 --fulltests` for yet another mode of access. If you'd prefer that, I can do that quickly.

**Comment by raimis** [comment]
OK! I'll look to that...

**Comment by loriab** [comment]
just added `psi4 --fulltest -nNUM` to #1394 . will need `pytest-xdist` to run in parallel

**Comment by raimis** [comment]
@loriab I have integrated `psi4 --fulltest` on Azure, but the tests does not work in parallel:
```
2018-12-06T18:15:06.8235423Z =================================== ERRORS ====================================
2018-12-06T18:15:06.8236398Z _______________ ERROR at teardown of test_deprecated_wfn_arrays _______________
2018-12-06T18:15:06.8236914Z [gw0] win32 -- Python 3.6.6 C:\tools\miniconda3\python.exe
2018-12-06T18:15:06.8237116Z 
2018-12-06T18:15:06.8238150Z tp = <class 'PermissionError'>, value = None, tb = None
2018-12-06T18:15:06.8238413Z 
2018-12-06T18:15:06.8238651Z     def reraise(tp, value, tb=None):
2018-12-06T18:15:06.8238835Z         try:
2018-12-06T18:15:06.8239065Z             if value is None:
2018-12-06T18:15:06.8239312Z                 value = tp()
2018-12-06T18:15:06.8239526Z             if value.__traceback__ is not tb:
2018-12-06T18:15:06.8239861Z                 raise value.with_traceback(tb)
2018-12-06T18:15:06.8240255Z >           raise value
2018-12-06T18:15:06.8240643Z 
2018-12-06T18:15:06.8240921Z C:\tools\miniconda3\lib\site-packages\six.py:693: 
2018-12-06T18:15:06.8241733Z _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
2018-12-06T18:15:06.8242195Z C:\tools\miniconda3\lib\site-packages\six.py:693: in reraise
2018-12-06T18:15:06.8242519Z     raise value
2018-12-06T18:15:06.8243257Z C:\tools\miniconda3\lib\site-packages\six.py:693: in reraise
2018-12-06T18:15:06.8243569Z     raise value
2018-12-06T18:15:06.8244186Z _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
2018-12-06T18:15:06.8244400Z 
2018-12-06T18:15:06.8244638Z     def tear_down():
2018-12-06T18:15:06.8245076Z         import os
2018-12-06T18:15:06.8245339Z         import glob
2018-12-06T18:15:06.8245555Z         import psi4
2018-12-06T18:15:06.8245794Z         psi4.core.close_outfile()
2018-12-06T18:15:06.8246104Z         patterns = ['cavity.*', 'grid*', 'pytest_output.*h5',
2018-12-06T18:15:06.8246380Z                     'pytest_output.dat',
2018-12-06T18:15:06.8246851Z                     '*pcmsolver.inp', 'PEDRA.OUT*', 'timer.dat']
2018-12-06T18:15:06.8247099Z         pytest_scratches = []
2018-12-06T18:15:06.8247318Z         for pat in patterns:
2018-12-06T18:15:06.8247695Z             pytest_scratches.extend(glob.glob(pat))
2018-12-06T18:15:06.8247928Z         for fl in pytest_scratches:
2018-12-06T18:15:06.8248147Z >           os.unlink(fl)
2018-12-06T18:15:06.8249031Z E           PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'pytest_output.dat'
2018-12-06T18:15:06.8249336Z 
2018-12-06T18:15:06.8249582Z ..\lib\psi4\tests\conftest.py:28: PermissionError
```
So for now, they will run on core only!

**Comment by raimis** [comment]
@loriab  I think, it won't solve the problem on Windows: you are suppressing `FileNotFoundError`, but I'm getting `PermissionError`.

**Comment by loriab** [comment]
@raimis, yes, I've tried separate outfiles for individual tests, but pytest didn't like it, so need another bout. Also confirmed that there's no such thing as a session-wide tear-down with pytest-xdist. So, you're right, will have to stay serial for the moment. Sorry for the bad commit.

**Pull request merged**
