### PR TITLE
Adds delta corrections to string input parsing

### PR DESCRIPTION
**Pull request by dgasmith**
## Description
Adds the ability to use delta corrections for the CBS Wrapper's string-based input. For example, the following now works:

```python
energy('MP2/cc-pV[TQ]Z + D:CCSD(T)/cc-pVDZ')
gradient('MP2/cc-pV[TQ]Z + D:MP3/cc-pV[DT]Z')
opt('CISD/cc-pV[TQ]Z + D:CISDTQ/cc-pVDZ')
etc
```

Note that only a single delta is currently supported. We can consider multiple delta's in a string representation if there is an obvious way to do it. Ultimately, there is some notion that the string based parser should be fairly bare bones due to the relative inflexibility of the input. If required, the user can always use the `cbs` function directly for exactly control over the computation.

## Status
- [x]  Ready to go

### CODE REVIEW

**Comment by loriab** [comment]
extra open parenthesis in ``energy('MP2/cc-pV([TQ]Z + D:CCSD(T)/cc-pVDZ')`` above?

Yay, I'll have to try out the alternate syntax in pywrap-all.

**Comment by dgasmith** [comment]
@loriab Ah, no. Was trying to do a `+d` basis example. Everything that I messed with seemed to work and since we rely heavily on the CBS wrapper this should mostly be syntactic sugar at this point. Let me know if you hit any issues.

**Comment by dgasmith** [comment]
@loriab Hijacking this slightly, `nocp` was being parsed as `False` from the lowerkwargs function. Something to watch out for.

**Comment by loriab** [comment]
Agree, any kwargs that _can_ be interpreted as T/F but T/F doesn't span their allowed values, we need to be careful to put in that lowerkwargs list. And then it'll have to be `yes.match`-ed etc. in-function if allowed values are to be, for example, `yes|on|true|1|valerinmeyer|0|false|off|no`.

**Pull request merged**
