### PR TITLE
Docspass secondary user-facing driver fns

### PR DESCRIPTION
**Pull request by loriab**
## Description
consolidate cube-writing code

## Todos
Notable points that this PR has either accomplished or will accomplish.
- [x] consolidate three cube-centered pieces of code into one, libcubeprop. history of this in discussions below.
- [x] spruce up some docs, particularly when options text has been copied from read_options into the written docs, which then gets out of sync, and who knows which is right. want to replace these with `.. include:: autodir_options_c/globals__relativistic.rst`` that can't get out of sync
- [x] put in parameter, return, examples docstrings, versionadded (for wfn) for the lesser-used user-facing fns: oeprop, molden, cubeprop and get these into the Psithon Functions chapter of docs, rather than hidden away in the Programmers Manual --> Python Driver section. This is to satisfy the soft fail request for oeprop/molden/cubeprop (http://forum.psicode.org/t/ideas-to-simplify-wave-function-passing/161/10?u=loriab for discussion).
- [x] put off until later real standardization of handling oeprop, molden, cubeprop python fns and associated documentation

## Status
- [x]  Ready to go

### CODE REVIEW

**Comment by dgasmith** [comment]
Actually kind leaning back towards `*args` for things like Cube, OE, and properties. I think it looks a bit cleaner.

**Comment by loriab** [comment]
I've never really liked having `def property(` out on it's own. That is, I think it needs to be for driver routing purposes for the same reason `def run_dfmp2` and `def run_dfmp2_gradient` are different. For user-facing, I find `energy('mp2')` and `property('mp2')` too alike. I'd rather `properties=[]` was just a kwarg passed on to any of e(), g(), o(), f(), h() (with the understanding that an extra calc would be taken at the end of o()). But that's a large can of worms, so I'll just mention it as why I like properties as a kwarg.

So I like the kwarg for that reason. I don't mind the look of `*args` in oeprop, as certainly that the most important info being conveyed to the fn, though we scarcely ever use `*args` otherwise. I think the syntax of the c-side option is rather ungainly. Python-wise I'd love to do getters and setters on the CubeProp object so it acts more like the functional object. But what worries me is users not knowing where to go to specify what they want done– c-side options, kwargs, args, methods on object. Right now, you can do most any calc with the name argument to e(), etc. plus c-side options. 

But a more object-based API procedure in future will require more explicit options passing. And cubeprop, oeprop, moldenwriter are all very light-weight objects. So maybe going ahead and exporting and using all the getters and setters for these objects is the route. Figure out what the best syntax would be for that route, then use that to figure out a convenient one-line call to handle most use cases with minimal options spec. Maybe guided by the vml_cube script.

Sorry, this is a ramble. Certainly I'm not clear on what's best to do to accomodate all styles.

**Comment by dgasmith** [comment]
I do agree on most counts. Although, I think its worth pointing out that properties through OEProp are quite trivial; however, any other properties are going require linear response in some way or another which divorces itself quite radically from standard 'energy' calls.

**Comment by fevangelista** [comment]
I like the idea of adding getters/setters to cubeprop so that programmers can take it and do crazy things as plot orbitals during SCF cycles.  As far as the python side is concerned my vote goes to the *kwargs approach for cubeprop, I guess something like this:
cubeprop(wfn, tasks=['orbitals'], orbitals=[1,2,4,8])

**Comment by loriab** [comment]
For the third commit e94e8fce9aae8680cfa81ea11201ec14b38ea5f0, we have a digression into cube trimming. It turns out we have three variations on cube-file generation:

```
>>> grep CubicScalarGrid::CubicScalarGrid */*/*
bin/fisapt/csg.cc:CubicScalarGrid::CubicScalarGrid(boost::shared_ptr<BasisSet> primary, Options& options) :
lib/libcubeprop/csg.cc:CubicScalarGrid::CubicScalarGrid(
lib/libmints/gridprop.cc:CubicScalarGrid::CubicScalarGrid(
```

However, it looks like the libmints one isn't fully compiled.

```
# If you want to remove some sources specify them explicitly here
if(DEVELOPMENT_CODE)
   list(REMOVE_ITEM sources_list "gridprop.cc")
else()
   list(REMOVE_ITEM sources_list "gridprop.cc")
endif()
```

My guess at historical reconstruction is that @andysim was working on this in libmints and did the cubefile class and export in early 2014. And @robparrish did early work in libmints on gridprop. Then @robparrish and @fevangelista teamed up and filled out the class and the former checked it into bin/fisapt and the latter into lib/libcubeprop in mid 2015. The latter two are very similar.

I've been communicating with @fevangelista , and he suggested merging libcubeprop into the libmints version. But after reconsidering the history, I think libcubeprop should be the survivor. So, I've removed the libmints one, then redirected the fisapt one towards the libcubeprop one (adding the nuclear weights capability to the libcubeprop class).

So is this all good? At least it builds, cubeprop passes, and fisapt1 runs. @dgasmith , did I do the options passing into initialization right in src/lib/libcubeprop/csg.cc ? @robparrish , can I change your CUBIC_GRID_OVERAGE https://github.com/psi4/psi4/blob/master/src/bin/psi4/read_options.cc#L975 for fisapt to default to 4.0 bohr, rather than 2.0, so it's the same as libcubeprop? @fevangelista you mentioned using the CUBIC_GRID_FILEPATH from the libmints version, but doesn't CUBEPROP_FILEPATH https://github.com/psi4/psi4/blob/master/src/bin/psi4/read_options.cc#L204 fill that role?

**Comment by robparrish** [comment]
Yeah, there should definitely be only one CubicScalarGrid in PSI4. I agree
that it should be in something like libcubeprop. 4.0 bohr is actually a
better default - many density-based properties have significant features
out to more than 2.0 bohr.


-Rob

**Comment by fevangelista** [comment]
Yes @loriab, CUBEPROP_FILEPATH does indeed fill that role.  Thanks for the cleanup!

**Comment by andysim** [comment]
I don't think my gchat replies to you questions went through, @loriab, so I figured I should reply publicly.  I agree with your changes and I think your assessment of the history is pretty accurate, although my memory of what exactly I did with this code, and why, is shaky at best.  Let me know if I can help in any way.

**Comment by loriab** [comment]
I dropped the original goals of this PR and refocused on consolidating the cube-writing code. Properties generation and standards are in the air and everyone has signed off on the changes, so I think it worthwhile to get these changes into the main repo.

**Pull request merged**
