### PR TITLE
docs cleanup

### PR DESCRIPTION
**Pull request by loriab**
## Description
fixed up some but not all docs broken links from driver reorganization

## Status
- [ ]  Ready to go

### CODE REVIEW

**Comment by loriab** [comment]
@jturney , @edeprince3 , @ryanmrichard, @dgasmith  should look over a0a8c2b and see if it's ok. Basically, we were installing headers `src/lib/libmodule/*.h` to `includes/psi4/libmodule/*.h`, which is fine. But then we were installing headers `src/bin/module/*.h` to `includes/psi4/libmodule/*.h`, which meant that a header couldn't be referred to through the same path from both a source and installed file tree. Cue problems for compiling plugins against both. 

This commit installs bin headers to `includes/psi4/module/*.h`. Then since the intermediate lib or bin dir is gone, can't do `#include <../bin/fnocc/blas.h>` anymore, so added the bin dirs to the CMake includes path. Then also installed `FCMangle.h` since Fortran plugins needed it. 

The above gets Eugene's v2rdm built for me. Have I introduced any bad practices?

@dgasmith , contrary to what I wrote you, please hold off on merging this PR until this issue gets resolved

**Comment by edeprince3** [comment]
If there is something bad about this, I could always duplicate those blas files in my plugin.

**Comment by ryanmrichard** [comment]
In general your install structure should be the same as the source 
structure.  I would recommend installing to include/psi4/src/bin/ or 
include/psi4/src/lib/.

**Comment by loriab** [comment]
`src` is pretty common in a source tree, but I don't think I've ever seen it in an installed `include` tree. I could live with separate `lib` and `bin` underneath `include` if that's the consensus instead of adding `includes/bin` to the includes path.

**Comment by jturney** [comment]
I'm with @loriab on this: ```lib``` and ```bin``` underneath ```include```.

**Comment by loriab** [comment]
Thanks, @jturney . So add `lib` and `bin` under installed `include` rather than add `${PROJECT_SOURCE_DIR}/src/bin` & `${PROJECT_BINARY_DIR}/src/bin` to cmake includes_directories? If so, I'll patch that up tonight.

**Comment by jturney** [comment]
Yep.

**Comment by dgasmith** [comment]
FWIW I like having `lib` and `bin` in includes as well.

**Pull request merged**
