### PR TITLE
Some minor revisions

### PR DESCRIPTION
**Pull request by bozkaya**
## Description
Implementation of CD of (ab|cd) integrals for PPL term of CCSD, and some other minor revisions, such as renaming "WABEF_TYPE" option to "PPL_TYPE".  

## Todos
Notable points that this PR has either accomplished or will accomplish.
- [x] CD of (ab|cd) integrals for PPL term of DF-CCSD.

## Questions
- [x]  Question1

## Status
- [x]  Ready to go

### CODE REVIEW

**Comment by jturney** [comment]
Can you update the description of the PR to say what it does? Plus, if it is ready to merge when the testing is complete please click "Ready to go".

**Comment by loriab** [comment]
Looks good. This is background work, not ready-to-go method algorithm, right?

Sometimes the code in dfocc tends to repeat (e.g., below <10 lines of the 138 added really differ between newly added and existing member functions). Would you want to consider consolidating such functions in future for ease of maintenance? It might also help the module's build time.

```cpp
2c2
< //    CD-WabefT2:  
---
> //    WabefT2  
4c4
< void DFOCC::ccsd_WabefT2_cd()
---
> void DFOCC::ccsd_WabefT2()
6,8d5
< 
<     timer_on("WabefT2");
< 
11c8
<     SharedTensor2d V, Vs, Ts, Va, Ta, bQ;
---
>     SharedTensor2d V, Vs, Ts, Va, Ta;
12a10
>     timer_on("WabefT2");
44,48c42,44
<     bQ = SharedTensor2d(new Tensor2d("L <Q|AB>", nQ_cd, navirA, navirA));
<     bQ->read(psio_, PSIF_DFOCC_INTS, true, true);
<     K = SharedTensor2d(new Tensor2d("DF_BASIS_CC B (AB|Q)", navirA * navirA, nQ_cd));
<     K = bQ->transpose();
<     bQ.reset();
---
>     K = SharedTensor2d(new Tensor2d("DF_BASIS_CC B (AB|Q)", navirA * navirA, nQ));
>     K = bQabA->transpose();
>     bQabA.reset();
65c61
<             I->contract(false, true, navirA*nb, navirA, nQ_cd, K, K, 0, a*navirA*nQ_cd, 1.0, 0.0);
---
>             I->contract(false, true, navirA*nb, navirA, nQ, K, K, 0, a*navirA*nQ, 1.0, 0.0);
134a131,134
>     // Read B(Q,ab)
>     bQabA = SharedTensor2d(new Tensor2d("DF_BASIS_CC B (Q|AB)", nQ, navirA, navirA));
>     bQabA->read(psio_, PSIF_DFOCC_INTS, true, true);
> 
137c137
< }// end ccsd_WabefT2_cd
---
> }// end ccsd_WabefT2
```

**Comment by bozkaya** [comment]
Hi Lori,

In one of the functions, ccsd_WabefT2_cd(), I use CD factors for (ab|cd) integrals while for all the other 4-index integrals DF factors are used. In the second function, ccsd_WabefT2(), I use only DF factors for all 4-index integrals. Further, the explicit form of W_abef tensors are different for each functions. Hence, although both functions looks repeating each other, they are not in fact. At the theoretical point of view, there are significant differences between them. Hence, I prefer to keep them separate. However, it is possible to merge them. But in that case I will need if-else blocks at several places.

Of course, I create common functions if I need something repeatedly. However, if I see theoretically significant difference between two functions, then I prefer separate functions. For example, instead of merged CCD and CCSD codes, I prefer to keep them separate, which looks me better organised. Alternatively, it is possible to merge all MP2, MP3, MP2.5, LCCD, and CCD into CCSD code with many if-else blocks or switch-case blocks. For each different method creating different functions appears to me more systematic and better organised. 

I agree with you about avoiding repetitive codes for the sake of maintenance and build time. Presently, I am busy with CCSD(T) gradients. When I get some free time I will try to reduce repetitive codes if there are any, except for the similarities between high-order and lower-order methods, such as CCSD and MP3. @loriab

**Comment by dgasmith** [comment]
While DF and CD are theoretically different, practical implementations should be identical. Coding in this way allows DF and CD to be used interchangeably in addition to the many benefits of reducing the code base by a factor of two. If you want help factorizing your code, please feel free to ask. 

Going ahead and pulling this in.

**Comment by bozkaya** [comment]
Dear Daniel,

I think you misunderstood the discussion. In the DFOCC module there are many methods and all of them have both DF and CD versions. All DF and CD methods are implemented in the exactly the same source codes. There is no separate programming for DF and CD methods and there is no any repetition.

What we are discussing with Lori is something else. DF-CCSD code has many terms, the most expensive term is called PPL. For the PPL the default algorithm with the "pure" DF approach is:

D_ij^ab t_ij^ab = Tau_ij^ef W_abef

where W_abef tensor includes <ab|ef>_DF integrals (Einstein summation convention is used). Additionally, I have implemented the following hybrid approach recently:

D_ij^ab t_ij^ab = Tau_ij^ef <ab|ef>_DF/CD + W_ijam t_m^a

In the above formula <ab|ef>_DF/CD integrals are obtained using a DF/CD hybrid approach. I do not want to write too much details. CDS knows what I am doing and why I am trying it. Further, as you can see the explicit formulas are used are not identical with the default PPL algorithm. 

DFOCC::ccsd_WabefT2() function computes: 

D_ij^ab t_ij^ab = Tau_ij^ef W_abef

while DFOCC::ccsd_WabefT2_cd() function computes:

D_ij^ab t_ij^ab = Tau_ij^ef <ab|ef>_DF/CD

contraction. Hence, each function compute a different term indeed. The difference is not just the DF vs CD. Therefore, there is no repetition of codes, but there are similarities in both functions of course. @dgasmith @loriab

**Comment by bozkaya** [comment]
In the above comment <ab|ef> integrals are disappeared somehow. The "_DF/CD" should be "<ab|ef>_DF/CD". @dgasmith @loriab

**Comment by bozkaya** [comment]
There should be a problem in Github editor, Dirac ordered ERI integrals are not shown. I think you got the formulas. As a final try I will write them using Mulliken ordering instead of Dirac.

Hybrid approach for PPL:
D_ij^ab t_ij^ab = Tau_ij^ef (ae|bf)_DF/CD + W_ijam t_m^a

DFOCC::ccsd_WabefT2_cd() function computes the

D_ij^ab t_ij^ab = Tau_ij^ef (ae|bf)_DF/CD

part. @dgasmith @loriab

**Comment by loriab** [comment]
Hi @bozkaya, I agree that if/else blocks everywhere are not something anyone wants to see for your code. But I believe the trend with C++ code is toward greater abstraction so that the same code can cover more uses. Perhaps I didn't choose a fitting example above, but various people who have looked into DFOCC have been alarmed at the seemingly repeated code and numerous data structures. So maybe, as you say, when the individual methods are working as you want them, a consolidation and refactoring step could be useful.

CCSD(T) gradients sound exciting!

**Comment by bozkaya** [comment]
Hi @loriab,

I promise I will find a consolidation way to reduce the source code as much as possible when I find a free time to work on it. Presently, I am more focused on the implementation and adding some new features to DFOCC. Even If we suppose that there are some redundant codes in DFOCC, it is a not big problem. It may just take a few more minutes of building time and a slightly additional storage.  Further, I think the relatively large body of DFOCC w.r.t. some other modules is understandable since DFOCC includes many post-HF methods (standard and OO) including energies and gradients, and most of them are implemented for RHF and UHF refs.

**Pull request merged**
