### PR TITLE
G* FCHK output, and Distributed Multipole Analysis

### PR DESCRIPTION
**Pull request by andysim**
## Description
Increases compatibility with external analysis tools, by providing Gaussian formatted checkpoint file (FCHK) output.  Also adds built-in distributed multipole analysis via Stone's GDMA package.

## Todos
- [x] Add FCHK writer to libmints.
- [x] Incorporate GDMA 2, for distributed multipole analysis.
- [x] Add GDMA options, to prevent user from having to provide a separate input file.
- [x] Put GDMA results in the variables map.
- [x] Add GDMA test case.
- [x] Document FCHK writer and GDMA.

## Questions
- [x]  Although GDMA is released under GPL2, I want to try to contact Anthony Stone to get explicit permission to release his code as a subdirectory of Psi4.

I don't think there are any legal problems with including an FCHK writer; I simply followed the [format description](http://www.gaussian.com/g_tech/g_ur/f_formchk.htm) and checked it against some of the GDMA examples.  Anybody disagree?

## Status
- [x]  Ready to go

### CODE REVIEW

**Comment by andysim** [comment]
I'm aware that we're not looking for new features right now, but I had to write this anyway so I decided to launch a PR.  It should be ready to go very soon.

**Comment by CDSherrill** [comment]
Ooh, very exciting!

**Comment by andysim** [comment]
Because the code just calls GDMA, which I turned into a function call instead of an executable, I think we should distributed the GDMA manual with the Psi4.  I dumped the PDF into doc/external for now.  Any objections?

**Comment by loriab** [comment]
Great to see this capability added! A pdf in doc/external can probably be linked to from Sphinx docs, though it won't be searchable. If Stone isn't keen on the subdir of Psi4 scheme, we could arrange so that his code stays on his website, a conda recipe (or cmake Add_External_Project) curls it from the web, a patch converts it to build as a lib rather than an exe, and so libgdma.so stays outside psi4. Then the interface code between gdma and libmints stays in psi4. Would like to make the built library available from our conda channel, though.

**Comment by andysim** [comment]
Excellent idea about the Conda distribution, Lori.  I emailed Prof. Stone yesterday, but haven't heard back.  He is retired now, so I don't know if his Cambridge email is active; his seminal red book was updated last year so I think he's still doing some work.  I doubt he will object to our distribution idea; I think he would've chosen a different license to GPL if he didn't want his code to be used in this way.  Regardless, I think we should wait a week to hear back and merge the PR if we don't get a response.  He deserves to have a say in how we handle his code.

**Comment by CDSherrill** [comment]
I'm ok with linking to a PDF manual or external website for GDMA, but I
think we would also at least need a little paragraph in our manual
explaining that the capability is there, and giving any Psi keywords that
are used to access GDMA.

**Comment by andysim** [comment]
I added full Sphinx documentation for both the FCHK writer and for GDMA, in commit f2aca7, @CDSherrill.  I heard back from Prof. Stone and he has kindly agreed to allow us to use GDMA in the way that we want to, so this PR is ready to go.  In his message, he raised the issue of our output providing only kcal/mol units, and mentioned that he would like to have kJ/mol units too, in line with IUPAC guidelines.  We certainly should make the hartree to kJ/mol available directly in physconst (instead of having to go through kcal/mol), but what do think about having both units available in the SAPT output?

**Comment by loriab** [comment]
I've no objection to a third column in the SAPT output. But then, I've always been an advocate of output being as wide as necessary to show the data. Can scan psi to find other cases of kcal/mol where kJ/mol needs to be added. Probably `database()` and `cp()` probably.

**Comment by andysim** [comment]
I took a look at the src subdirs, and could only find SAPT and thermo that use the kcal conversion, so they should be easy enough to modify.  I just didn't want to start messing with other people's nice, clean SAPT code.  In the spirit of standards compliance, I do favor the use of SI units; most US users will still want kcal units, so providing both would be ideal if there is space.

**Comment by CDSherrill** [comment]
Wonderful about the GDMA distribution!

Yes, if the output does not get too cluttered, I would support kJ/mol as
another column.  I don't want infinitely wide output files :). But one more
column of something not printed to too many digits can probably be
accommodated.

**Pull request merged**
