### PR TITLE
PR template and dlpno test fix

### PR DESCRIPTION
**Pull request by loriab**
## Todos

- [x] Put back separate section for API/RN headlines in PR template
- [x] Looks like the dlpno fix in #2707 slightly broke a test. Zach has confirmed this is the reasonable fix. Only showed up in quad-zeta cbs step

## Checklist
- [ ] ~Tests added for any new features~
- [x] [All or relevant fraction of full tests run](http://psicode.org/psi4manual/master/build_planning.html#how-to-run-a-subset-of-tests)

## Status
- [x] Ready for review
- [x] Ready for merge

### CODE REVIEW

**Review by zachglick — APPROVED** [review]

**Comment by JonathonMisiewicz** [comment]
What's the difference between API and Todos in the PR template?

**Comment by loriab** [comment]
> What's the difference between API and Todos in the PR template?

Yeah, that's the tricky part (and why the original template that had two sections --- user interest and dev interest --- got merged into the one section currently active). Usually I'd try to put in the Todos section all the why details I'd want to remember looking back on the PR and the details needed by reviewers. Then by the time of writing RN, I'd have enough perspective to condense into key points for users. So for https://github.com/psi4/psi4/pull/2653#issue-1323866437 recently, the RN section would be "added conventional remp2 and oremp2, refined qcvar setting in occ module, and tightened occ convergence".

Glad of any better way to phrase or separate the two sections. (Do we want two sections -- I assumed so after conf call?)  For reference, pb11 has: https://raw.githubusercontent.com/pybind/pybind11/master/.github/pull_request_template.md

**Comment by JonathonMisiewicz** [comment]
```
## User-Facing Notes
<!-- A bullet-point format description of how this PR affects the user. This will be copy-pasted into the release notes. May be empty. -->
- [ ] Note 1
- [ ] Note 2

## Dev-Facing Notes
<!-- A bullet-point format description of what this PR does "at a glance." Target audience is code reviewers and other devs skimming PRs. Should be more technical than user notes. Should never be empty.  -->
- [ ] Note 1
- [ ] Note 2
```

**Comment by loriab** [comment]
Regarding https://github.com/psi4/psi4/pull/2718#issuecomment-1244232466 above, `<!--` descriptions lgtm. I'd suggest for section titles:
* User API & Changelog headlines
* Dev notes & details

**Comment by loriab** [comment]
Amusing look back: https://github.com/psi4/psi4/commit/af471c484dfcfd48aeab098f0dcbd200fe2c7271

**Review by maxscheurer — APPROVED** [review]

**Review by JonathonMisiewicz — APPROVED** [review]

**Pull request merged**
