### PR TITLE
Corrected links to functions

### PR DESCRIPTION
**Pull request by mhlechner**
## Description
Broken hyperlinks to other energy, ... functions corrected.

## Todos
- [x] Fix broken hyperlinks.

## Status
- [x]  Ready to go

### CODE REVIEW

**Comment by mhlechner** [comment]
Similar to pull request #497 but should fix all broken links, not only those to energy/optimize/frequency.

**Comment by loriab** [comment]
LGTM

**Comment by dgasmith** [comment]
LGTM

**Comment by andysim** [comment]
LGTM

**Comment by dgasmith** [comment]
@mhlechner Can you please update your fork with directions from [here](https://github.com/psi4/psi4/wiki/1_Obtaining#get-updates-3). Also, let us know if any of the directions are misleading!

**Comment by andysim** [comment]
Thanks for working on the conflict resolution.  LGTM

**Pull request merged**
