### PR TITLE
Sync all def2 fit basis sets to the universal fitting sets from BSE.

### LINKED ISSUE #1798: def2-qzvp issues
The def2-qzvp set is malformed for Rb
```
F  1  1.00
   .85245  
****
```
Sr
```
F  1  1.00
   .9954  
****
```
Cs
```
F  1  1.00
   .58777
****
```
and Ba
```
F  1  1.00
   .08788
G  1  1.00
   .5     
****
```

### PR DESCRIPTION
**Pull request by susilehtola**
## Description
This PR replaces all def2 jfit sets with the universal jfit sets from the Basis Set Exchange, and the jkfit sets with the universal jkfit set.

At present, there are some inconsistencies between the jfit sets
```
b=( def2*jfit.gbs ); for((ib=0;ib<${#b[@]};ib++)); do for((jb=0;jb<ib;jb++)); do echo -n "${b[ib]} vs ${b[jb]}: "; diff ${b[ib]} ${b[jb]}| wc -l;done;done
def2-qzvpp-jfit.gbs vs def2-qzvp-jfit.gbs: 47
def2-sv_p_-jfit.gbs vs def2-qzvp-jfit.gbs: 101
def2-sv_p_-jfit.gbs vs def2-qzvpp-jfit.gbs: 54
def2-svp-jfit.gbs vs def2-qzvp-jfit.gbs: 47
def2-svp-jfit.gbs vs def2-qzvpp-jfit.gbs: 0
def2-svp-jfit.gbs vs def2-sv_p_-jfit.gbs: 54
def2-tzvp-jfit.gbs vs def2-qzvp-jfit.gbs: 47
def2-tzvp-jfit.gbs vs def2-qzvpp-jfit.gbs: 0
def2-tzvp-jfit.gbs vs def2-sv_p_-jfit.gbs: 54
def2-tzvp-jfit.gbs vs def2-svp-jfit.gbs: 0
def2-tzvpp-jfit.gbs vs def2-qzvp-jfit.gbs: 47
def2-tzvpp-jfit.gbs vs def2-qzvpp-jfit.gbs: 0
def2-tzvpp-jfit.gbs vs def2-sv_p_-jfit.gbs: 54
def2-tzvpp-jfit.gbs vs def2-svp-jfit.gbs: 0
def2-tzvpp-jfit.gbs vs def2-tzvp-jfit.gbs: 0
```
and the jkfit sets as well
```
 b=( def2*jkfit.gbs ); for((ib=0;ib<${#b[@]};ib++)); do for((jb=0;jb<ib;jb++)); do echo -n "${b[ib]} vs ${b[jb]}: "; diff ${b[ib]} ${b[jb]}| wc -l;done;done
def2-qzvpp-jkfit.gbs vs def2-qzvp-jkfit.gbs: 4
def2-sv_p_-jkfit.gbs vs def2-qzvp-jkfit.gbs: 1727
def2-sv_p_-jkfit.gbs vs def2-qzvpp-jkfit.gbs: 1727
def2-svp-jkfit.gbs vs def2-qzvp-jkfit.gbs: 1723
def2-svp-jkfit.gbs vs def2-qzvpp-jkfit.gbs: 1727
def2-svp-jkfit.gbs vs def2-sv_p_-jkfit.gbs: 4
def2-tzvp-jkfit.gbs vs def2-qzvp-jkfit.gbs: 0
def2-tzvp-jkfit.gbs vs def2-qzvpp-jkfit.gbs: 4
def2-tzvp-jkfit.gbs vs def2-sv_p_-jkfit.gbs: 1727
def2-tzvp-jkfit.gbs vs def2-svp-jkfit.gbs: 1723
def2-tzvpp-jkfit.gbs vs def2-qzvp-jkfit.gbs: 0
def2-tzvpp-jkfit.gbs vs def2-qzvpp-jkfit.gbs: 4
def2-tzvpp-jkfit.gbs vs def2-sv_p_-jkfit.gbs: 1727
def2-tzvpp-jkfit.gbs vs def2-svp-jkfit.gbs: 1723
def2-tzvpp-jkfit.gbs vs def2-tzvp-jkfit.gbs: 0
```

According to @bennybp the sets should be all the same, see https://github.com/MolSSI-BSE/basis_set_exchange/issues/103

## Todos
Notable points (developer or user-interest) that this PR has or will accomplish.
- [x] remove redundant def2-*-[jk|j]fit basis sets

Presuming Susi accepts my PR, this one will additionally accomplish
- [x] fixes #1798 At least make all the def2 orbital and rifit basis sets parseable. These have been read through diff_gbs.py so I know all the elements parse now. Variety of errors found.
- [x] helps #1804 by redirecting def2-*-jkfit specifications toward the universal files. only took about four files to find a satisfactory and minimally disruptive place for a simple map-and-warn :-(
- [x] helps plugins like v2rdm_casscf that are adding internal pb11 by attaching the found Python headers location to the plugin target.

## Checklist
- [ ] Tests added for any new features
- [ ] [All or relevant fraction of full tests run](http://psicode.org/psi4manual/master/build_planning.html#how-to-run-a-subset-of-tests)

## Status
- [x] Ready for review
- [x] Ready for merge

### CODE REVIEW

**Comment by susilehtola** [comment]
> I wonder if instead of doing it this way it wouldn't be cleaner to add def2-universal-JFIT/JKFIT as a basis set, and select that when any of the def2 family is used as an actual orbital basis. That way, this should be futureproof for the migration to BSE-supplied data.

Thanks for the suggestion; this was my original idea as well but I didn't know out of hand how to achieve this, so I was hoping someone would give me a hint!

**Comment by PeterKraus** [comment]
The problem seems to be that the "default" fitting basis set remains `def-qzvpp-jkfit`:

https://dev.azure.com/psi4/psi4/_build/results?buildId=1658&view=logs&j=96451287-da82-57a8-2c11-8da7db9ab71a&t=895e49e6-cad9-5b25-6d66-c0b61859d928&l=698

I think those can be modified here:

https://github.com/psi4/psi4/blob/287610542a3f71ec58007da9df7e6ba451c83fc7/psi4/driver/qcdb/libmintsbasisset.py#L761-L765

Also, could you add a quick comment about what you did into the psi4/share/psi4/basis/NOTES file, here: https://github.com/psi4/psi4/blob/309b058ce75b55c8d8e19245b6ce480c00f1797e/psi4/share/psi4/basis/NOTES

**Comment by loriab** [comment]
I prefer the py file editing to the text basis file editing so we can still do a grand comparison upon molssi switchover to bse. 

If useful, there’s also a gbsdiff.py script probably in basis/primitives that will do a per element diff of two gbs files insensitive to format or shell order.

**Comment by susilehtola** [comment]
> I prefer the py file editing to the text basis file editing so we can still do a grand comparison upon molssi switchover to bse.

@loriab Could you clarify? Just add the universal set, don’t remove the old (incorrect) ones?

**Comment by loriab** [comment]
I've diffed the universal and existing jkfit/jfit with diff_gbs.py (screenshot below), and all's well. (black is unchanged, blue adds an element, yellow is different but I don't really care about thallium and we don't use jfit anyways.

I think if you edit the basis in tests mints9 and python/mints9 to universal, that should finally heal CI. Thanks for fixing this up.

Screen Shot 2020-02-06 at 8 24 05 PM

**Comment by susilehtola** [comment]
Merged, as I think I've eliminated all explicit uses of def2-(basis)-JFIT and def2-(basis)-JKFIT: the Azure build went through on Windows but failed on the linuxes due to sns-mp2 where the sns-m2 code appears to explicitly rely on the old-fashioned input

https://github.com/DEShawResearch/sns-mp2/blob/fcce1d053b42ee7185fd550d19ab9beda08ad3ed/snsmp2/snsmp2.py#L93

**Comment by loriab** [comment]
Thanks. I added one old basis set use back into mints9 for coverage. Yay for -30k net loc.

**Comment by susilehtola** [comment]
@dgasmith ready to merge

**Pull request merged**
