### PR TITLE
F-SAPT, rebased

### PR DESCRIPTION
**Pull request by loriab**
## Description
Documents F/I-SAPT capabilities, adds F/I-SAPT test cases and samples, and makes F/I-SAPT postprocessing scripts available in install/share.

## Todos
Notable points that this PR has either accomplished or will accomplish.
- [x] Enables the average citizen to quickly begin using F/I-SAPT.

## Status
- [x]  Ready to go. Looks ready to me, though there may well be further reST changes after viewing the docs build. @robparrish may want to look it over. We'll close the other PR.

### CODE REVIEW

**Comment by robparrish** [comment]
Looks fine to me. Thanks Lori!

-Rob

**Comment by jturney** [comment]
LGTM.

**Comment by loriab** [comment]
lgtm

**Comment by andysim** [comment]
LGTM

**Pull request merged**
