### PR TITLE
Switch MSVC to LLVM compiler for Windows builds

### PR DESCRIPTION
**Pull request by raimis**
## Description
This is part of *Psi4* porting to Windows (#933).

## Todos
Notable points (developer or user-interest) that this PR has or will accomplish.
- [x] Switch MSVC to LLVM compiler
- [x] Fix linkage errors
- [x] Update passing Windows tests

## Checklist
- [x] ~~Tests added for any new features~~
- [x] [All or relevant fraction of full tests run](http://psicode.org/psi4manual/master/build_planning.html#how-to-run-a-subset-of-tests)

## Status
- [x] Ready for review
- [x] Ready for merge

### CODE REVIEW

**Comment by raimis** [comment]
@robertodr thanks for prompt review, but this just the first commit of a big PR... :)

**Comment by raimis** [comment]
`LLVM` compatibility with `MSVC` ABI is not yet complete (http://clang.llvm.org/docs/MSVCCompatibility.html), so compiling with `LLVM` and linking with the C++ library from `MSVC`, might give some problems.

I got just one linkage problem! It happens when trying to create `psi::PsiOutStream` with `std::make_shared`, while passing `mode` argument:
```c++
auto printer = std::make_shared<psi::PsiOutStream>("filename", std::ostream::trunc);

error LNK2001: unresolved external symbol "__declspec(dllimport) public: static enum std::_Iosb<int>::_Openmode const std::_Iosb<int>::trunc" (__imp_?trunc@?$_Iosb@H@std@@2W4_Openmode@12@B)
```
but it works, in such cases:
```c++
// Creating std::share_ptr explicitly
auto printer = std::shared_ptr(new psi::PsiOutStream("filename", std::ostream::trunc));

// Using the argument default value (mode = std::ostream::trunc)
auto printer = std::make_shared<psi::PsiOutStream>("filename");

// Using a temporary variable
auto mode = mode = std::ostream::trunc;
auto printer = std::make_shared<psi::PsiOutStream>("filename", mode);
```
I use the last case to fix the code.

**Comment by andysim** [comment]
Hi, @raimis, thanks again for the very useful contributions - we really appreciate your time.  None of use have any concerns with this one, but we noticed that the `ready to merge` box is not checked.  Can we pull this one in now?

**Comment by raimis** [comment]
Yes, it is ready!

**Comment by loriab** [comment]
There's about 150k lines of psi4 build in appveyor now, mostly warnings. Was this expected?

**Comment by raimis** [comment]
Yes, *LLVM* is more picky than *MSVC*. Most of them are harmless and could be disable to be sure we don't miss something serious.

**Comment by loriab** [comment]
I guess we must be suppressing a lot with linux clang. Or we need a clean-up-the-warnings workday. Thanks.

**Pull request merged**
