### PR TITLE
Add aug-pcSseg-X basis sets

### PR DESCRIPTION
**Pull request by jvansan**
## Description
Added aug-pcSseg-X.gbs (X=0,1,2,3,4) from EMSL.
Added pc-X and other various polarization consistent basis sets, also from EMSL.

### CODE REVIEW

**Comment by dgasmith** [comment]
Sorry we haven't been in touch. This is probably good, but we are waiting on #442 to make any more movements on accepting additional PR's.

**Comment by loriab** [comment]
Could you put together a table and/or a couple sentences about whether these basis sets are general or specialized (properties, etc.) and how the sets relate to each other diffuse-wise, zeta-wise, and in any other relevant dimension? We'll want something like that for the docs page: http://psicode.org/psi4manual/master/basissets_tables.html Don't worry about formatting or checking it in; just the info would be great.

Also, please confirm that this basis family has **no** ECP needs.

Do you have any info on good fitting (jk, ri) basis sets for these orbital sets? We'll probably default to an appropriately sized def2 fitting, but may as well make an informed choice if there's info to be had.

Thanks!

**Comment by jvansan** [comment]
The Jensen *pc* basis sets [1-7] are analogous to the Dunning *cc* basis sets and may be used in their place. They were designed to converge monotonically to the HF basis set limit, and have been shown to do so faster than the *cc* basis sets for molecular and spectroscopic properties. [8]

Confusingly, the name pc-n actually refers to an n+1-zeta basis set, that is pc-2 is a triple-zeta basis set.

aug-pc-n includes diffuse functions.

pcseg-n is a segmented version of the pc-n basis sets, thus more computationally expensive. [9]

pcSseg-n is an even larger segmented version of the pc-n basis sets, optimized for NMR shielding calculations. [10]

I have not been able to find any literature on preferred auxiliary basis sets for use with these, so appropriately sized def2 basis sets should be sufficient. I have been experimenting with these with rather good success.

I can also **confirm** that these basis sets do not require ECPs.

Perhaps on the list of wants would be to modify the CBS python wrapper to allow for extrapolation with these basis sets. I may take a stab at this if I can find time in the next little while.

[1] Frank Jensen, Polarization consistent basis sets: Principles, J. Chem. Phys. 115, 9113 (2001).
[2] Frank Jensen, Polarization consistent basis sets. II. Estimating the Kohn-Sham basis set limit, J. Chem. Phys. 116, 7372 (2002).
[3] Frank Jensen, Polarization consistent basis sets. III. The importance of diffuse functions, J. Chem. Phys. 117, 9234 (2002).
[4] Frank Jensen, Trygve Helgaker, Polarization consistent basis sets. V. The elements Si-Cl, J. Chem. Phys. 121, 3463 (2004).
[5] Frank Jensen, Polarization consistent basis sets. VI. The elements He, Li, Be, B, Ne, Na, Mg, Al, Ar, J. Phys. Chem. A 111, 11198 (2007).
[6] Frank Jensen, Polarization Consistent Basis Sets. VII. The Elements K, Ca, Ga, Ge, As, Se, B
r and Kr, J. Chem. Phys. 136, 094110 (2012).
[7] Frank Jensen, Polarization Consistent Basis Sets. VIII. The Transition Metals Sc-Zn, J. Chem. Phys. 138, 014107 (2013).
[8] Teobald Kupka, Carmay Lim, Polarization-Consistent versus Correlation-Consistent Basis Sets in Predicting Molecular and Spectroscopic Properties, J. Phys. Chem. A. 111m 1927 (2007).
[9] Frank Jensen, Unifying General and Segmented Contracted Basis Sets. Segmented Polarization Consistent Basis Sets., Journal of Chemical Theory and Computation 10, 1074-1085 (2014) DOI: 10.1021/ct401026a.
[10] Frank Jensen, Segmented Contracted Basis Sets Optimized for Nuclear Magnetic Shielding, J. Chem. Theory Comp. 11, 132 (2015).

**Comment by susilehtola** [comment]
"pcseg-n is a segmented version of the pc-n basis sets, thus more computationally expensive. [9]"

Well, that's not really true: it depends on your integrals driver. If your program handles everything as general contractions, then segmented basis sets are slower. If it handles everything as segmented contractions, then general contracted basis sets are **much much** slower...

**Comment by loriab** [comment]
replaced by #475 after rebase through CMakeRewrite-KillTheBoost

**Pull request closed without merging**
