### PR TITLE
Revert changes to cmake that cause Forte compilation problems on Mac

### PR DESCRIPTION
**Pull request by fevangelista**
## Description
Recent changes to the cmake build systems introduced an issue when compiling psi4 plugins and Forte on a Mac. Compilation fails at the linking stage with the error
```
ld: can't link with bundle (MH_BUNDLE) only dylibs (MH_DYLIB)
```

This PR reverts two changes.

## Questions
- [ ] Is there a better solution that still uses `pybind11_add_module(core MODULE NO_EXTRAS core.cc)`?

## Checklist
- [ ] [All or relevant fraction of full tests run](http://psicode.org/psi4manual/master/build_planning.html#how-to-run-a-subset-of-tests)

## Status
- [x] Ready for review
- [ ] Ready for merge

### CODE REVIEW

**Comment by fevangelista** [comment]
No problem, this is a simple enough hack that we can apply locally for now. Perhaps the PR will evolve into a better solution once we investigate more.

**Comment by PeterKraus** [comment]
I guess if there are near-future plans to find a better solution, then there's no point merging, right?

**Comment by dgasmith** [comment]
Probably want a @loriab review on this as well before merging.

**Comment by loriab** [comment]
@robertodr, was using `MODULE` instead of `SHARED` deliberate? https://github.com/pybind/pybind11/blob/master/tools/pybind11Tools.cmake#L116

I confirm that v2rdm won't build in psi4's current state with same module error.

@fevangelista, there's a new ambit 0.3 conda pkg available for Mac now.

**Comment by robertodr** [comment]
I was following the CMake manual: "SHARED libraries are linked dynamically and loaded at runtime. MODULE libraries are plugins that are not linked into other targets but may be loaded dynamically at runtime using dlopen-like functionality." Guess I was wrong? Maybe @fevangelista can test that out?

**Comment by loriab** [comment]
testing the `MODULE` --> `SHARED` on v2rdm now

**Comment by PeterKraus** [comment]
Closing as #1642 resolves the issue.

**Pull request closed without merging**
