### PR TITLE
Make psi4.so work again. Based on work by @bennybp

### PR DESCRIPTION
**Pull request by loriab**
This gets us back to a working ``make psi4so``. Basic docs at https://github.com/psi4/psi4/wiki/8_FAQ_Contents#psi4so

### CODE REVIEW

**Comment by dgasmith** [comment]
I think this looks fine. @bennybp do you have anything else to add to this?

**Comment by bennybp** [comment]
Has this been tested with `make psi4so` yet? I'm not sure it would compile. There were a few changes in my commit that were needed to remove some ambiguity of some types.

Or is this just laying the groundwork a bit?

**Comment by loriab** [comment]
This compiles for me on Linux intel compilers and runs. Yes, @bennybp I saw your `boost::python` additions like at https://github.com/psi4/psi4private/commit/af66bb495f285c4e86cf233fa593718e2ef47a45#diff-6aec7708a780d624eaec1709674ccf5eL1043 and tried with and without and both worked fine. You definitely had problems w/o those disambiguations?

**Comment by bennybp** [comment]
Hmm I definitely did, but don't anymore. Likely some of the cleaning that's been done lately removed dependency on a library that also defined a `str` class.

**Comment by loriab** [comment]
Ok, sounds safe to leave the `boost::python` out for the time being and go ahead and merge this PR to get the python so `psi4.so` working again. @bennybp, you'll have noticed that I didn't do the initialize and finalize changes possibly necessary for your linux so `libpsi4.so` since I couldn't test the built product. Whenever you like, add a `libpsi4so` target to build your version. Even if the python so and the linux so are identical, I think they'll have different names and install locations (site-packages and lib, respectively), so they'll need different targets.

**Comment by dgasmith** [comment]
Looks like we can merge this for now, might need to revisit later to fully flesh out all functionality.

**Pull request merged**
