### PR TITLE
SAPT(DFT) Timers & Misc.

### PR DESCRIPTION
**Pull request by yxie326**
## Description
Adds timers for SAPT(DFT) procedure to track bottle-necks for improving performance. Information printed into `timer.dat`. A few other minor modifications are also done (see below).

## Todos
Notable points that this PR has either accomplished or will accomplish.
* **Developer Interest**
  - [x] Added step-wise timers for SAPT(DFT).
  - [x] Appended missing dimer SCF step for FISAPT timer.
  - [x] Exported timer functions to python-side.
  - [x] Fixed a few typos in SAPT(DFT) procedure `sapt_proc.py`.
  - [x] Expanded output width for `timer.dat` to avoid overflowing.

## Checklist
- [x] [All or relevant fraction of full tests run](http://psicode.org/psi4manual/master/build_planning.html#how-to-run-a-subset-of-tests)

## Status
- [x] Ready for review
- [x] Ready for merge

## Attachment
[timer_dat.txt](https://github.com/psi4/psi4/files/2203735/timer_dat.txt)
Seems that github doesn't like .dat files so I renamed it.

### CODE REVIEW

**Comment by dgasmith** [comment]
Overall looks good. Can you provide the output of a `timer.dat` with these changes?

**Comment by loriab** [comment]
For those that would like to see it

```

Host: ds8

Timers On : Mon Jul  9 16:54:55 2018
Timers Off: Mon Jul  9 16:56:09 2018

Wall Time:       74.42 seconds

SAPT(DFT): Dimer SCF                :      2.883u      0.033s      1.795w      1 calls
JK: (A|mn)                          :      3.583u      0.000s      2.172w      5 calls
JK: (A|Q)^-1/2                      :      0.467u      0.000s      0.285w      5 calls
JK: (Q|mn)                          :      0.533u      0.017s      0.329w      5 calls
HF: Form H                          :      0.017u      0.000s      0.030w      5 calls
HF: Form S/X                        :      0.017u      0.000s      0.010w      5 calls
HF: Guess                           :      1.300u      0.017s      0.799w      5 calls
SAD Guess                           :      1.300u      0.017s      0.788w      5 calls
HF: Form G                          :     53.400u      0.583s     32.417w     55 calls
JK: D                               :      0.000u      0.000s      0.003w     97 calls
JK: USO2AO                          :      0.017u      0.000s      0.002w     97 calls
JK: JK                              :      6.300u      0.000s      3.835w     97 calls
JK: J                               :      0.450u      0.000s      0.271w     97 calls
JK: J1                              :      0.133u      0.000s      0.135w    109 calls
JK: J2                              :      0.317u      0.000s      0.130w    109 calls
JK: K                               :      5.800u      0.000s      3.538w     97 calls
JK: K1                              :      5.450u      0.000s      3.301w    163 calls
JK: K2                              :      0.350u      0.000s      0.235w    109 calls
JK: AO2USO                          :      0.000u      0.000s      0.000w     97 calls
HF: Form F                          :      0.000u      0.000s      0.002w     55 calls
HF: DIIS                            :      0.083u      0.000s      0.063w     55 calls
DIISManager::add_entry              :      0.000u      0.000s      0.017w     50 calls
DIISManager::extrapolate            :      0.050u      0.000s      0.018w     45 calls
bMatrix setup                       :      0.000u      0.000s      0.008w     45 calls
bMatrix pseudoinverse               :      0.033u      0.000s      0.003w     45 calls
New vector                          :      0.017u      0.000s      0.006w     45 calls
HF: Form C                          :      0.217u      0.000s      0.110w     55 calls
HF: Form D                          :      0.000u      0.000s      0.001w     55 calls
SAPT(DFT): Monomer A SCF            :      2.983u      0.050s      1.849w      1 calls
SAPT(DFT): Monomer B SCF            :      2.883u      0.050s      1.795w      1 calls
SAPT(DFT):SAPT:elst                 :      0.000u      0.000s      0.000w      1 calls
SAPT(DFT):SAPT:exch                 :      0.233u      0.000s      0.148w      1 calls
SAPT(DFT):SAPT:ind                  :      1.867u      0.000s      1.117w      1 calls
SAPT(DFT): Monomer A DFT            :     29.233u      0.367s     17.795w      1 calls
V: Grid                             :      0.717u      0.000s      0.446w      2 calls
RV: Form V                          :     51.150u      0.583s     31.023w     24 calls
Properties                          :     51.000u      0.717s     30.270w  55840 calls
Functional                          :     16.767u      0.117s     10.525w  55840 calls
V_xc                                :     10.133u      0.133s      6.536w  33504 calls
SAPT(DFT): Monomer B DFT            :     28.650u      0.350s     17.421w      1 calls
SAPT(DFT):SAPT(DFT):JK              :      0.250u      0.000s      0.149w      1 calls
SAPT(DFT):SAPT(DFT):elst            :      0.000u      0.000s      0.000w      1 calls
SAPT(DFT):SAPT(DFT):exch            :      0.200u      0.000s      0.126w      1 calls
SAPT(DFT):SAPT(DFT):ind             :     45.583u      0.533s     27.664w      1 calls
RV: Form Vx                         :     44.150u      0.533s     26.828w     16 calls
Derivative Properties               :      9.050u      0.050s      5.407w  22336 calls
V_XCd                               :      6.933u      0.067s      4.389w  22336 calls
SAPT(DFT):SAPT(DFT):disp            :      5.000u      0.167s      3.141w      1 calls
DFH: initialize()                   :      0.583u      0.000s      0.350w      1 calls
DFH: sparsity prep                  :      0.033u      0.000s      0.024w      1 calls
DFH: AO Construction                :      0.533u      0.000s      0.313w      1 calls
DFH: transform()                    :      0.117u      0.017s      0.075w      1 calls
DFH: Total Workflow                 :      0.033u      0.000s      0.021w      6 calls
DFH: Total Transform                :      0.017u      0.000s      0.014w      4 calls
DFH: 1st Contraction                :      0.000u      0.000s      0.009w      2 calls
DFH: 2nd Contraction                :      0.017u      0.000s      0.005w      2 calls
DFH: MO to disk                     :      0.000u      0.000s      0.001w      2 calls
DFH: Direct Contractions            :      0.083u      0.017s      0.046w      1 calls
DF Integrals                        :      0.767u      0.083s      0.514w      1 calls
W Integrals                         :      0.000u      0.000s      0.001w      1 calls
Exch-Disp20 N^5                     :      0.033u      0.033s      0.043w      1 calls
Exch-Disp20 N^4                     :      0.267u      0.033s      0.178w      1 calls

-----------------------------------------------------------
SAPT(DFT): Dimer SCF                :      2.883u      0.033s      1.795w      1 calls
| JK: (A|mn)                        :      0.683u      0.000s      0.418w      1 calls
| JK: (A|Q)^-1/2                    :      0.083u      0.000s      0.053w      1 calls
| JK: (Q|mn)                        :      0.100u      0.017s      0.062w      1 calls
| HF: Form H                        :      0.017u      0.000s      0.006w      1 calls
| HF: Form S/X                      :      0.000u      0.000s      0.002w      1 calls
| HF: Guess                         :      0.133u      0.000s      0.089w      1 calls
| | SAD Guess                       :      0.133u      0.000s      0.087w      1 calls
| HF: Form G                        :      0.517u      0.000s      0.309w     11 calls
| | JK: D                           :      0.000u      0.000s      0.000w     11 calls
| | JK: USO2AO                      :      0.000u      0.000s      0.000w     11 calls
| | JK: JK                          :      0.517u      0.000s      0.308w     11 calls
| | | JK: J                         :      0.033u      0.000s      0.027w     11 calls
| | | | JK: J1                      :      0.017u      0.000s      0.014w     11 calls
| | | | JK: J2                      :      0.017u      0.000s      0.013w     11 calls
| | | JK: K                         :      0.483u      0.000s      0.277w     11 calls
| | | | JK: K1                      :      0.400u      0.000s      0.231w     11 calls
| | | | JK: K2                      :      0.083u      0.000s      0.045w     11 calls
| | JK: AO2USO                      :      0.000u      0.000s      0.000w     11 calls
| HF: Form F                        :      0.000u      0.000s      0.000w     11 calls
| HF: DIIS                          :      0.017u      0.000s      0.012w     11 calls
| | DIISManager::add_entry          :      0.000u      0.000s      0.003w     10 calls
| | DIISManager::extrapolate        :      0.017u      0.000s      0.003w      9 calls
| | | bMatrix setup                 :      0.000u      0.000s      0.001w      9 calls
| | | bMatrix pseudoinverse         :      0.000u      0.000s      0.001w      9 calls
| | | New vector                    :      0.017u      0.000s      0.001w      9 calls
| HF: Form C                        :      0.033u      0.000s      0.022w     11 calls
| HF: Form D                        :      0.000u      0.000s      0.000w     11 calls
SAPT(DFT): Monomer A SCF            :      2.983u      0.050s      1.849w      1 calls
| JK: (A|mn)                        :      0.733u      0.000s      0.440w      1 calls
| JK: (A|Q)^-1/2                    :      0.100u      0.000s      0.060w      1 calls
| JK: (Q|mn)                        :      0.117u      0.000s      0.067w      1 calls
| HF: Form H                        :      0.000u      0.000s      0.007w      1 calls
| HF: Form S/X                      :      0.000u      0.000s      0.002w      1 calls
| HF: Guess                         :      0.300u      0.017s      0.176w      1 calls
| | SAD Guess                       :      0.300u      0.017s      0.173w      1 calls
| HF: Form G                        :      0.383u      0.000s      0.269w     10 calls
| | JK: D                           :      0.000u      0.000s      0.000w     10 calls
| | JK: USO2AO                      :      0.017u      0.000s      0.000w     10 calls
| | JK: JK                          :      0.350u      0.000s      0.268w     10 calls
| | | JK: J                         :      0.000u      0.000s      0.026w     10 calls
| | | | JK: J1                      :      0.000u      0.000s      0.013w     10 calls
| | | | JK: J2                      :      0.000u      0.000s      0.012w     10 calls
| | | JK: K                         :      0.350u      0.000s      0.240w     10 calls
| | | | JK: K1                      :      0.333u      0.000s      0.220w     10 calls
| | | | JK: K2                      :      0.017u      0.000s      0.020w     10 calls
| | JK: AO2USO                      :      0.000u      0.000s      0.000w     10 calls
| HF: Form F                        :      0.000u      0.000s      0.000w     10 calls
| HF: DIIS                          :      0.033u      0.000s      0.012w     10 calls
| | DIISManager::add_entry          :      0.000u      0.000s      0.003w      9 calls
| | DIISManager::extrapolate        :      0.017u      0.000s      0.003w      8 calls
| | | bMatrix setup                 :      0.000u      0.000s      0.001w      8 calls
| | | bMatrix pseudoinverse         :      0.017u      0.000s      0.001w      8 calls
| | | New vector                    :      0.000u      0.000s      0.001w      8 calls
| HF: Form C                        :      0.067u      0.000s      0.022w     10 calls
| HF: Form D                        :      0.000u      0.000s      0.000w     10 calls
SAPT(DFT): Monomer B SCF            :      2.883u      0.050s      1.795w      1 calls
| JK: (A|mn)                        :      0.733u      0.000s      0.440w      1 calls
| JK: (A|Q)^-1/2                    :      0.083u      0.000s      0.055w      1 calls
| JK: (Q|mn)                        :      0.100u      0.000s      0.063w      1 calls
| HF: Form H                        :      0.000u      0.000s      0.005w      1 calls
| HF: Form S/X                      :      0.000u      0.000s      0.002w      1 calls
| HF: Guess                         :      0.283u      0.000s      0.174w      1 calls
| | SAD Guess                       :      0.283u      0.000s      0.172w      1 calls
| HF: Form G                        :      0.433u      0.000s      0.256w     10 calls
| | JK: D                           :      0.000u      0.000s      0.000w     10 calls
| | JK: USO2AO                      :      0.000u      0.000s      0.000w     10 calls
| | JK: JK                          :      0.433u      0.000s      0.255w     10 calls
| | | JK: J                         :      0.033u      0.000s      0.023w     10 calls
| | | | JK: J1                      :      0.017u      0.000s      0.012w     10 calls
| | | | JK: J2                      :      0.017u      0.000s      0.011w     10 calls
| | | JK: K                         :      0.383u      0.000s      0.230w     10 calls
| | | | JK: K1                      :      0.350u      0.000s      0.209w     10 calls
| | | | JK: K2                      :      0.033u      0.000s      0.020w     10 calls
| | JK: AO2USO                      :      0.000u      0.000s      0.000w     10 calls
| HF: Form F                        :      0.000u      0.000s      0.000w     10 calls
| HF: DIIS                          :      0.000u      0.000s      0.011w     10 calls
| | DIISManager::add_entry          :      0.000u      0.000s      0.003w      9 calls
| | DIISManager::extrapolate        :      0.000u      0.000s      0.003w      8 calls
| | | bMatrix setup                 :      0.000u      0.000s      0.001w      8 calls
| | | bMatrix pseudoinverse         :      0.000u      0.000s      0.001w      8 calls
| | | New vector                    :      0.000u      0.000s      0.001w      8 calls
| HF: Form C                        :      0.050u      0.000s      0.020w     10 calls
| HF: Form D                        :      0.000u      0.000s      0.000w     10 calls
JK: D                               :      0.000u      0.000s      0.000w      1 calls
JK: USO2AO                          :      0.000u      0.000s      0.000w      1 calls
JK: JK                              :      0.250u      0.000s      0.148w      1 calls
| JK: J                             :      0.017u      0.000s      0.008w      1 calls
| | JK: J1                          :      0.000u      0.000s      0.004w      3 calls
| | JK: J2                          :      0.017u      0.000s      0.004w      3 calls
| JK: K                             :      0.233u      0.000s      0.140w      1 calls
| | JK: K1                          :      0.217u      0.000s      0.134w      6 calls
| | JK: K2                          :      0.017u      0.000s      0.006w      3 calls
JK: AO2USO                          :      0.000u      0.000s      0.000w      1 calls
SAPT(DFT):SAPT:elst                 :      0.000u      0.000s      0.000w      1 calls
SAPT(DFT):SAPT:exch                 :      0.233u      0.000s      0.148w      1 calls
| JK: D                             :      0.000u      0.000s      0.000w      1 calls
| JK: USO2AO                        :      0.000u      0.000s      0.000w      1 calls
| JK: JK                            :      0.233u      0.000s      0.145w      1 calls
| | JK: J                           :      0.000u      0.000s      0.008w      1 calls
| | | JK: J1                        :      0.000u      0.000s      0.004w      3 calls
| | | JK: J2                        :      0.000u      0.000s      0.004w      3 calls
| | JK: K                           :      0.233u      0.000s      0.137w      1 calls
| | | JK: K1                        :      0.217u      0.000s      0.131w      6 calls
| | | JK: K2                        :      0.017u      0.000s      0.006w      3 calls
| JK: AO2USO                        :      0.000u      0.000s      0.000w      1 calls
SAPT(DFT):SAPT:ind                  :      1.867u      0.000s      1.117w      1 calls
| JK: D                             :      0.000u      0.000s      0.001w     21 calls
| JK: USO2AO                        :      0.000u      0.000s      0.000w     21 calls
| JK: JK                            :      1.800u      0.000s      1.094w     21 calls
| | JK: J                           :      0.067u      0.000s      0.056w     21 calls
| | | JK: J1                        :      0.017u      0.000s      0.028w     23 calls
| | | JK: J2                        :      0.050u      0.000s      0.027w     23 calls
| | JK: K                           :      1.717u      0.000s      1.032w     21 calls
| | | JK: K1                        :      1.650u      0.000s      0.989w     46 calls
| | | JK: K2                        :      0.067u      0.000s      0.043w     23 calls
| JK: AO2USO                        :      0.000u      0.000s      0.000w     21 calls
SAPT(DFT): Monomer A DFT            :     29.233u      0.367s     17.795w      1 calls
| V: Grid                           :      0.367u      0.000s      0.222w      1 calls
| JK: (A|mn)                        :      0.733u      0.000s      0.444w      1 calls
| JK: (A|Q)^-1/2                    :      0.100u      0.000s      0.062w      1 calls
| JK: (Q|mn)                        :      0.117u      0.000s      0.072w      1 calls
| HF: Form H                        :      0.000u      0.000s      0.006w      1 calls
| HF: Form S/X                      :      0.000u      0.000s      0.002w      1 calls
| HF: Guess                         :      0.300u      0.000s      0.185w      1 calls
| | SAD Guess                       :      0.300u      0.000s      0.183w      1 calls
| HF: Form G                        :     26.317u      0.317s     15.958w     12 calls
| | RV: Form V                      :     25.850u      0.317s     15.681w     12 calls
| | | Properties                    :     15.083u      0.150s      9.231w  16752 calls
| | | Functional                    :      5.117u      0.050s      3.014w  16752 calls
| | | V_xc                          :      5.383u      0.100s      3.289w  16752 calls
| | JK: D                           :      0.000u      0.000s      0.000w     12 calls
| | JK: USO2AO                      :      0.000u      0.000s      0.000w     12 calls
| | JK: JK                          :      0.467u      0.000s      0.275w     12 calls
| | | JK: J                         :      0.050u      0.000s      0.029w     12 calls
| | | | JK: J1                      :      0.017u      0.000s      0.015w     12 calls
| | | | JK: J2                      :      0.033u      0.000s      0.014w     12 calls
| | | JK: K                         :      0.417u      0.000s      0.244w     12 calls
| | | | JK: K1                      :      0.383u      0.000s      0.220w     12 calls
| | | | JK: K2                      :      0.033u      0.000s      0.023w     12 calls
| | JK: AO2USO                      :      0.000u      0.000s      0.000w     12 calls
| HF: Form F                        :      0.000u      0.000s      0.000w     12 calls
| HF: DIIS                          :      0.000u      0.000s      0.015w     12 calls
| | DIISManager::add_entry          :      0.000u      0.000s      0.004w     11 calls
| | DIISManager::extrapolate        :      0.000u      0.000s      0.005w     10 calls
| | | bMatrix setup                 :      0.000u      0.000s      0.002w     10 calls
| | | bMatrix pseudoinverse         :      0.000u      0.000s      0.001w     10 calls
| | | New vector                    :      0.000u      0.000s      0.002w     10 calls
| HF: Form C                        :      0.033u      0.000s      0.024w     12 calls
| HF: Form D                        :      0.000u      0.000s      0.000w     12 calls
SAPT(DFT): Monomer B DFT            :     28.650u      0.350s     17.421w      1 calls
| V: Grid                           :      0.350u      0.000s      0.224w      1 calls
| JK: (A|mn)                        :      0.700u      0.000s      0.430w      1 calls
| JK: (A|Q)^-1/2                    :      0.100u      0.000s      0.054w      1 calls
| JK: (Q|mn)                        :      0.100u      0.000s      0.065w      1 calls
| HF: Form H                        :      0.000u      0.000s      0.006w      1 calls
| HF: Form S/X                      :      0.017u      0.000s      0.003w      1 calls
| HF: Guess                         :      0.283u      0.000s      0.175w      1 calls
| | SAD Guess                       :      0.283u      0.000s      0.173w      1 calls
| HF: Form G                        :     25.750u      0.267s     15.625w     12 calls
| | RV: Form V                      :     25.300u      0.267s     15.342w     12 calls
| | | Properties                    :     15.583u      0.217s      8.952w  16752 calls
| | | Functional                    :      4.600u      0.017s      2.995w  16752 calls
| | | V_xc                          :      4.750u      0.033s      3.248w  16752 calls
| | JK: D                           :      0.000u      0.000s      0.000w     12 calls
| | JK: USO2AO                      :      0.000u      0.000s      0.000w     12 calls
| | JK: JK                          :      0.450u      0.000s      0.281w     12 calls
| | | JK: J                         :      0.067u      0.000s      0.031w     12 calls
| | | | JK: J1                      :      0.050u      0.000s      0.015w     12 calls
| | | | JK: J2                      :      0.017u      0.000s      0.015w     12 calls
| | | JK: K                         :      0.383u      0.000s      0.247w     12 calls
| | | | JK: K1                      :      0.383u      0.000s      0.223w     12 calls
| | | | JK: K2                      :      0.000u      0.000s      0.024w     12 calls
| | JK: AO2USO                      :      0.000u      0.000s      0.000w     12 calls
| HF: Form F                        :      0.000u      0.000s      0.000w     12 calls
| HF: DIIS                          :      0.033u      0.000s      0.014w     12 calls
| | DIISManager::add_entry          :      0.000u      0.000s      0.004w     11 calls
| | DIISManager::extrapolate        :      0.017u      0.000s      0.004w     10 calls
| | | bMatrix setup                 :      0.000u      0.000s      0.002w     10 calls
| | | bMatrix pseudoinverse         :      0.017u      0.000s      0.001w     10 calls
| | | New vector                    :      0.000u      0.000s      0.001w     10 calls
| HF: Form C                        :      0.033u      0.000s      0.023w     12 calls
| HF: Form D                        :      0.000u      0.000s      0.000w     12 calls
SAPT(DFT):SAPT(DFT):JK              :      0.250u      0.000s      0.149w      1 calls
| JK: D                             :      0.000u      0.000s      0.000w      1 calls
| JK: USO2AO                        :      0.000u      0.000s      0.000w      1 calls
| JK: JK                            :      0.217u      0.000s      0.124w      1 calls
| | JK: J                           :      0.017u      0.000s      0.008w      1 calls
| | | JK: J1                        :      0.000u      0.000s      0.004w      3 calls
| | | JK: J2                        :      0.017u      0.000s      0.004w      3 calls
| | JK: K                           :      0.200u      0.000s      0.116w      1 calls
| | | JK: K1                        :      0.200u      0.000s      0.110w      6 calls
| | | JK: K2                        :      0.000u      0.000s      0.006w      3 calls
| JK: AO2USO                        :      0.000u      0.000s      0.000w      1 calls
SAPT(DFT):SAPT(DFT):elst            :      0.000u      0.000s      0.000w      1 calls
SAPT(DFT):SAPT(DFT):exch            :      0.200u      0.000s      0.126w      1 calls
| JK: D                             :      0.000u      0.000s      0.000w      1 calls
| JK: USO2AO                        :      0.000u      0.000s      0.000w      1 calls
| JK: JK                            :      0.200u      0.000s      0.123w      1 calls
| | JK: J                           :      0.017u      0.000s      0.007w      1 calls
| | | JK: J1                        :      0.000u      0.000s      0.003w      3 calls
| | | JK: J2                        :      0.017u      0.000s      0.003w      3 calls
| | JK: K                           :      0.183u      0.000s      0.116w      1 calls
| | | JK: K1                        :      0.183u      0.000s      0.110w      6 calls
| | | JK: K2                        :      0.000u      0.000s      0.005w      3 calls
| JK: AO2USO                        :      0.000u      0.000s      0.000w      1 calls
SAPT(DFT):SAPT(DFT):ind             :     45.583u      0.533s     27.664w      1 calls
| JK: D                             :      0.000u      0.000s      0.001w     17 calls
| JK: USO2AO                        :      0.000u      0.000s      0.000w     17 calls
| JK: JK                            :      1.383u      0.000s      0.815w     17 calls
| | JK: J                           :      0.150u      0.000s      0.049w     17 calls
| | | JK: J1                        :      0.017u      0.000s      0.024w     19 calls
| | | JK: J2                        :      0.133u      0.000s      0.023w     19 calls
| | JK: K                           :      1.217u      0.000s      0.760w     17 calls
| | | JK: K1                        :      1.133u      0.000s      0.723w     38 calls
| | | JK: K2                        :      0.083u      0.000s      0.036w     19 calls
| JK: AO2USO                        :      0.000u      0.000s      0.000w     17 calls
| RV: Form Vx                       :     44.150u      0.533s     26.828w     16 calls
| | Properties                      :     20.333u      0.350s     12.087w  22336 calls
| | Functional                      :      7.050u      0.050s      4.517w  22336 calls
| | Derivative Properties           :      9.050u      0.050s      5.407w  22336 calls
| | V_XCd                           :      6.933u      0.067s      4.389w  22336 calls
SAPT(DFT):SAPT(DFT):disp            :      5.000u      0.167s      3.141w      1 calls
| DFH: initialize()                 :      0.583u      0.000s      0.350w      1 calls
| | DFH: sparsity prep              :      0.033u      0.000s      0.024w      1 calls
| | DFH: AO Construction            :      0.533u      0.000s      0.313w      1 calls
| DFH: transform()                  :      0.117u      0.017s      0.075w      1 calls
| | DFH: Total Workflow             :      0.017u      0.000s      0.014w      4 calls
| | | DFH: Total Transform          :      0.017u      0.000s      0.014w      4 calls
| | | | DFH: 1st Contraction        :      0.000u      0.000s      0.009w      2 calls
| | | | DFH: 2nd Contraction        :      0.017u      0.000s      0.005w      2 calls
| | DFH: MO to disk                 :      0.000u      0.000s      0.001w      2 calls
| | DFH: Direct Contractions        :      0.083u      0.017s      0.046w      1 calls
| | | DFH: Total Workflow           :      0.017u      0.000s      0.007w      2 calls
| DF Integrals                      :      0.767u      0.083s      0.514w      1 calls
| W Integrals                       :      0.000u      0.000s      0.001w      1 calls
| Exch-Disp20 N^5                   :      0.033u      0.033s      0.043w      1 calls
| Exch-Disp20 N^4                   :      0.267u      0.033s      0.178w      1 calls

***********************************************************
```

**Comment by yxie326** [comment]
@loriab Here are the tags for SAPT0 and SAPT(DFT). I have modified (in this PR) the tags of SAPT(DFT) so that they match the style of FISAPT. I have not modified any of the tags in SAPT0 and many-body SAPT; those are having similar styles (i.e. doesn't have module name in the beginning).

`SAPT0:

DF Integrals
W Integrals
Elst10
Exch10
Exch10 S^2
Ind20
Exch-Ind20
Exch-Disp20 N^5
Exch-Disp20 N^4
OO DF Integrals
Elst10
Exch10
Exch10 S^2


SAPT(DFT):

SAPT(DFT): Dimer SCF
SAPT(DFT): Monomer A SCF
SAPT(DFT): Monomer B SCF
SAPT(DFT):SAPT:elst
SAPT(DFT):SAPT:exch
SAPT(DFT):SAPT:ind
SAPT(DFT): Monomer A DFT
SAPT(DFT): Monomer B DFT
SAPT(DFT):SAPT(DFT):JK
SAPT(DFT):SAPT(DFT):elst
SAPT(DFT):SAPT(DFT):exch
SAPT(DFT):SAPT(DFT):ind
SAPT(DFT):SAPT(DFT):disp`

**Comment by loriab** [comment]
Thanks, @yxie326. Main differences are (1) no `SAPT:` in front and (2) plain SAPT code has more per-term labels. So long as FISAPT and DFTSAPT are aligned (as Yie has done), the current mismatch doesn't bother me. And not too many methods have a `Ind20` terms, so fairly obvious.

I'll add my approval. Any adding of `SAPT:` can be a separate PR.

**Pull request merged**
