### PR TITLE
build, docs, py3 improvements

### PR DESCRIPTION
**Pull request by loriab**
## Description
Provide a brief description of the PR's purpose here.

## Todos
Notable points that this PR has either accomplished or will accomplish.
- [x] renamed gtfock and erd. enable erd allowed w/o being default
- [x] add astropy docs dependence. all psi4.core and psi4.driver autodoc-ed w/o helper scripts
- [x] do absolute, not relative, imports in psi4.driver
- [x] replace cdict with variables and arrays in core.Wfn
- [x] reimplement versioning, at least internally. publish `v1.0` tag on top of `1.0`
- [x] 	Switched sto-3g and 3-21G DF fitting basis sets to def2-SVP
- [x]	Reword castup basis logic
- [x] **python 3 compatible**, now with testing!
- [x] numpy interface updates
- [x] effectively re-enable threaded MKL (build issue)
- [x] reenable mostly static linked build
- [x] externals installed to `external/` not `external/{pkgname}`

## Status
- [x]  Ready to go

### CODE REVIEW

**Comment by andysim** [comment]
Yay for us not being Luddites!  I see you used `from __future__ ...` throughout, so it should be Python 2 compatible, but has it been tested with an old version?  I like the numpy version info; that will be really helpful for debugging.

**Comment by dgasmith** [comment]
@andysim We compile and test with Python2 exclusively at the moment. Couldnt figure out Travis, debating if we want to switch the Distelli build to Python3.

**Comment by andysim** [comment]
Ah, ok.  I knew we had issues mixing and matching, but I thought [this](https://github.com/psi4/psi4/pull/486/files#diff-354f30a63fb0907d4ad57269548329e3R121) meant we were using Python 3 for all Travis runs.  Good to know that both are working.

**Comment by andysim** [comment]
Looks like the failure is a Distelli issue, so LGTM.

**Comment by dgasmith** [comment]
It's a pure Distelli issue, all tests pass on Mac. LGTM.

**Comment by jturney** [comment]
LGTM

**Pull request merged**
