### PR TITLE
Wavefunction passing update

### PR DESCRIPTION
**Pull request by dgasmith**
This is the list of changes made for the wavefunction passing update. This is a very large change that modified virtually every file in Psi4, details of the why and what can be found [here](https://github.com/psi4/psi4public/wiki/Changes-to-Information-Passing-in-Psi4-(Jan-2016)). This is slightly long, but please read this fully as there is a decent chance that advanced users will have to make some tweaks to their existing input files.

A quick rundown of the changes:
* Energy, gradient, etc now actually return a energy (a number), gradient (a matrix), etc. A good example of these changes is [this](https://github.com/psi4/psi4public/commit/a559003d1e4be8ac36107ba64751ee6db78c8f3b#diff-684250b9cfb2a0fa201f5dc123c90964L48) diff.
* All methods now take new kwargs (python variables):
    * `return_wfn` - return the methods wavefunction: `scf_e, scf_wfn = energy('SCF', return_wfn=True)`
    * `ref_wfn` - what wavefunction to use as reference: `mp2_e = energy('MP2', ref_wfn=scf_wfn)`
    * `molecule` - give a molecule for the calculation to be run on (mostly an internal kwarg)

* The global molecule is now only touched/modifed by the input file, the user parameter `activate` and by the optimize function.
* OEProp, cubewriter, and the molden writer all need to be explicitly passed a wavefunction python-side.
* These changes will allow for extremely complex workflows. Check out [`proc.py/run_sapt`](https://github.com/dgasmith/psi4public/blob/wavefunction_pass/share/python/proc.py#L2611) for an interesting case of passing wavefunctions and molecules into primary `proc.py` functions.
* `DF` and `RI` modifiers to methods are no longer valid (e.g., `energy('RI-MP2')`). Please use the `mp2_type` option instead.
* Fixed numerous bugs/oddities and moved everything towards a more object oriented workflow.

----------

A few notable issues that people may run into:

* The `psi4/lib` folder has been moved to `psi4/share` please update all `PSIDATADIR` references accordingly.
* `Process::environment.wavefunction` no longer exists. This will break any input side `psi4.wavefunction` and `psi4.set_wavefunciton` calls. Please use the `return_wfn` and `ref_wfn` kwargs on methods instead.
* A consequence of this is we broke all of the plugins! Don't worry the fix is very simple please change your C++ signature from: 
 `PsiReturnType skeleton(Options& options)`
to:
 `SharedWavefunction skeleton(SharedWavefunction ref_wfn, Options& options)`
 Every method in Psi4 now takes a Wavefunction and Options objects, this is to make plugins consistent as well. The python-side signature is now `psi4.plugin('skeleton.so', ref_wfn)`.  Options passing has not yet been handled, but thats next up on the list.

----------
Below is a list of outstanding issues. Please note that these will likely not all be cleaned up here. Outstanding issues will be moved to a ticket:

* [ ] Methods also take the `molecule` kwarg, it is not clear if `ref_wfn` or `molecule` should supersede the other yet.
* [ ] Not all methods return wavefunctions yet. For example what does a SAPT wavefunction look like?
    * [ ] psimrcc Wavefunction
    * [ ] SAPT Wavefunction
    * [ ] EFP Wavefunction
* [ ] If I pass SCF a `ref_wfn` with orbitals, the `ref_wfn` orbitals are not used.
* [ ] We would like a SCF level wavefunction to be able to cast itself back C1 symmetry so that we can run symmetry-based SCF and then use this wavefunction in symmetry intolerant code. These transforms are reimplemented in every symmetry tolerant code.
* [ ] Saving of binary `optking` information may break for very complex optimizations (database, cbs wrapper, etc). Optimization proceeds, but always restarts at the first iteration so convergence is slow.
* [ ] Plugin examples are starting to show their age. We probably need to overhaul these.
* [ ] The documentation needs to reflect the above changes.
* [ ] DF and RI calls should soft fail with a proper error message.

### CODE REVIEW

**Comment by dgasmith** [comment]
By attempting to observe the PCM issue we have fundamentally changed its state to passing.

More likely scenario: Tag versions were off.

**Comment by andysim** [comment]
A Heisenbug!

**Comment by andysim** [comment]
I keep seeing "continuous-integration/travis-ci — Waiting for status to be reported", and it doesn't appear to have run your merge of Lori's commits.  Is anybody else seeing the same?

**Comment by loriab** [comment]
I see the same thing. I've been confused about what status you and Daniel were seeing.

**Comment by andysim** [comment]
The last commit doesn't even show up in Travis.  I just clicked on the last commit that showed up in Travis to restart it, but it doesn't seem to have triggered a build of the latest version.

**Comment by dgasmith** [comment]
It ran and passed here: https://travis-ci.org/psi4/psi4/builds/109076512

I restarted it to see if that fixes things.

**Comment by andysim** [comment]
That's the merge of @loriab's new printing / running machinery into the existing master, which we expect to pass.  What we need to see is 9c5d3c3 of this PR.  It's not running because of merge conflicts (I only just noticed that error message), so you'll need to pull the master branch in and add the conflict resolution to the PR.

**Comment by dgasmith** [comment]
@andysim Thats the CI instance that started when I pulled in @loriab's changes. 

Something is up, see my branch with the changes here: https://github.com/dgasmith/psi4public/tree/wavefunction_pass

**Comment by loriab** [comment]
The final `9c5` commit from your branch shows up here, but the two intermediate ones `507` and `62f` that are on your branch don't seem to have made it here to the PR.

**Comment by dgasmith** [comment]
@loriab Yupn thats really odd. I replayed the commits manually and I think everything is coming through correctly now.

**Comment by loriab** [comment]
Well, we have output, but it's laughably unhelpful.

**Comment by jgonthier** [comment]
Not helping the current discussion, but if ``DF`` and ``RI`` modifiers are no longer valid, the manual needs to be modified accordingly. Is it already done ? I had a look but could not find it.

Also, if someone could write somewhere (for example in the Psi4 forum) how the TravisCI  works, i.e. how do we know what fails and which details do we have access to, that would be helpful.

**Comment by andysim** [comment]
The output looks suspiciously like a segfault.  I'm trying to reproduce it now.  If you click the "details" like in the Travis status box near the bottom of this page, you'll see full details of exactly what is working / failing, @jgonthier.

**Comment by loriab** [comment]
Oh yeah, the summer work weeks caught various things in the manual that were outright broken, but there's plenty more that's not quite best practices (recommending `~/.psi4rc` for controlling scratch). And now there's items that are definitely wrong. One first step, https://github.com/psi4/psi4/issues/249

**Comment by andysim** [comment]
Just did a clean build from @dgasmith's version, and this is what I see.  I bet that's what's happening on Travis.  Any clues, @loriab?

`Traceback (most recent call last):
  File "/Users/andysim/programming/psi4/share/python/inputparser.py", line 699, in process_input
    temp = re.sub(pcm, process_pcm_command, temp)
  File "/usr/local/Frameworks/Python.framework/Versions/2.7/lib/python2.7/re.py", line 155, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "/Users/andysim/programming/psi4/share/python/inputparser.py", line 366, in process_pcm_command
    import pcm_placeholder
ImportError: No module named pcm_placeholder`

**Comment by loriab** [comment]
Well, https://github.com/dgasmith/psi4public/blob/wavefunction_pass/cmake/ConfigPCMSolver.cmake#L78 needs `lib` --> `share` for one thing. Can you do that, then tell me what your next error is? Both @dgasmith and I have been using pcmsolver from metapackage and so may have evaded a few issues.

**Comment by andysim** [comment]
I forgot to specify a fortran compiler, so it didn't actually build PCMSolver.  My bad.  That's still a bug though; we should run just fine without PCM so we should probe that a little.  I'm currently torturing my laptop with a clean build that actually does include PCM; I'll let you know what I find.  The "good" news is that it's completely reproducible on a vanilla OSX setup.

**Comment by loriab** [comment]
Actually, it's alarming that the pcm cases were in the test suite. If no fortran, then enable_pcmsolver should have been off and the tests/pcmsolver subdir never added.

**Comment by andysim** [comment]
Your suggestion fixed the problem on my machine, @loriab.  Great detective work.  I just pushed the update, so we'll see if that fixes it.  The non-PCM thing needs to be figured out some time, but I think it can wait until the rest of the merge issues are resolved.

**Comment by loriab** [comment]
Yay. If that was the only lib --> share I missed, I'll be pleased.

**Comment by andysim** [comment]
Looks great so far!  I retract my statement about the code being bad in the absence of PCMSolver; I wasn't actually running the tests themselves.  I just grabbed a PCM input from the test suite and it's no surprise that it failed when I didn't compile PCM.

**Comment by loriab** [comment]
Looks like this one will pass. Whatever you all decide on the timing of the merge is fine with me. But I would advocate for sooner rather than later, as presently there's no good base for developing any but minor bug fixes.

**Comment by dgasmith** [comment]
I agree the sooner the better. What about Tuesday unless someone finds a serious bug or needs extra time to review/comment?

-Daniel Smith

**Comment by loriab** [comment]
Tuesday (or sooner) works for me, considering the PRs are piling up.

**Comment by jturney** [comment]
Tuesday (or sooner) works for me, too.

**Pull request merged**
