### PR TITLE
B3lyp35

### PR DESCRIPTION
**Pull request by loriab**
## Description
Get feedback on functional.py oddities and justifiy b3lyp5 fix

## Todos
- [x] if agreed upon, this will get us B3LYP5 back
- [background](http://forum.psicode.org/t/b3lyp-defect-compatibility-with-gamess-and-gaussian/193)
- [deeper background](http://verahill.blogspot.com/2013/06/446-b3lyp-and-wah-confusion.html)

## Questions
- [x] major ?: if you vary the vwn in plain b3lyp superfunctional [here](https://github.com/loriab/psi4/blob/b3lyp35/share/python/functional.py#L1243), it matches other programs' B3LYP3 when `VWN3RPA_C` or `VWN5RPA_C` is used but matches other programs' B3LYP5 when `VWN3_C` or `VWN5_C` is used. Naming-wise, this makes no sense. Anyone have a better justification? This PR keeps default B3LYP at `VWN3RPA_C` and [switches](https://github.com/psi4/psi4/pull/339/commits/cfcbf085305c8033186fb3c68c1b96f19688a939#diff-9e8e3243e87430585c59e5a407f6bf69R1314) B3LYP5 to `VWN5_C` and re-enables it. So the input file below works, yet that redefinition is disturbing.
- [x] minor ?: why is `wB88_X` being redefined [here](https://github.com/psi4/psi4/pull/339/commits/cfcbf085305c8033186fb3c68c1b96f19688a939#diff-9e8e3243e87430585c59e5a407f6bf69R654) when it was just defined up above [here](https://github.com/psi4/psi4/pull/339/commits/cfcbf085305c8033186fb3c68c1b96f19688a939#diff-9e8e3243e87430585c59e5a407f6bf69R603). Ok to delete 2nd definition as done in this PR?
- [x] minor ?: why is `bp86d1` building upon b3lyp as [here](https://github.com/psi4/psi4/pull/339/commits/cfcbf085305c8033186fb3c68c1b96f19688a939#diff-9e8e3243e87430585c59e5a407f6bf69R2114)? Ok to make it build upon bp86 as done in this PR?

## Status
- [x]  Ready to go

B3LYP3/5 test input. You'll need [this](https://raw.githubusercontent.com/drhaney/psi4/master/share/basis/6-31g_2df_p_.gbs) basis set
```
# all non-psi4 references from http://forum.psicode.org/t/b3lyp-defect-compatibility-with-gamess-and-gaussian/193

# @jamont conditions

molecule {
0 1
O
H 1 rOH
H 1 rOH 2 aHOH

rOH = 0.9622
aHOH = 103.84
}

set basis 6-311g(d)
set scf_type pk
set e_convergence 9

e = energy('b3lyp')
compare_values(-76.4338100903, e, 7, 'b3lyp3 vs Gaussian')
compare_values(-76.4338100577, e, 7, 'b3lyp3 vs Gamess')

clean()

# @drhaney conditions

set basis 6-31G(2df,p)
#set dft_spherical_points 590
#set dft_radial_points 99

e = energy('b3lyp')
compare_values(-76.4293315991, e, 5, 'b3lyp3 vs Gamess')
# GAMESS-VWNrpa_1  -76.4293 3159 91
# Psi4-VWNrpa_3    -76.4293 5426 98
# Gaussian-09      -76.4256 2566 74
# LAB psi4         -76.4293 4111 93  # large grid  VWN3RPA_C  VWN5RPA_C

e = energy('b3lyp5')
compare_values(-76.39221287, e, 5, 'b3lyp5 vs NWChem')
# GAMESS-VWN_5     -76.3922 0295 70
# Nchem-VWN_3      -76.3922 1287 
# Psi4-VWN_3       -76.3922 2551 29
# LAB psi4         -76.3922 1237 09  # large grid  VWN3_C     VWN5_C

clean()

# @hokru conditions

molecule {
O -1.769142 -0.076181 0.000000
H -2.065745 0.837492 0.000000
H -0.809034 0.001317 0.000000
}

### e = energy('b3lyp')
### compare_values(-76.46290368244, e, 5, 'b3lyp3 vs Turbomole')
### #For VWN3 (same as Gaussian) I get
### #-76.46290368244 (Turbomole "B3LYP_Gaussian")
### #-76.46290355576 (psi4 energy('b3lyp'))
### #-76.46290344335 (nwchem default vnw-1-rpa)
### #VNW-1-rpa in nwchem seems to be VWN3 in Turbomole/Gaussian
### 
### e = energy('b3lyp5')
### compare_values(-76.42582290565, e, 5, 'b3lyp5 vs Turbomole')
### #and VWN5
### #-76.42582290565 (Turbomole default )
### #-76.42582303608 (psi4 energy('b3lyp5') with VWN5_C not VWN5RPA_C , needs to be changed!)
### #-76.42582292329 (nwchem VWN_5)
```

### CODE REVIEW

**Comment by dgasmith** [comment]
@loriab Looks like you scooped up changes from your other commit here as well. Can you pull this out?

**Comment by loriab** [comment]
Yes, I know– it's because I branched this PR branch off the other PR branch. But the other one is ready for merge and this one is tentative. So when the other merges, the extra commits here should heal up or I can rebase them away. The extra commits make this one a bit confusing, but I tried to include enough links in the description.

**Comment by dgasmith** [comment]
@loriab Ah, ok that flattened it out.

**Comment by loriab** [comment]
@robparrish, any warnings or guidance on the major question above?

**Comment by robparrish** [comment]
Was just discussing this with Lori. The underlying primitive functional
were implemented according to the excellent notes at the density functional
repository:

http://www.cse.scitech.ac.uk/ccg/dft/xc-b3lyp.pdf (contains the definition
for vwn3rpa)
http://www.cse.scitech.ac.uk/ccg/dft/c-vwn5.pdf
http://www.cse.scitech.ac.uk/ccg/dft/c-vwn5rpa.pdf

We also refer to the VWN paper (
http://www.nrcresearchpress.com/doi/pdf/10.1139/p80-159). In VWN, any
functional with "RPA" means that the parameters of their Pade interpolation
formula across r_s are fit to RPA computations, any functional without
means that the same parameters are fit to the QMC data of Ceperley and
Alder. For RPA/non-RPA, VWN perform one Pade fit across r_s for
ferromagnetic limit (EcP), one for the paramagnetic limit (EcF). The RPA
fit is given in the middle of page 1207 in the left column (parameter c =
EcP4 = 42.7198), while the QMC fit is given in Table I on page 1207
(parameter c = EcP4 = 12.9352).

The remaining question of the paper is the issue of interpolation across
spin polarization z. This is where VWN 1-5 are defined - they have
different spin-interpolation formulae, and all give the same results for
closed-shell systems.

That B3LYP and B3LYP5 differ for closed-shell systems means that the
notation has been bastardized. Clearly B3LYP uses the RPA parameters while
B3LYP5 uses the QMC parameters. But then the question of which VWN is to be
used is less clear. The one currently used in PSI4 comes from the density
functional repository above, which is actually VWN1 with the RPA
parameters.

Lori has generously agreed to provide some reference data from other codes
for open-shell systems so we can double-check the choice of VWN for
spin-polarized cases. We'll get this fully cleared up as soon as those
numbers come in.

Best,







-Rob

**Comment by loriab** [comment]
NW-Chem
```
closed-shell   vwn_3                    Total DFT energy =      -76.407526614389
closde-shell   vwn_1_rpa (def.)         Total DFT energy =      -76.444577160243
open-shell     vwn_3                    Total DFT energy =      -75.940741067166
open-shell     vwn_1_rpa (def.)         Total DFT energy =      -75.974154693676
```
Psi4
```
closed-shell  VWN3RPA_C       -76.4445772372     # matches NW closed VWN_1_RPA
closed-shell  VWN5RPA_C       -76.4445772372     # ""
closed-shell  VWN3_C          -76.4075266923     # matches NW closed VWN3
closed-shell  VWN5_C          -76.4075266923     # ""

open-shell  VWN3RPA_C         -75.9741548527     # matches NW open VWN_1_RPA
open-shell  VWN5RPA_C         -75.9744079442
open-shell  VWN3_C            -75.9404785496
open-shell  VWN5_C            -75.9407528036     # ~matches NW open VWN_3
```
Conditions
```
aug-cc-pvdz

#0 1  # closed
1 2  # open
O  -1.551007  -0.114520   0.000000
H  -1.934259   0.762503   0.000000
H  -0.599677   0.040712   0.000000
```

Summary
Looks like psi's b3lyp3 should remain with `VWN3RPA_C` and its b3lyp5 should use `VWN5_C` in order to match NW-Chem with both open- and closed-shell.

**Comment by loriab** [comment]
People at the forum have kindly supplied Turbomole and G* values for further comparison. They are encoded into the test case below, which passes using this PR branch (that reenables b3lyp5 with `VWN5_C`). The open-shell b3lyp5 in psi4 matches turbochem rather better than nwchem.

```
set scf_type pk
set e_convergence 9
set basis aug-cc-pvdz
set dft_spherical_points 590
set dft_radial_points 99

molecule cswater {
0 1
O  -1.551007  -0.114520   0.000000
H  -1.934259   0.762503   0.000000
H  -0.599677   0.040712   0.000000
}

oswater = cswater.clone()
oswater.set_multiplicity(2)
oswater.set_molecular_charge(1)

e = energy('b3lyp', molecule=cswater)
compare_values(-76.444577160243, e, 5, 'clsd-shell: b3lyp (vwn3rpa) vs NWChem (vwn_1_rpa; default)')

set reference uhf
e = energy('b3lyp', molecule=oswater)
compare_values(-75.974154693676, e, 5, 'open-shell: b3lyp (vwn3rpa) vs NWChem (vwn_1_rpa; default)')
compare_values(-75.97415476252, e, 5, 'open-shell: b3lyp (vwn3rpa) vs Turbomole (vwn3)')
compare_values(-75.9741544303, e, 5, 'open-shell: b3lyp (vwn3rpa) vs Gaussian (default)')

set reference rks
e = energy('b3lyp5', molecule=cswater)
compare_values(-76.407526614389, e, 5, 'clsd-shell: b3lyp5 (vwn5) vs NWChem (vwn_3)')

set reference uks
e = energy('b3lyp5', molecule=oswater)
compare_values(-75.940741067166, e, 4, 'open-shell: b3lyp5 (vwn5) vs NWChem (vwn_3)')
compare_values(-75.94075271487, e, 5, 'open-shell: b3lyp5 (vwn5) vs Turbomole (vwn5; default)')
# this one doesn't match quite so well
```

**Comment by loriab** [comment]
Ok, elaborated on the `set print 2` descriptions of the four VWNs, and added a test case vs. other packages in https://github.com/psi4/psi4/pull/339/commits/f535e22afefbaeac65c78e95788c5f211f85b11c . When you're satisfied with the labeling, etc. @robparrish, I think this is good to go. I'll add you as a collaborator to my fork so that you can do any simple editing directly.

**Comment by robparrish** [comment]
OK, agreed, B3LYP is defined with VWN1RPA, B3LYP5 is with VWN5. I think this is good to go. One thing that might avoid unnecessary clarification in future is to rename PSI4's VWN3* to VWN1*. Thanks to everyone for all your efforts in this one.

**Comment by loriab** [comment]
Great! Provided the stability instability doesn't pop up again, this is ready. If you definitely want VWN3 renamed, I'll do it. But since the functional repository names it VWN3 and the coding of the functional is a lot harder to check than the assembly of the superfunctional, I think the extra notes I added to `set_description` will bridge the clarity gap.

**Pull request merged**
