### PR TITLE
Linear Exchange Matrix Build (LinK)

### PR DESCRIPTION
**Pull request by andyj10224**
## Description
Implements the linear exchange matrix build (LinK) algorithm for Direct SCF.
Reference: C. Ochsenfeld, C.A. White, and M. Head-Gordon,  J. Chem. Phys. 109, 1663 (1998)
(https://aip.scitation.org/doi/10.1063/1.476741)

NOTE: The J build already has density screening implemented (see #2155)

wc_linK_errors_updated_06_04_21
wc_linK_timings_hornet_06_04_21

## Todos

- [x] Builds the K matrix of large molecular systems in O(N) time
- [x] Errors are minimal when compared to approximations like Density Fitting

## Questions
- [ ] This code is currently in DirectJK, should I make a new JK module for fast methods like LinK, since a fast K algorithm would be really useful for density fitting?

## Checklist
- [x] Tested accuracy and speed of method on a 3D system of growing water clusters.

## Status
- [x] Ready for review
- [ ] Ready for merge

### CODE REVIEW

**Comment by susilehtola** [comment]
It looks like the diff is not clean: there are changes that don't appear to arise from this pull. There's also a merge conflict.

**Comment by susilehtola** [comment]
Did you do a rebase pull, and forget to push with --force?

**Comment by loriab** [comment]
> It looks like the diff is not clean: there are changes that don't appear to arise from this pull. There's also a merge conflict.

Yes, we're working on it. Much history in this branch.

**Comment by andyj10224** [comment]
> > It looks like the diff is not clean: there are changes that don't appear to arise from this pull. There's also a merge conflict.
> 
> Yes, we're working on it. Much history in this branch.

Ugh, just spent all night rebasing, should be ready now. I will test my code again tomorrow as a sanity check :)

**Comment by JonathonMisiewicz** [comment]
I'm marking this as 1.5: this is too big to be a 1.4 target, given that the goal is to have 1.4rc2 up very soon.

**Comment by andyj10224** [comment]
> I'm marking this as 1.5: this is too big to be a 1.4 target, given that the goal is to have 1.4rc2 up very soon.

I agree, I did not intend for this to be 1.4. I am also working on CFMM (which will also be 1.5), and I should have that PR ready within the next month.

**Comment by andyj10224** [comment]
I tested my code after rebasing, still looks just like it did before. I updated the timings and errors graphs based on the results of my rebased code (I used an intel compiler this time, rather than GCC)

**Comment by susilehtola** [comment]
From what I understood of the code, LinK is only used for incremental Fock builds.

However, the algorithm should also be useful for full Fock builds.

**Comment by andyj10224** [comment]
> From what I understood of the code, LinK is only used for incremental Fock builds.
> 
> However, the algorithm should also be useful for full Fock builds.

My code works for full Fock builds too (I will test this later)

**Comment by susilehtola** [comment]
> > From what I understood of the code, LinK is only used for incremental Fock builds.
> > However, the algorithm should also be useful for full Fock builds.
> 
> My code works for full Fock builds too (I will test this later)

Of course it should, since full Fock is differential Fock with `delta P = P`.

My point was just that the code is now using the non-LinK algorithm for the full build step...

**Comment by JonathonMisiewicz** [comment]
I think this PR is next on your list, since #2155 merge is imminent. Rebase, fix the merge conflicts, and ping me when this is ready for review.

**Comment by andyj10224** [comment]
This LinK code is severely outdated. I will open a PR with a new one shortly.

**Pull request closed without merging**
