### PR TITLE
Enables serialized JSON jobs

### PR DESCRIPTION
**Pull request by dgasmith**
## Description
Provides serialized input and output capabilities through a JSON interface. This is an experimental feature and the JSON interface itself will likely evolve significantly over various iterations.

## Features
- `psi4 --json data.json` is now a valid Psi input.
- All python based exceptions (not just Psi exceptions) in Psithon should now be printed to the Psi output as well as stdout.
- Dimension objects now have an `__iter__` attribute.

## Status
- [x]  Ready to go

### CODE REVIEW

**Comment by loriab** [comment]
second time through, still LGTM

**Comment by amjames** [comment]
awesome! LGTM

**Comment by andysim** [comment]
This is a really clean solution.  lgtm

**Comment by andysim** [comment]
Not sure if you'd rather do a squash or just a plain rebase for the merge, so I'm going to punt.

**Comment by dgasmith** [comment]
I dont think we want to do squash commits unless its like `change1`, `redid change1`, `tweaked change1`. Not a huge deal either way.

**Comment by andysim** [comment]
Good to know.  For some reason I thought you preferred `1st part`, `2nd part`, `3rd part` to be rolled together if they're all contributions to the same overall feature.  I agree with your idea though; squash should be used for Trumpian commits.

**Comment by dgasmith** [comment]
Probably would in general, it just seems that our commits seem to hit a lot of topics. For example, this is JSON, exception, and Dimension object handling.

**Comment by andysim** [comment]
Still lgtm after being rebased (I opted not to go nuclear and skip the branch updating earlier)

**Pull request merged**
