### PR TITLE
Test unprivileged acct

### PR DESCRIPTION
**Pull request by cdsgroup**
## Description
effectively, update samples

## Status
- [x] Ready for review
- [x] Ready for merge **SQUASH**

### CODE REVIEW

**Review by PeterKraus — COMMENTED** [review]
OK, so GHA can generate `samples/` from `tests/`, keeping them in sync. I however don't understand where this action is stored - probably a different PR?

Also, when does this automatic `samples/` <- `tests/` update occur? It creates a PR, as needed, after every other merged PR, or only when the GHA is manually triggered?

**Review by hokru — APPROVED** [review]

**Comment by loriab** [comment]
@PeterKraus, good questions. I've outlined the current state here https://github.com/psi4/psi4/blob/gha-master/.github/workflows/README.md . at the moment the docs-pr action is stored at the gha-master branch, so I can edit it.

**Review by PeterKraus — APPROVED** [review]
That's pretty nifty. So each PR will get their docs built and accessible under [https://github.com/psi4/psi4docs/pulls]() as well as another commit updating `samples` from `tests`. 

Once the PR is merged, the docs are built again and pushed into the master branch of `psi4/psi4docs` which is where the psicode site points to.

Looks rather cool and I'm excited to see this in practice.

**Review by JonathonMisiewicz — APPROVED** [review]
I'm happy to see samples regenerated, but the README needs to be dumbed down. It took far too much effort on my end to understand, and I still can't make out much of this.

docs-pr.yml
	Please rewrite the first results bullet point to "Produces a tarball of the HTML docs that can be downloaded and inspected offline." Add instructions on how to find the tarball.
	Please rewrite the second bullet entirely. I cannot parse this. Do you mean "automated commit of sample generation to PR"?

"Results" and "Goals" are ambiguous at present. As best as I can make out, "Results" means "what are the individual automated processes", while "Goals" for `docs.yml` means "list out the things that are built" while for `docs-pr.yml`, it means "list the purpose of this." Please separate out the _purpose_ from the _things we want physically available at the end of the dosc project_, and mark _the status of the physically available things_.

**Pull request merged**
