### PR TITLE
MBIS valence charges

### PR DESCRIPTION
**Pull request by tallakahath**
## Description
Prints out the MBIS valence charges. These were already being computed, just not exposed to the user. Tests were added for the new output, and all tests pass. There is no impact on runtime because it is just exposing values already being computed.

Addresses https://github.com/psi4/psi4/issues/3140

## User API & Changelog headlines
- [x] MBIS valence charges are now exposed and printed in MBIS output
- [x] The wfn array_variable `MBIS VALENCE CHARGES` is now available to be retrieved

## Dev notes & details
- [x] Saves the MBIS valence charges to it's own little matrix
- [x] And exposes those charges on the python side as the wfn variable `MBIS VALENCE CHARGES`
- [x] Updates the relevant tests

## Checklist
- [x] Tests added for any new features
- [x] [All or relevant fraction of full tests run](http://psicode.org/psi4manual/master/build_planning.html#how-to-run-a-subset-of-tests)

## Status
- [x] Ready for review
- [ ] Ready for merge

### CODE REVIEW

**Comment by kzinovjev** [comment]
Thanks, this is essentially the same as https://github.com/psi4/psi4/pull/3102 but done properly! Will close the other one in favor of this.

**Review by JonathonMisiewicz — APPROVED** [review]

**Comment by JonathonMisiewicz** [comment]
@tallakahath Please pull the branch and then commit the addition of `MBIS VALENCE WIDTHS` to the [glossary](https://github.com/psi4/psi4/blob/master/doc/sphinxman/source/glossary_psivariables.rst). Just follow the pattern of the other MBIS variables.

**Comment by tallakahath** [comment]
@JonathonMisiewicz I think I did it right -- I added `MBIS VALENCE CHARGES` (`MBIS VALENCE WIDTHS` was already present) to the glossary and got things pulled in. Does this lgty now?

**Comment by JonathonMisiewicz** [comment]
> @JonathonMisiewicz I think I did it right -- I added `MBIS VALENCE CHARGES` (`MBIS VALENCE WIDTHS` was already present) to the glossary and got things pulled in. Does this lgty now?

It should be. We need one other reviewer, and then to troubleshoot the failing test... The failure is unrelated to this PR.

**Review by loriab — APPROVED** [review]
lgtm, thank you!

That blas error is often a fluke – I've restarted to see if it persists.

**Comment by loriab** [comment]
Heads up that I've edited the PR branch. My current hypothesis is that MKL 2022.2 is reacting badly on Windows with Psi4. Recent CI with 2022.1 and 2024.1.0 have been successful, so I'm pinning to the latter. (For anyone following, the `24*` doesn't have anything to do with v2024. Instead, build `24_win64_mkl` at https://anaconda.org/conda-forge/libblas/files is pinned to MKL 2024.1 (the latest, `25_`, uses 2024.2).)

**Comment by loriab** [comment]
Ok, first CI error was MKL 2022.2 not working with Win Psi4. Second CI error was Windows builds were recently re-enabled for simple-dftd3/dftd3-python, so there's a big version skip, 0.6 -> 1.2, and the path to the parameters file isn't right for the W layout. I've filed an PR upstream. At last, this is RTG!

**Pull request merged**
