### PR TITLE
Fix SAD guess energy printout

### PR DESCRIPTION
**Pull request by susilehtola**
## Description
The first iteration energy in SAD is at best non-variational (RHF, UHF), and at worst completely nonsensical (ROHF, CUHF). As neither a DIIS error can be formed in the lack of a proper density matrix, this PR sets the first iteration energy to zero, so that only sensical energies are printed out.

## Todos
Notable points (developer or user-interest) that this PR has or will accomplish.
- [x] Guess energy correctly evaluated in ROHF and CUHF
- [x] Guess energy properly labeled

## Questions
- [ ] Question1

## Checklist
- [ ] Tests added for any new features
- [ ] [All or relevant fraction of full tests run](http://psicode.org/psi4manual/master/build_planning.html#how-to-run-a-subset-of-tests)

## Status
- [x] Ready for review
- [x] Ready for merge

### CODE REVIEW

**Comment by dgasmith** [comment]
The first SAD energy gives you a general feeling of how well SAD is doing. We do mark this as "Iteration 0", but we could bump up the documentation level there. Either way very much not in favor of removing it wholesale.

**Comment by loriab** [comment]
Maybe labeling it `!` instead of `0` would better signal untrustworthiness.

**Comment by susilehtola** [comment]
> The first SAD energy gives you a general feeling of how well SAD is doing. We do mark this as "Iteration 0", but we could bump up the documentation level there. Either way very much not in favor of removing it wholesale.

Right, but it's still a RHF/RKS energy, and for e.g. ROHF it just gives total nonsense. I'll have a look if there's a way to fix the initial energy evaluation so that the guess outputs the same energy regardless of the reference, and also put in @loriab's suggestion to mark the iteration with ```!```

**Comment by susilehtola** [comment]
Test case:
```
molecule {
0 3
O
}

set reference rohf
set basis pcseg-1
set guess sad
energy('scf')
```

Output before changes:
```

                           Total Energy        Delta E     RMS |[F,P]|

   @DF-ROHF iter   0:    28.43955367824759    2.84396e+01   0.00000e+00 
   @DF-ROHF iter   1:   -74.75118310291205   -1.03191e+02   1.84153e-02 DIIS
   @DF-ROHF iter   2:   -74.75844495846947   -7.26186e-03   6.55338e-03 DIIS
   @DF-ROHF iter   3:   -74.75962778267566   -1.18282e-03   8.89743e-04 DIIS
   @DF-ROHF iter   4:   -74.75966293836538   -3.51557e-05   7.52761e-05 DIIS
   @DF-ROHF iter   5:   -74.75966326690698   -3.28542e-07   1.44805e-05 DIIS
   @DF-ROHF iter   6:   -74.75966327706121   -1.01542e-08   4.33092e-07 DIIS
  Energy and wave function converged.
```

Output after changes
```
  ==> Iterations <==

                           Total Energy        Delta E     RMS |[F,P]|

   @DF-ROHF iter SAD:   -73.85293189670189   -7.38529e+01   0.00000e+00 
   @DF-ROHF iter   1:   -74.75118310291205   -8.98251e-01   1.84153e-02 DIIS
   @DF-ROHF iter   2:   -74.75844495846947   -7.26186e-03   6.55338e-03 DIIS
   @DF-ROHF iter   3:   -74.75962778267566   -1.18282e-03   8.89743e-04 DIIS
   @DF-ROHF iter   4:   -74.75966293836538   -3.51557e-05   7.52761e-05 DIIS
   @DF-ROHF iter   5:   -74.75966326690698   -3.28542e-07   1.44805e-05 DIIS
   @DF-ROHF iter   6:   -74.75966327706121   -1.01542e-08   4.33092e-07 DIIS
  Energy and wave function converged.
```

**Pull request merged**
