### PR TITLE
Unclickable Function Reference

### PR DESCRIPTION
**Pull request by kcpearce**
## Description
Fix one instance of the energy() function reference not being clickable by changing "~driver.energy()" to be "~psi4.energy()"

## Todos
Notable points that this PR has either accomplished or will accomplish.
- [x] Make energy() clickable

## Questions
- [ ]  Question1

## Status
- [x]  Ready to go

Fix energy() function reference to be clickable

### CODE REVIEW

**Comment by kcpearce** [comment]
Change energy() function reference to be clickable

**Comment by loriab** [comment]
LGTM

**Comment by dgasmith** [comment]
LGTM

**Comment by jturney** [comment]
LGTM

**Pull request merged**
