### PR TITLE
Adds non-relativistic core-valence basis sets for Sc-Zn.

### PR DESCRIPTION
**Pull request by fevangelista**
## Description
Adds cc-pwCVXZ-NR basis sets (X = T,Q,5) of Balabanov and K.A. Peterson (J. Chem. Phys. 2005) for elements Sc-Zn.

## Todos
Notable points that this PR has either accomplished or will accomplish.
- [X] Adds missing basis sets for Sc-Zn.

## Questions
- [ ]  Should this be merged with the cc-pwCVXZ basis set file?  In EMSL this basis set has the suffix "-NR" to distinguish it from the "-DK" version.

## Status
- [ ]  Ready to go

### CODE REVIEW

**Comment by dgasmith** [comment]
The `-NR` threw me a bit, but are these just `cc-pwCVXZ` basis functions? If so, then yes please add them to the `cc-pwCVXZ` file otherwise things could get quite confusing. Especially with fitting bases.

**Comment by CDSherrill** [comment]
I think they might be tagged that way in EMSL?  Better check.

**Comment by fevangelista** [comment]
Yes, that's how they are tagged.  I don't think that the corresponding RI or JK-FIT basis set are available.  In any case I merged the basis sets with those in cc-pwCVXZ.gbs so if we want to go with the uniform name they are ready.

**Comment by dgasmith** [comment]
I should have been clear. We want this tagged in the same BasisSet family even though there are no corresponding DF/RI basis for those particular atoms so that we get a better failure message.

**Pull request merged**
