### PR TITLE
main channel adcc

### PR DESCRIPTION
**Pull request by loriab**
## Description
main channel adcc uses MKL and subchannel is gone. try to fix CI.
## Status
- [ ] Ready for review
- [ ] Ready for merge

### CODE REVIEW

**Comment by mfherbst** [comment]
Yes sorry about that ... in the build it downloads an old adcc version from github instead of recognising the installed version from conda it seems. I'll take a look.

**Comment by loriab** [comment]
@mfherbst, looks like the adcc of main is working nicely. If you could build py3.6, that should fix the remaining CI lane. And building py3.8 would future-proof the lineup. Thanks!

**Comment by mfherbst** [comment]
Yes it's py 3.6. We do not have this at the moment. I made an amendment in #1827 to disable adcc testes if pyversion != 3.7. We'll look into producing builds for 3.6 and 3.8 as well.

**Comment by mfherbst** [comment]
Py 3.6 is now available on anaconda as well, see #1827.

**Comment by loriab** [comment]
closed in favor of #1827

**Pull request closed without merging**
