### PR TITLE
Temporary link for compilation instructions

### PR DESCRIPTION
**Pull request by bwb314**
## Description
The added link gives current instructions for how to install Psi4 from source.

## Status
- [X]  Ready to go

### CODE REVIEW

**Comment by loriab** [comment]
Good idea to throw the outdated wiki info into docs, too. Go ahead and link to all the options sections, though: https://github.com/psi4/psi4/blob/master/CMakeLists.txt#L13-L105

Even though the line numbers may shift slightly, the three Options sections contain everything anyone might need to change.

**Comment by andysim** [comment]
lgtm

**Comment by bwb314** [comment]
Ok, just added a link to all of the options sections.

**Comment by loriab** [comment]
LGTM

Recommend "Squash and merge".

**Comment by jturney** [comment]
LGTM

**Pull request merged**
