### PR TITLE
Feature/o24 data set vol. 2

### PR DESCRIPTION
**Pull request by PhillCli**
## Description
follow up on the #2154 since in the heat it got merged before I was done with it.

## Todos
- [x] adds test-case for O24
- [x] cleans up the `TAGL` 

## Checklist
- [x] Tests added for any new features
- [x] [All or relevant fraction of full tests run](http://psicode.org/psi4manual/master/build_planning.html#how-to-run-a-subset-of-tests)

## Status
- [x] Ready for review
- [x] Ready for merge

### CODE REVIEW

**Comment by PhillCli** [comment]
Waiting to see if test-case passes, all clear if it does.

**Comment by PhillCli** [comment]
looks like it's clear,
```log
166/184 Test #457: python-databases .................   Passed   22.93 sec
```
@loriab does these tags look ok??
```
add_regression_test(python-databases "psi;quicktests;python;noc1")
```

**Comment by JonathonMisiewicz** [comment]
I defer to Lori on whether this belongs in `tests/python` or `tests/pytest`. I'm not sure what the difference is.

**Review by loriab — APPROVED** [review]
lgtm, thanks. `tests/python` was where one put API tests before `tests/pytests/` came about. fine to lodge it there -- that folder will be translated to pytest.

**Review by JonathonMisiewicz — APPROVED** [review]

**Review by andysim — APPROVED** [review]
Thanks for addressing this so quickly - this is a really nice cleanup.  I like the use of f-strings for formatting the output.  LGTM!

**Pull request merged**
