### PR TITLE
Fix FCIDUMP irrep ordering convention

### PR DESCRIPTION
**Pull request by zachglick**
## Description
Addresses #1431 

## Todos
Notable points (developer or user-interest) that this PR has or will accomplish.
- [x] Changes ORBSYM (the symmetry of each orbital) from Psi4's internal convention of ordering irreps to the traditional FCIDUMP ordering
- [x] Adds ISYM (the symmetry of the overall wavefunction)
- [x] Updates the `fcidump` test to match new ordering

## Questions
- [x] Does this change in convention break anything in Psi4? (Or anything that uses Psi4?)
- [x] Since I altered the tests to match the output, how to verify correctness of this change?

## Checklist
- [x] [All or relevant fraction of full tests run](http://psicode.org/psi4manual/master/build_planning.html#how-to-run-a-subset-of-tests)

## Status
- [x] Ready for review
- [ ] Ready for merge

### CODE REVIEW

**Comment by CDSherrill** [comment]
Wfn irrep logic for socc not correct... (Around line 91).  Need to take
direct product of each socc orbital irrep.  Can do this by XOR of each
irrep in the socc list.

**Comment by zachglick** [comment]
@robertodr and @andysim 
I could certainly make a PsiAPI test for energies, although I think the leading underscore of `_energies_from_fcidump` will have to be removed, since it denotes that the function is private.

@CDSherrill 
I intended for this bit of code to do exactly what you describe:

``` wfn_irrep = 0
    for h, n_socc in enumerate(active_socc):
        if n_socc % 2 == 1:
            wfn_irrep ^= h
```

The line `wfn_irrep ^= h` accumulates the XOR of all irreps `h` in `wfn_irrep`. I could rewrite it as `wfn_irrep = wfn_irrep^h` to make it more intelligible.

I think that the format of `active_socc` is not a list of irreps, instead it's a list of orbital counts per irrep, which is why I XOR `h` and not `n_socc`. The `if n_socc % 2 == 1` check takes advantage of the fact that a number XORed with itself is 0, so only irreps with an odd number of orbitals matter.

**Comment by robertodr** [comment]
I have no objection in making `_energies_from_fcidump` public, it was in an earlier iteration of the FCIDUMP functionality.

**Comment by robertodr** [comment]
:+1: for adding the test and thanks again for taking care of this issue!

**Comment by CDSherrill** [comment]
Ah, I quickly read this on my phone and missed that the XOR was in a loop.  Yes, looks good!

**Pull request merged**
