### PR TITLE
CI for Windows on Azure

### PR DESCRIPTION
**Pull request by raimis**
## Description
This is part of *Psi4* porting to Windows (#933).

This is intended as a replacement for *Appveyor*, which has 60 min limit. *Azure* allow to run up to 360 min!

## Todos
Notable points (developer or user-interest) that this PR has or will accomplish.
- [x] CI for Windows on *Azure*

## Checklist
- [x] Tests added for any new features
- [x] [All or relevant fraction of full tests run](http://psicode.org/psi4manual/master/build_planning.html#how-to-run-a-subset-of-tests)

## Status
- [x] Ready for review
- [x] Ready for merge

### CODE REVIEW

**Comment by raimis** [comment]
Azure in action: https://dev.azure.com/raimisg/psi4/_build/results?buildId=178

**Comment by dgasmith** [comment]
That’s amazing! Pretty big fan of Azure over Appveyor, especially so for bigger projects.

I’ll give the build files a check tomorrow.

**Comment by JonathonMisiewicz** [comment]
Ooh, and builds can take more than an hour. Hopefully we'll be seeing fewer timeouts.

**Comment by raimis** [comment]
@loriab the switching to Python 3.6 is intentional. I just copied scripts from Appveyor, where I had to pin Python version due to missing dependencies.

**Comment by raimis** [comment]
This is ready to be merged and after the pipeline has to be configured: https://dev.azure.com/psi4/psi4/_build

**Pull request merged**
