### PR TITLE
Refreshed all tests/*/output.ref's for the Psi4 release.

### PR DESCRIPTION
**Pull request by dgasmith**
## Description
Refreshed all output.ref's in the tests folder. An interesting discovery is that some DFT methods (wB97X, and wB97) inhibit the Psi4 output printing. We need to fix this before this PR goes through, but I wanted to start in on checking some of the changes.

## Todos
- [x] Several DFT functionals no longer print their output correctly. While the program still runs the input script (can be verified with python print), Psi4 printing has stopped. This needs to be fixed. 
- [x] Update dft1, dft1-alt, and dft2 test case output.ref's after the above change.

## Spot check outputs
I don't think its possible to compare every single output, but I would like to borrow the following people to spot check a few outputs. We run quite a few tests, but they certainly are not comprehensive. This could potentially show holes in our testing strategy (like the above issue). 

Probably the easiest way to do this is go to the "Files changed" tab at the top and use a browser search to find a file your interested in. This does require you to know the name of the file in question. Alternatively, you can download my branch and run a `git diff -w -b HEAD~4 filename`. The `-b -w` options are to help cleanup the diff a bit.

- [x] CC @lothian 
- [x] OCC/DFOCC @bozkaya 
- [x] Psithon/DFTD3/PyWrap/etc @loriab 
- [x] FNO-CC @edeprince3 
- [x] Opt @psi-rking 
- [x] CI (myself)
- [x] SCF/DFT @jturney @robparrish 
- [x] DCFT @andysim 

## Status
- [ ]  Ready to go

### CODE REVIEW

**Comment by psi-rking** [comment]
I checked all the optimization tests.  I saw no major problems.  A few of the cases now converge a bit faster.  

opt-lindep-change/input.dat could be updated to the current energy after 3 steps, but this is not essential as we don't fully optimize this case.

for opt10: we've changed basis sets, which is the reason for the different energy in the new output.ref

For some of the older cases, the testing criterion should be tightened.  Specifically for 
opt1, opt1-fd, opt4, and opt5.  The default SCF algorithm changed from PK->DF, and these output's are older.  So I expect someone simply reduced the checking to only 3 decimals to maintain a PASS.  We should tighten this up and be able to get 6 decimals in the energy - at least 5 - in a full optimization, at least.  Note for tests such as opt 2, pk is specified and 6 decimals are checked already.

**Comment by dgasmith** [comment]
@psi-rking Sure, making those changes did not seem to hurt anything. Glad everything looks good.

**Comment by loriab** [comment]
I'll sign off on psithons and pywraps. dftd3 I'll check after the dft printing and dftd3-version (failing for me now, too) are solved. I'll throw in that `git diff --word-diff=color -w -b HEAD~4` is a nice way to review these files.

**Comment by dgasmith** [comment]
@andysim @lothian @edeprince3 @bozkaya Can you check off your test cases or refer someone who can review them?

**Comment by andysim** [comment]
Sorry for the delay.  The DCFT tests look good to me.  I think we can also check of the CC tests; if I remember correctly, those tests are actually validated by comparing the output to the reference using a separate Perl script.  If the tests run successfully, it means that the output is present and correct, or Perl wouldn't be able to parse it.

**Comment by dgasmith** [comment]
As a note: not all CC tests are tested through Perl. Actually looking at the output has caught a few bugs so far, although it does require someone intimately familiar with the tests to do so.

I would be happy if we could get eyes on every test, but if it doesn’t happen its not a big deal.

**Comment by lothian** [comment]
I need to update the test for cc5, which is currently failing even though
it's not run automagically.  It seems that the reference output was
overwritten by an output from a failed calculation.

-TDC

--
Prof. T. Daniel Crawford
crawdad@vt.edu

**Comment by bozkaya** [comment]
Sorry for my late response. It looks okay for OCC and DFOCC tests.

**Comment by dgasmith** [comment]
@lothian I fixed cc5 in this branch. cc5 now runs, passes, and the output.ref is updated.

**Comment by lothian** [comment]
What was the bug in cc5?

--
Prof. T. Daniel Crawford
crawdad@vt.edu

**Comment by dgasmith** [comment]
The job did not have enough memory and failed due to a TOCLEN error. I shot you a gchat about this awhile back, but did not receive a response and consequently forgot about it.

**Comment by lothian** [comment]
Oh, sorry I missed the message about the TOCLEN.

--
Prof. T. Daniel Crawford
crawdad@vt.edu

**Comment by dgasmith** [comment]
@lothian I am just happy that I remembered this! 

I updated some CC output printing to align a bit better and checked over a few CC test cases. I think everything looks ok, but if someone else could eye ball a couple that would be great.

**Pull request merged**
