### PR TITLE
FIX: Tightens up a few tests

### PR DESCRIPTION
**Pull request by dgasmith**
Based off the forums and a few issues there are a few tests that are not quite robust enough to test the code rather than a operational tweaks.
 - `props2` - The new orientation code requires that this be moved to the COM at every step.
 - `props3` - Overall convergence needs to be tightened to move flutter in 64-pole below test threshold.
 - `scf-cov` - Convergence needs to be tightened in addition to not using a C2v molecule during a orientation check.

### CODE REVIEW

**Comment by loriab** [comment]
I presume this actually fixes props2 (in which case should also add back to tests/CM). My concern is the change that people won't automatically get their multipoles at the origin w/o explicitly asking and that behaviour is different btwen Cart/ZMat (psi4/psi4#782). Anyone else concerned?

The scf-coverage problems we've been seeing have been compilation dependent after DF_Helper merge. Do you consider the changes to this test a fix to slightly flawed test?

**Comment by CDSherrill** [comment]
I pulled up issue 782 to remind my self what is going on, but the comments
there are somewhat terse and they don't do enough to jog my memory even
though I had a conversation with Lori about it.  I'm not sure the wider
community will be able to comment much on this point without doing a little
homework to figure out what is being asked about.  Could we have a bit more
commentary describing the issue?

**Comment by dgasmith** [comment]
I view `props3` and `scf-cov` fixing up a slightly shaky/flawed test.

For `props2` this is fixing an issue caused by the Cart/ZMat changes. Let me comment there further to keep that discussion contiguous.

**Comment by loriab** [comment]
[props2 commentary](https://github.com/psi4/psi4/issues/782#issuecomment-332296506), as I don't think you're on that thread, @CDSherrill 

props3, scf-coverage LGTM

**Pull request merged**
