### PR TITLE
v1.4 codemeta.json

### PR DESCRIPTION
**Pull request by loriab**
## Description
Updating codemeta while I've got author info handy. Anyone -- you're welcome to update affiliations. The rule of thumb is affiliation is the most recent place from whence you contributed to psi. @maxscheurer, please supply your latitude and longitude.

## Status
- [x] Ready for review
- [x] Ready for merge

### CODE REVIEW

**Comment by maxscheurer** [comment]
@loriab 
49.417312, 8.675617

**Comment by loriab** [comment]
also, @yxie326, you need to make an https://orcid.org/

**Comment by PeterKraus** [comment]
@loriab 
-32.0117, 115.8929

**Comment by loriab** [comment]
I'm seeking to get Javascript disabled so this thing passes. Maybe it doesn't like the repetitive `"@id"`, but I don't see another good way to store GH and orcID. https://discuss.lgtm.com/t/disable-javascript-analysis/2150/15?u=loriab

**Pull request merged**
