### PR TITLE
fmt: clang-format the cclambda module

### PR DESCRIPTION
**Pull request by andysim**
## Description
clang-format the cclambda module

## Questions
- [ ] If merging this PR will hinder your research b/c you have local edits, protest here or in #1144

## Status
- [x] Ready for review
- [x] Ready for merge

### CODE REVIEW

**Comment by andysim** [comment]
This has been force updated, and includes #1257

**Comment by amjames** [comment]
Thanks @andysim. #1257 is in so there is nothing blocking this anymore. Third reviewer is free to merge! (once everything is green)

**Comment by andysim** [comment]
Just to confirm, you have an alternate plan for #1061, right?

**Comment by amjames** [comment]
@andysim yes, and thanks for the reminder. I am going to post a comment overthere explaining what we are going to do on that front.

**Pull request merged**
