### PR TITLE
Minor fixes

### PR DESCRIPTION
**Pull request by dgasmith**
## Description
A few quick fixes that came up over the Psi weekend.

## Fixes
- [x] Kills off duplicate `_setup.py`
- [x] Adds more docs for MOLDEN MO write.
- [x] Reworks inplace. Please review @loriab @jturney

## Status
- [x]  Ready to go

### CODE REVIEW

**Comment by loriab** [comment]
I think ``--inplace`` as fixed here possibly wouldn't work with a non-default `-DPYMOD_INSTALL_LIBDIR`, but that's an odd enough combination that if I have one someday, I'll figure out the adjustments.

LGTM

**Comment by jturney** [comment]
This looks ok to me. I agree with @loriab that I'm not sure about ```-DPYMOD_INSTALL_LIBDIR``` working.

LGTM

**Comment by dgasmith** [comment]
For running `--inplace` im not sure there is a good way to communicate that back. There are some `--inplace` sacrifices and this may be one of them.

**Comment by jturney** [comment]
Oh right, with ```--inplace``` the value of ```-DPYMOD_INSTALL_LIBDIR``` shouldn't matter was inplace imples source directory.

**Comment by andysim** [comment]
I noticed the RTG box isn't checked yet.  Should I review this, or are you still adding stuff?

**Comment by dgasmith** [comment]
@andysim I can always open a new one if something comes up. Im done, just waiting on Travis now.

**Comment by andysim** [comment]
LGTM

**Pull request merged**
