### PR TITLE
Fixes basis_guess with -D combo

### PR DESCRIPTION
**Pull request by bwb314**
## Description
DFT-D plus the use of a guess basis set produced an error because of a typo in setting the dispersion energy: set_variables -> set_variable. 

## Status
- [X] Ready to go

### CODE REVIEW

**Comment by dgasmith** [comment]
Better question: How was this not tested? Should Travis go through smoke tests.

**Comment by loriab** [comment]
Aren't a whole lot of tests of guess_basis. I think "smoke" is a subset of "quick", through I would like the full set of smoke addons.

**Comment by dgasmith** [comment]
Oh, I see its only if its cast and no other scenario. @bwb314 Can you add a *single* cast to `tests/dftd3/energy/input.dat`?

**Comment by dgasmith** [comment]
Looks good to me, will pull in once everything passes.

**Pull request merged**
