### PR TITLE
Continuous Fast Multipole Method (CFMM)

### PR DESCRIPTION
**Pull request by andyj10224**
## Description
This code is an implementation of the CFMM Method (C.A. White et. al 1994) for linear-scaling building of the J matrix, used in HF, DFT, and SAPT.

Reference Paper: https://www.sciencedirect.com/science/article/pii/0009261494011281

## Todos

- [x] Implements a Low Scaling J matrix build that is competitive with traditional DirectJK J matrix build, giving a complementing linear scaling algorithm to Linear Exchange (LinK).
- [x] Implements a new and more efficient multipoles library in Psi4 (in libfmm as multipoles_helper)

## Questions
- [ ] Do we need to make a new JK class to handle new methods like CFMM and LinK? (Like LinearJK : public JK)

## Checklist
- [ ] Tests added for any new features
- [ ] [All or relevant fraction of full tests run](http://psicode.org/psi4manual/master/build_planning.html#how-to-run-a-subset-of-tests)

## Status
- [ ] Ready for review
- [ ] Ready for merge

## Data
(Comparing the J build in CFMM (Waterclusters, 6-31G*) to a traditional DirectJK build of the J and K matrices)
Comparative CFMM Watercluster Results 10-02-2021

(Looking at the CFMM errors over system size (using multipole order 10, only considering systems that converge within 8 iterations)
CFMM Errors (New CFMM Code)

(Looking how the CFMM total J time compares to the total wall time [No LinK is used])
(NOTE: The near field calculations take up a majority of the J build time, as multipoles are relatively free)
CFMM Watercluster Results 10-02-2021

### CODE REVIEW

**Comment by andyj10224** [comment]
P.S. Ignore most of my commit messages (I have too much fun when coding :))

**Comment by JonathonMisiewicz** [comment]
I am not planning to look at this code until your other two PRs (#2155 and #2187) are closer to acceptance but am leaving some "triage" comments.

* Labels in the title are an eyesore, and GitHub has its own labels feature. I've added them as proper labels instead. Similarly, in future, please mark a PR as draft rather than add a "[Work in Progress]" text tag.
* It isn't clear to me if there's anything in particular you want to get by submitting this PR when it's not even marked for review. Did you submit this to get feedback on the "Do we need a new JK object?" question?
* I am going to ask that _in future_, you have more descriptive git commits rather than whatever words are currently on your mind. As somebody who has to debug Psi decently often, commit histories are often an invaluable clue to figuring out what the intention behind some obscure piece of code is. I'd _prefer_ if you cleaned up the commit messages for this PR, but I'm not going to insist on it.

**Comment by hokru** [comment]
Thanks Andy! Will be great to have this feature!

Commits should be squashed  and renamed when this is no longer WIP ;-)

**Comment by andyj10224** [comment]
> I am not planning to look at this code until your other two PRs (#2155 and #2187) are closer to acceptance but am leaving some "triage" comments.
> 
> * Labels in the title are an eyesore, and GitHub has its own labels feature. I've added them as proper labels instead. Similarly, in future, please mark a PR as draft rather than add a "[Work in Progress]" text tag.
> * It isn't clear to me if there's anything in particular you want to get by submitting this PR when it's not even marked for review. Did you submit this to get feedback on the "Do we need a new JK object?" question?
> * I am going to ask that _in future_, you have more descriptive git commits rather than whatever words are currently on your mind. As somebody who has to debug Psi decently often, commit histories are often an invaluable clue to figuring out what the intention behind some obscure piece of code is. I'd _prefer_ if you cleaned up the commit messages for this PR, but I'm not going to insist on it.

Also, I opened this PR early in order to a) Update the Psi developers on the progress of the new CFMM code, and b) To get y'all to start thinking about the future of the JK class, and potential design choices for if a user would like to run, per se DF-J + linK, CFMM-J + chain-of-spheres K, etc.

Also, most of my "non-sense" PR messages result from the fact that I have to change branches, so I make a quick push to GH before I switch to another project, and can be safely ignored, as they don't mean anything. I will avoid doing such a thing in the future though, and add more descriptive Git messages :) However, the descriptive commit messages DO mean something.

**Comment by andyj10224** [comment]
> Thanks Andy! Will be great to have this feature!
> 
> Commits should be squashed and renamed when this is no longer WIP ;-)

Just did the squashing and renaming :)

**Comment by susilehtola** [comment]
Shouldn't the SCF cycle also write out that CFMM has been used?

**Comment by andyj10224** [comment]
Long since gone stale. Code is buggy and outdated.

**Pull request closed without merging**
