### PR TITLE
pyoptking, take 2

### PR DESCRIPTION
**Pull request by loriab**
## Description
Continues from #1120. pyoptking largely plumbed in.

## Todos

Failing tests from full suite. These will definitely include (a) functions to opt, (b) mixed basis sets, an odd thing in fnocc2 where I can't get the wfn to freeze core.
- [ ]	 17 - cbs-xtpl-opt (Failed)
- [ ]	 18 - cbs-xtpl-func (Failed)
- [ ]	 20 - cbs-xtpl-wrapper (Failed)
- [ ]	114 - dcft5 (Failed)
- [ ]	204 - fnocc2 (Failed)
- [ ]	267 - opt-lindep-change (Failed)
- [ ]	277 - opt8 (Failed)
- [ ]	281 - opt13 (Failed)
- [ ]	282 - opt14 (Failed)
- [ ]	283 - opt-irc-1 (Failed)
- [ ]	284 - opt-irc-2 (Failed)
- [ ]	285 - opt-irc-3 (Failed)
- [ ]	301 - pubchem1 (Failed)
- [ ]	304 - pywrap-all (Failed)
- [ ]	393 - python-pubchem (Failed)
- [ ]	419 - gcp-pbeh3c (Failed)
- [ ]	428 - pcmsolver-opt-fd (Failed)

## Checklist
- [ ] Tests added for any new features
- [ ] [All or relevant fraction of full tests run](http://psicode.org/psi4manual/master/build_planning.html#how-to-run-a-subset-of-tests)

## Status
- [x] Ready for preliminary review. hopefully the optking team can work off this.
- [ ] Ready for merge

### CODE REVIEW

**Comment by JonathonMisiewicz** [comment]
Just to make sure, are we holding off on switching out our optkings until _after_ all the C-optking features get ported over? I use Psi for IRC's, but commit history says those aren't working in Py-optking yet.

**Comment by loriab** [comment]
Correct, at a minimum all tests must pass before merge. @alexheide has been working on IRC this fall, iirc. I’m sure we’ll hear more Friday.

**Comment by loriab** [comment]
PRs psi-rking/optking#24 and psi4/psi4#1335 are a pair. Together, they get most optimizations working for Psi. In particular have working:

- [x] ordinary, opt-is-full job optimizations
- [x] collecting all the psivars so psi can read them in. basically, collecting enough to generate a skeleton (mol, basis, psivars) that can be passed back from `psi4.optimize(..., return_wfn=True)`
- [x] inlining optking's logging output into the psi4 output file
- [x] resetting psi4's options on either side of the `optking.run_json_dict()` call. The trouble was that the psi4-s imported by optking were clearing and setting options (as is proper for indep json runs) such that the calling psi4 didn't have its original options in globals upon optking termination
- [x] starting to catch optking errors (str in json) and re-raising them as psi4 errors.

Yes, that AlgError vs OptError for exceeding geom_maxiter really stumped me for a while b/c I only got the final error ("dynamic level exceeded") and I thought it was behaving differently btwn direct optking and psi4 initiated runs. To me it seems clear that if geom_maxiter is exceeded, then optimizer quits directly (though perhaps that's clearer when geom_maxiter=2 than =200).

@psi-rking @AlexHeide

**Comment by psi-rking** [comment]
Sometimes ultimate convergence is more important than any maxiter variable
- particularly for speedy methods or initial optimizations.  If an
optimization fails in internal coordinates, then one might want the
optimizer to try Cartesians, automatically.  The idea of a 'dynamic level'
(whatever its final name or design) is that a user could easily elect the
degree to which the optimizer should try different things to reach
convergence.

**Comment by dgasmith** [comment]
`max_iter` is always a hard limit in all of Psi4/optimizers/conjugate gradients/etc codes. It seems that this is a high level user expectation that should be obeyed.

**Comment by psi-rking** [comment]
Just a note to say I'm working on the IRC code in pyoptking again.  No promises - just optimism!

**Comment by loriab** [comment]
closed in favor of #2727

**Pull request closed without merging**
