### PR TITLE
v1.3 additional contributions

### PR DESCRIPTION
**Pull request by loriab**
## Description
@raimis, @JonathonMisiewicz, @alenaizan, @susilehtola, @zachglick  
Please suggest any spelling or initials changes. Also, supply info for https://github.com/psi4/psi4/blob/master/codemeta.json. Either post here or PR _to this PR_. You're also at liberty to decline.

## Status
- [x] Ready for review
- [x] Ready for **SQUASH** merge

### CODE REVIEW

**Comment by alenaizan** [comment]
Looks good. Here is my info:
    {
            "@type": "Person",
            "givenName": "Asim",
            "additionalName": "",
            "familyName": "Alenaizan",
            "affiliation": "Center for Computational Molecular Science and Technology, Georgia Institute of Technology",
            "latitude": 33.780,
            "longitude": -84.3965,
            "@id": "https://orcid.org/0000-0002-0871-664X",
            "@id": "https://github.com/alenaizan"
    }

**Comment by JonathonMisiewicz** [comment]
* The spelling is correct, but please add my middle initial. `J. P. Misiewicz`
* You want to move the "and" from the first line of "additional contributions" to the second

JSON field is
```
        {
            "@type": "Person",
            "givenName": "Jonathon",
            "additionalName": "P.",
            "familyName": "Misiewicz",
            "affiliation": "Center for Computational Quantum Chemistry, University of Georgia",
            "latitude": 33.94797,
            "longitude": -83.37482,
            "@id": "https://orcid.org/0000-0002-6425-9551",
            "@id": "https://github.com/JonathonMisiewicz"
        }
```

Congratulations on the 1.3rc1 tag, by the way!

**Comment by susilehtola** [comment]
Name form is OK in output. Json info
```
        {
            "@type": "Person",
            "givenName": "Susi",
            "familyName": "Lehtola",
            "affiliation": "Department of Chemistry, University of Helsinki",
            "latitude": 60.205097,
            "longitude": 24.964145,
            "@id": "https://orcid.org/0000-0001-6296-8103",
            "@id": "https://github.com/susilehtola"
        }
```

**Comment by zachglick** [comment]
Sounds great!

        {
            "@type": "Person",
            "givenName": "Zachary",
            "additionalName": "L.",
            "familyName": "Glick",
            "affiliation": "Center for Computational Molecular Science and Technology, Georgia Institute of Technology",
            "latitude": 33.780,
            "longitude": -84.3965,
            "@id": "https://github.com/zachglick"
        }

**Comment by raimis** [comment]
```
        {
            "@type": "Person",
            "givenName": "Raimondas",
            "familyName": "Galvelis",
            "affiliation": "Acellera",
            "latitude": 41.3971,
            "longitude": 2.2013,
            "@id": "https://orcid.org/0000-0001-8431-1612",
            "@id": "https://github.com/raimis"
        }

**Pull request merged**
