### PR TITLE
File names now have PID

### PR DESCRIPTION
**Pull request by ryanmrichard**
## Description
Addresses issue #548 by appending the process identification (PID) number to file prefixes generated with
the `get_writer_file_prefix` function.

## Todos
Notable points that this PR has either accomplished or will accomplish.
* **Developer Interest**
  - [x] PID is now appended to all file prefixes generated with the `get_writer_file_prefix` function
  - [x] Fixes `const` correctness in this function as well as simplifies internal guts
  - [x] Now ignores all file extensions (not just `.out` and `.dat`) when determining base file name
* **User-Facing for Release Notes**
  - [x] Some (all at the moment) of the generated ASCII file's names now contain the PID

## Status
- [x]  Ready to go

### CODE REVIEW

**Comment by ryanmrichard** [comment]
Before this gets merged, do we want to also do the `set guess file` change in it?  It's sort of in the spirit of this PR.  That of course requires feedback from the community.

**Comment by dgasmith** [comment]
Can you rebase this up to master. We can get it in next.

**Comment by ryanmrichard** [comment]
For the record this PR does not change the `set guess file` thing, largely because it appeared to be a bigger change than I initially thought.

**Comment by ryanmrichard** [comment]
@loriab see modified description

**Pull request merged**
