### PR TITLE
Nov cmake

### PR DESCRIPTION
**Pull request by loriab**
## Description
More build changes

## Todos
Notable points that this PR has either accomplished or will accomplish.
- [x] enable py3 testing
- [x] fix versioning at releases, allow conda build to get version before build
- [x] fix case where Fortran compilers required, but not detectable, have to be passed in
- [x] dashboard back

## Questions
- [x]  After these two PRs, just waiting on plugins from @jturney 

## Status
- [x]  Ready to go **after oct_cmake**

### CODE REVIEW

**Comment by jturney** [comment]
I'll rebase my plugin work to this and open a new PR.

**Comment by jturney** [comment]
LGTM

**Comment by andysim** [comment]
LGTM

**Comment by dgasmith** [comment]
LGTM.

**Pull request merged**
