### PR TITLE
FNO support in DFOCC (take 2)

### PR DESCRIPTION
**Pull request by loriab**
## Description
Replaces #824: Frozen Natural Orbitals were implemented for DF-CCSD and DF-CCSD(T) energies.

## Todos
- [x] FNOs are implemented for MP2.5, MP3, LCCD, CCD, CCSD, CCSD(T), and CCSD(AT).
- [x] Both DF and CD options are available (only for RHF ref for now).

## Checklist
- [ ] Tests added for any new features
- [ ] [All or relevant fraction of full tests run](http://psicode.org/psi4manual/master/build_planning.html#how-to-run-a-subset-of-tests)

## Status
- [ ] Ready for review
- [ ] Ready for merge

### CODE REVIEW

**Comment by loriab** [comment]
@bozkaya, I've just rebased and force-pushed to remove a conflict, so this branch should be good to go for whenever you care to proceed. Let me know if you have any problems accessing it. Thanks!

**Comment by bozkaya** [comment]
Hi Lori, 

Thank you for your arrangements. I was in a trip and just returned. Now, I would like to catch up with psi4, otherwise it will a problem for me to proceed because of significant differences in my dfocc and the one in the psi4. 

Now, how I can reach that repo?  Because I need to slightly modify my tensor class. Further, I will add a new UHF-DF-CCSD code soon. Hence, before it I would like to synchronize my code with the public repo.

@loriab

**Comment by loriab** [comment]
Thanks, @bozkaya, I'm glad you'll have a chance to work on it. You can use standard `git` to access the branch. From a local clone, make sure my fork is a remote (analogous to "alex" below). If not, then `git remote add loriab https://github.com/loriab/psi4.git`. Then pull down the branch with `git fetch loriab ugurfno`. Then check out the branch with `git checkout ugurfno`, and "make dfocc fno defaults match fnocc" should be the top commit in `git log`. Proceed with normal development, and push to your account `git push origin ugurfno`. You can either open a new PR to psi4 master from there (to replace this PR) or open a PR to loriab ugurfno (to continue this PR).

```
>>> git remote -v
alex	https://github.com/AlexHeide/psi4.git (fetch)
alex	https://github.com/AlexHeide/psi4.git (push)
origin	https://github.com/loriab/psi4.git (fetch)
origin	https://github.com/loriab/psi4.git (push)
upstream	https://github.com/psi4/psi4.git (fetch)
upstream	https://github.com/psi4/psi4.git (push)
```

**Comment by bozkaya** [comment]
Hi Lori,

Thank you very much for your help. I have updated my tensor class. Further, I have added delte-MP2 corrections to the energy of the method, hence it is saved to PsiVar now. I think, you may add it public repo now. However, when try to make a push I got the following error:

remote: Permission to loriab/psi4.git denied to bozkaya.
fatal: unable to access 'https://github.com/loriab/psi4.git/': The requested URL returned error: 403

As I understand you should allow me to push my changes.

Let me know if we need anything else. @loriab

**Comment by loriab** [comment]
@bozkaya, great, thanks!  If you don’t mind, please push your branch to your fork (perhaps already done), then make a PR to my branch (choose “loriab/psi4” instead of usual “psi4/psi4” and “ugurfno” instead of usual “master” on the left hand side of the four-drop down PR form)..

**Comment by bozkaya** [comment]
@loriab Thank you for the information. I have made a PR to your branch ugurfno.

**Comment by loriab** [comment]
Thanks for [the PR](https://github.com/loriab/psi4/pull/8), @bozkaya. Unfortunately, it (1) contains commits from authors other than yourself, indicating that the branch isn't based off loriab:ugurfno and (2) the final commit, which should contain just your changes from this week, shows over 3k files and 1M LOC changed. This is seriously wrong and probably not worth trying to recover from.

Perhaps start over with [these directions](https://github.com/psi4/psi4/pull/1390#issuecomment-444903155). Get my branch and add your changes. The commits tab in the PR to me should be one or a few commits solely by you from this week, and the LOC diffs should be in the hundreds (or low thousands if you add many tests). Psi uses ordinary git and the PR workflow, so internet resources and [our resources](http://psicode.org/psi4manual/master/build_obtaining.html#faq-githubworkflow) are available.

**Comment by bozkaya** [comment]
Hi Lori,

I am sorry that I am really confused. How about this, I send you the dfocc module, you add it to the present psi4. Then, I will update my psi4 and my fork and proceed as usual. If it is okay for you I will send the whole module as a zip file to you via e-mail. @loriab

**Comment by loriab** [comment]
Hi @bozkaya, glad you're continuing to work on this. I worry that we're combining too many things here. I can see that saving the deltaMP2 energies are relevant to getting the FNO energies working, but changes to the tensor class and UHF-DF-CCSD perhaps are not. 

For the latter two, I suggest a separate PR. If you send git patches of the commits where you added those features/fixes (can add `.patch` to end of GH commit view like https://github.com/psi4/psi4/commit/28caec54bff4a0ef39f01269cb94a930f6bd7223.patch or can do on the command line, https://stackoverflow.com/questions/6658313/generate-a-git-patch-for-a-specific-commit), I can get that PR started for you. The changes in those diffs/patches should be new work on, for example, the tensor class, not historical changes.

For this PR, mainly what's needed are the deltaMP2 changes (again, if you'll send a patch, I'll add it to this PR) and tests. For the tests, it'll be straightforward to start from this branch and add new files.

**Comment by JonathonMisiewicz** [comment]
Reminder that we decided on the conf. call that this should not be a 1.4 target.

**Comment by JonathonMisiewicz** [comment]
Nearly 3(!) years later, this PR will itself need to be replaced due to other developments in `dfocc`. Maybe by #2354, maybe not. Either way, PR closed.

**Pull request closed without merging**
