### PR TITLE
Pubchem Py3fix

### PR DESCRIPTION
**Pull request by andysim**
## Description
Uses the [new RESTful interface](https://pubchem.ncbi.nlm.nih.gov/pug_rest/PUG_REST.html#_Toc458584218) to get PubChem hits.
## Todos
Notable points that this PR has either accomplished or will accomplish.
- [x] Fixes PubChem tests with Python 3

## Status
- [x]  Ready to go

### CODE REVIEW

**Comment by andysim** [comment]
Doh, I forgot to add `--rebase` when I merged in master, yet again.  I suck.

**Comment by dgasmith** [comment]
+1 for REST and JSON simplifications!

**Comment by loriab** [comment]
Yay, nesting levels reduced from 10 to 5 :-) . And I'm reassured to see "3d" in there. Looks like we're not doing wait-and-repeat anymore, but `MaxSeconds` available if travis habitually times out.

LGTM

**Comment by andysim** [comment]
Yeah, it seems like the simple REST interface doesn't require a queue for simple tasks; substructure searches and conformer stuff seems to generate a ticket, as before.  I learned all I know from scanning the document linked above, so I'm far from an expert.  I did a little testing with both Python versions and it *seems* to be ok.

**Comment by dgasmith** [comment]
LGTM

**Comment by amjames** [comment]
LGTM

**Pull request merged**
