### PR TITLE
Removed the VERSION file to avoid confusion.  Resolves #271.

### LINKED ISSUE #271: VERSION file contents
I just noticed that the VERSION file in the root directory contains "4.0", which is not consistent with @loriab's proposed version number system.  It looks like @robertodr added it when he did all that great work with CMake, so perhaps it's used to generate some info for the dashboard?  Either way, I think it should probably be brought into line with the new versioning scheme.

### PR DESCRIPTION
**Pull request by andysim**
## Description

Just removes the VERSION file, because the information is already contained in CMake's configuration files.

## Todos
Notable points that this PR has either accomplished or will accomplish.
- [x] Gets rid of the superfluous VERSION file.
- [x] Allows me to see how the new template and contributing files work in practice.

## Status
- [x]  Ready to go

### CODE REVIEW

**Comment by dgasmith** [comment]
How did the PR template work out for you?

**Comment by andysim** [comment]
It's great!  I'm an idiot, and forgot to remove all references to the VERSION file from the CMake stuff.  Oops.

**Comment by andysim** [comment]
OK, I nuked all references to ConfigVersion because, as I understand, gitversion.py replaces it.  The code is building now, but we should make sure it all links properly before merging.  Also, I'd like @loriab to confirm that I haven't done something stupid, before we accept the PR.

**Comment by loriab** [comment]
It looks good so far as I can predict.

**Comment by CDSherrill** [comment]
We don't pull VERSION into the manual somewhere do we?

**Comment by loriab** [comment]
It's fine, the docs use `gitversion.h`, too. See https://github.com/psi4/psi4/blob/master/doc/sphinxman/source/conf.py.in#L58

**Comment by loriab** [comment]
This is pretty simple, so merging. Docs-build tonight will validate harmlessness of removal.

**Comment by andysim** [comment]
Did I screw up the docs at all, @loriab?  If so, I'll fix them today.

**Comment by loriab** [comment]
Nope, they're fine! I did break the install by adding an install rule to the optional psi4so target, but that's unrelated, and I've got a fix in the works.

**Pull request merged**
