### PR TITLE
Tdscf excitations symmetry

### PR DESCRIPTION
**Pull request by lazaroid**
## Description
Adds contributing excitations to tdscf output for non-C1 symmetry.

## Checklist
- [x] [All or relevant fraction of full tests run](http://psicode.org/psi4manual/master/build_planning.html#how-to-run-a-subset-of-tests)

## Status
- [x] Ready for review
- [x] Ready for merge

### CODE REVIEW

**Comment by lazaroid** [comment]
Gah! I didn't know about the pytest test cases (the standard tdscf-n set ran OK, somewhat surprisingly). A standard copy-paste and then missing one part that needed changing! I've corrected it.

My version of pytest is too old to run the tests (apparently) but extracting the various bits out of the pytest file and running that as a standard input file worked OK.

**Comment by lazaroid** [comment]
I think that should have done the trick. (I ran the tdscf tests and then overwrote the respective output.ref files with the generated output.dat files.) I think the only differences are numerical errors during SCF and then formatting of the output. All final results should be unchanged.

**Review by JonathonMisiewicz — APPROVED** [review]
Many thanks!

**Review by loriab — APPROVED** [review]
lgtm, thanks!

**Review by jturney — APPROVED** [review]

**Pull request merged**
