### PR TITLE
Fix #2875: remove cached `nmo_` var

### LINKED ISSUE #2875: Don't Cache `nmo_`
[Some users who are using `clone` to change the number of orbitals report that `nmo_` doesn't update and request a way to change `nmo_`.](https://forum.psicode.org/t/reallocation-of-matrix-object-ca-with-new-matrix-of-different-dimension/2720/3?u=jmisiewicz) Ideally, `nmo()` should be `nmopi_.sum()`, and the `nmo_` variable no longer stored. This eliminates a possible internal inconsistency, and on the scale of other operations, the store/compute time savings are negligible.

### PR DESCRIPTION
**Pull request by mniverthi**
## Description

Refactored code in the WaveFunction class as per #2875

## User API & Changelog headlines

- [ ] No changes to user experience

## Dev notes & details

- [ ] Removed `nmo_` cache variable in favor of `nmopi_.sum()` to keep things in sync
- [ ] Refactored code to reflect removal of variable

## Questions
- [ ] Best ways to test this change?

## Checklist
- [ ] [All or relevant fraction of full tests run](http://psicode.org/psi4manual/master/build_planning.html#how-to-run-a-subset-of-tests)

## Status
- [ ] Ready for review
- [ ] Ready for merge

#2875

### CODE REVIEW

**Comment by JonathonMisiewicz** [comment]
Thanks for the contribution.

Have you built this modified version of Psi locally? When our test suite tries to build it, it doesn't work. That's the first step in testing.

**Comment by mniverthi** [comment]
Was able to build locally, pipeline (up to ctest) ran successfully. There were issues on pytest, but it seems like these issues have to do with missing packages, so I'm not sure how to address issues there. Any advice would be helpful

**Comment by loriab** [comment]
I see we have a plugin error here https://dev.azure.com/psi4/psi4/_build/results?buildId=5535&view=logs&j=f237aa60-f90a-5f4e-46d5-6f838a77d991&t=e678ab3d-f7fc-50f0-56d8-3349f4950165&l=9304 . That's very possibly pre-existing -- I should have retained skeletons in ctest when I deduplicated the ctest and pytest calls.

The "missing packages" link doesn't work for me. What is the text? Does running the `test_sapt_dft1` test in particular work for you locally?

**Comment by mniverthi** [comment]
Fixed the link in the original comment, also adding it here: https://dev.azure.com/psi4/psi4/_build/results?buildId=5535&view=logs&j=f237aa60-f90a-5f4e-46d5-6f838a77d991&t=4577f1f3-bc89-5040-5cf1-0f1c10ea6889&l=4843

**Comment by loriab** [comment]
A skipped test is not a problem -- the CI environment or resources constraints preclude running the test, so it's skipped. The failure above that of `dft_sapt1` is a problem https://dev.azure.com/psi4/psi4/_build/results?buildId=5535&view=logs&j=f237aa60-f90a-5f4e-46d5-6f838a77d991&t=4577f1f3-bc89-5040-5cf1-0f1c10ea6889&l=4664 so a good first debugging step is to try it locally.

**Comment by mniverthi** [comment]
I'm a bit confused about how to debug the test locally and also wanted to clarify my understanding of what is going on in the test. If I understand correctly, the test takes the `input.dat` file in`tests/sapt-dft1` and runs it through the built version of psi. Once this is done, it checks that there is nothing in `stdout` or `stderr` (as per line 230 of `tests/pytests/addons.py`) and that the test ran through successfully.

I've been using this as a general guide for setting stuff up and running tests, but I'm not sure exactly how everything fits together.

**Pull request closed without merging**
