### PR TITLE
fmt: clang-format FNOCC module

### PR DESCRIPTION
**Pull request by loriab**
## Description
fmt: clang-format FNOCC module

## Questions
- [ ] If merging this PR will hinder your research b/c you have local edits, protest here or in #1144

## Status
- [x] Ready for review
- [x] Ready for merge

### CODE REVIEW

**Comment by loriab** [comment]
fyi, @edeprince3

**Comment by edeprince3** [comment]
Yes, I just was looking at this - what is being changed?  It just looks like changes to whitespace, to me.

**Comment by loriab** [comment]
Right, this is purely a formatting pass (see #1144) according to the [clang-format file](https://github.com/psi4/psi4/blob/master/.clang-format). If you'd like to do it yourself to avoid disrupting authorship, just `clang-format -i *.h *.cc` in the fnocc directory.

**Comment by edeprince3** [comment]
No, no, no go ahead!  This is fine with me.

**Pull request merged**
