### PR TITLE
interfragment optimizations with 3 test cases

### PR DESCRIPTION
**Pull request by psi-rking**
## Description
Fixed incorrect B matrix for 'interfragment coordinates'.  These coordinates are not used by default, but the user can specify them to create very specific coordinates.  They may be useful, e.g., in combination with 'freeze_intrafrag' for fixed-body optimizations.

When symmetry is turned on, there is a difficulty with the symmetry detection in combination with the way in which the displacements are carried out for these coordinates.  A loosening of the symmetry tolerance when computing the symmetrized geometry usually works and has been implemented.  In the future, it may be best to carry out the displacements in these coordinates iteratively and numerically as they are for redundant intrafrag coordinates.  However, this approach would be more hazardous with no upside in C1, and I don't have time to implement it right now anyway.

- [ ] Feature1
Reference atoms can now be specified by the user with a standard multi-dimensional python list.  The test cases illustrate this.  Probably, this utility will stimulate more use cases for further development of the code.

## Questions
- [ ]  Question1

## Status
- [X]  Ready to go
All tests, including the 3 new ones pass for me.

### CODE REVIEW

**Comment by dgasmith** [comment]
Cool, this should give us a base to start playing around with automatic rigid body optimizations. 

Also note you can do `git pull --rebase upstream master` to rebase in the master branch of upstream. This will help cut down on the number of merges that happen. You can always fall back to merging if needed of course.

**Comment by psi-rking** [comment]
Thanks, will do in the future.  Let me know if/when you hit snags using
this tool.  It think it is far enough along that I should be able to solve
problems.
-Rollin

**Comment by dgasmith** [comment]
Sounds great. Update the branch and I'll pull this in.

**Comment by loriab** [comment]
Um, the commit history in this PR really shouldn't look like that. In most cases, this included, it should consist entirely of _your_ commits. 

Fortunately, I think we can do the same thing as with the backtransformation PR https://github.com/psi4/psi4/pull/406#issuecomment-225041174 that was in a similar state. You can do exactly the commands in the first paragraph of that comment (rename `labsandbox` if you prefer). Then issue a separate PR on the github website from that new, rebased branch. I expect that one will be in good shape with only your commits, so we'll accept that one and close out this one.

**Comment by psi-rking** [comment]
OK, I am trying to rebase.  So far, I seem to have only made a mess of
things locally.
-Rollin

**Pull request closed without merging**
