### PR TITLE
fix molden and nbody conv tests

### PR DESCRIPTION
**Pull request by loriab**
## Description

fixes a couple full tests. with these and the ones Jonathon fixed, full tests should be clean again.

## Todos

- [x] the nbody-vmfc-hessian has one element of value 0.85 above reference by 1.2e-8 caused by adiis. not a big deal, so convcrit loosened from 1e-8 to 2e-8.
- [x] the new molden writer tests are nicely structured, but they use r_convergence=12 a lot for SCF, which doesn't tighten the criteria for SCF. so the new adiis tipped one test over the failure limit. (see below the original (r_conv=12) and tight (e_conv=12) SCF cycles w/ diis and adiis.) I've regenerated the reference molden.refs with e_convergence 12 and plain diis, then relaxed the convergence for normal running. no trouble with adiis. sound ok, @sgoodlett?
- [ ] @hokru, on the new dft_blocking_schemes test, I'm getting `OCTREE GRID POINTS:: computed value (293260.0) does not match (293259) by difference (1.0).` Is it reasonable to test for 293259 +/- 2 or so?

```

                        Total Energy        Delta E     RMS |[F,P]|

   @RHF iter SAD:  -672.15146809832379   -6.72151e+02   0.00000e+00
   @RHF iter   1:  -672.63084564264716   -4.79378e-01   9.00814e-03 DIIS
   @RHF iter   2:  -672.71442224758289   -8.35766e-02   5.30043e-03 DIIS
   @RHF iter   3:  -672.74379684057214   -2.93746e-02   5.52535e-04 DIIS
   @RHF iter   4:  -672.74452788784220   -7.31047e-04   1.91489e-04 DIIS
   @RHF iter   5:  -672.74459677446487   -6.88866e-05   5.52833e-05 DIIS
   @RHF iter   6:  -672.74460689141483   -1.01169e-05   1.01025e-05 DIIS
   @RHF iter   7:  -672.74460730536885   -4.13954e-07   1.76374e-06 DIIS
   @RHF iter   8:  -672.74460731378190   -8.41305e-09   7.61045e-07 DIIS
  Energy and wave function converged.

   @RHF iter SAD:  -672.15146809832379   -6.72151e+02   0.00000e+00
   @RHF iter   1:  -672.63084564264716   -4.79378e-01   9.00814e-03 DIIS
   @RHF iter   2:  -672.71442224758289   -8.35766e-02   5.30043e-03 DIIS
   @RHF iter   3:  -672.74379684057214   -2.93746e-02   5.52535e-04 DIIS
   @RHF iter   4:  -672.74452788784220   -7.31047e-04   1.91489e-04 DIIS
   @RHF iter   5:  -672.74459677446487   -6.88866e-05   5.52833e-05 DIIS
   @RHF iter   6:  -672.74460689141483   -1.01169e-05   1.01025e-05 DIIS
   @RHF iter   7:  -672.74460730536885   -4.13954e-07   1.76374e-06 DIIS
   @RHF iter   8:  -672.74460731378190   -8.41305e-09   7.61045e-07 DIIS
   @RHF iter   9:  -672.74460731474380   -9.61904e-10   2.09614e-07 DIIS
   @RHF iter  10:  -672.74460731487704   -1.33241e-10   6.64041e-08 DIIS
   @RHF iter  11:  -672.74460731489182   -1.47793e-11   1.26692e-08 DIIS
   @RHF iter  12:  -672.74460731489194   -1.13687e-13   2.66098e-09 DIIS
   @RHF iter  13:  -672.74460731489341   -1.47793e-12   6.52605e-10 DIIS
   @RHF iter  14:  -672.74460731489307    3.41061e-13   2.24066e-10 DIIS
   @RHF iter  15:  -672.74460731489285    2.27374e-13   6.54131e-11 DIIS
   @RHF iter  16:  -672.74460731489262    2.27374e-13   2.00408e-11 DIIS
   @RHF iter  17:  -672.74460731489285   -2.27374e-13   4.36522e-12 DIIS
   @RHF iter  18:  -672.74460731489307   -2.27374e-13   1.26829e-12 DIIS
   @RHF iter  19:  -672.74460731489410   -1.02318e-12   2.71243e-13 DIIS
   @RHF iter  20:  -672.74460731489353    5.68434e-13   7.18233e-14 DIIS
  Energy and wave function converged.

   @RHF iter SAD:  -672.15146809832379   -6.72151e+02   0.00000e+00
   @RHF iter   1:  -672.63084564264716   -4.79378e-01   9.00814e-03 ADIIS/DIIS
   @RHF iter   2:  -672.71442224758289   -8.35766e-02   5.30043e-03 ADIIS/DIIS
   @RHF iter   3:  -672.74373946371918   -2.93172e-02   6.13615e-04 ADIIS/DIIS
   @RHF iter   4:  -672.74452727814617   -7.87814e-04   1.92071e-04 ADIIS/DIIS
   @RHF iter   5:  -672.74459671900468   -6.94409e-05   5.54299e-05 DIIS
   @RHF iter   6:  -672.74460689054501   -1.01715e-05   1.01141e-05 DIIS
   @RHF iter   7:  -672.74460730521071   -4.14666e-07   1.79146e-06 DIIS
   @RHF iter   8:  -672.74460731376098   -8.55027e-09   7.54369e-07 DIIS
  Energy and wave function converged.

   @RHF iter SAD:  -672.15146809832379   -6.72151e+02   0.00000e+00
   @RHF iter   1:  -672.63084564264716   -4.79378e-01   9.00814e-03 ADIIS/DIIS
   @RHF iter   2:  -672.71442224758289   -8.35766e-02   5.30043e-03 ADIIS/DIIS
   @RHF iter   3:  -672.74373946371918   -2.93172e-02   6.13615e-04 ADIIS/DIIS
   @RHF iter   4:  -672.74452727814617   -7.87814e-04   1.92071e-04 ADIIS/DIIS
   @RHF iter   5:  -672.74459671900468   -6.94409e-05   5.54299e-05 DIIS
   @RHF iter   6:  -672.74460689054501   -1.01715e-05   1.01141e-05 DIIS
   @RHF iter   7:  -672.74460730521071   -4.14666e-07   1.79146e-06 DIIS
   @RHF iter   8:  -672.74460731376098   -8.55027e-09   7.54369e-07 DIIS
   @RHF iter   9:  -672.74460731474016   -9.79185e-10   2.16800e-07 DIIS
   @RHF iter  10:  -672.74460731487568   -1.35515e-10   7.07155e-08 DIIS
   @RHF iter  11:  -672.74460731489148   -1.58025e-11   1.29083e-08 DIIS
   @RHF iter  12:  -672.74460731489262   -1.13687e-12   2.70093e-09 DIIS
   @RHF iter  13:  -672.74460731489307   -4.54747e-13   6.42115e-10 DIIS
   @RHF iter  14:  -672.74460731489330   -2.27374e-13   2.02808e-10 DIIS
   @RHF iter  15:  -672.74460731489262    6.82121e-13   6.57895e-11 DIIS
   @RHF iter  16:  -672.74460731489239    2.27374e-13   1.98299e-11 DIIS
   @RHF iter  17:  -672.74460731489273   -3.41061e-13   4.17600e-12 DIIS
   @RHF iter  18:  -672.74460731489296   -2.27374e-13   1.20666e-12 DIIS
   @RHF iter  19:  -672.74460731489376   -7.95808e-13   2.59222e-13 DIIS
  Energy and wave function converged.
```

## Checklist
- [ ] ~Tests added for any new features~
- [x] [All or relevant fraction of full tests run](http://psicode.org/psi4manual/master/build_planning.html#how-to-run-a-subset-of-tests)

## Status
- [x] Ready for review
- [x] Ready for merge

### CODE REVIEW

**Review by JonathonMisiewicz — APPROVED** [review]
Using `r_convergence` was my bad: I've spent so long in other modules that I forgot it's `d_convergence` for SCF.

**Review by maxscheurer — APPROVED** [review]

**Comment by loriab** [comment]
ok, the `dft_blocking_schemes` error only appears with a new l2, so for now this PR is good to go.

**Review by hokru — APPROVED** [review]

**Comment by hokru** [comment]
Instead of testing for +-2 a one could add `"DFT_WEIGHTS_TOLERANCE": -1.0` to the pytest (with new reference values) to remove numerical issues. In case the issue appears again.

**Comment by loriab** [comment]
> Instead of testing for +-2 a one could add "DFT_WEIGHTS_TOLERANCE": -1.0 to the pytest (with new reference values) to remove numerical issues. In case the issue appears again.

grand idea! I've done it here https://github.com/psi4/psi4/pull/2413/files#diff-ae2f922962c992ce2cab616a14af6da28727b696abada7f8b1c6f92bfd2cb4de

**Pull request merged**
