### PR TITLE
Unpin MKL for Windows builds

### PR DESCRIPTION
**Pull request by raimis**
## Description
This is part of *Psi4* porting to Windows (#933).

Some time ago (#1240), MKL version had to be pinned for Windows builds. Now it is fixed and the latest version could be used.

## Todos
Notable points (developer or user-interest) that this PR has or will accomplish.
- [x] Unpin MKL version

## Checklist
- [x] ~~Tests added for any new features~~
- [x] [All or relevant fraction of full tests run](http://psicode.org/psi4manual/master/build_planning.html#how-to-run-a-subset-of-tests)

## Status
- [ ] Ready for review
- [ ] Ready for merge

### CODE REVIEW

**Comment by raimis** [comment]
Don't merge! It seems there is still some problem with `intel-openmp` package. Need to check...

**Comment by andysim** [comment]
I'm not sure if it's related but I just ran a conda upgrade an a fresh, clean anaconda install, and this happened:
```
QuickSilver:~ > conda update --prefix /Users/andysim/anaconda3 anaconda
Solving environment: done

## Package Plan ##

  environment location: /Users/andysim/anaconda3

  added / updated specs: 
    - anaconda


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    mkl-2018.0.3               |                1       149.2 MB

The following packages will be DOWNGRADED:

    mkl: 2019.0-118 --> 2018.0.3-1
```
Maybe this means that there's a known problem with mkl2019 and it's being rolled back?

**Comment by raimis** [comment]
Yes, `numpy` force downgrade of `mkl`, but not `intel-openmp`.

**Comment by loriab** [comment]
I have seen something about mkl and Windows and 2018/2019 compatibility recently but of course can't find it now. I don't recall it as alarming, so if this PR has worked in practice, LGTM. Has @raimis definitely lifted the "Don't merge" directive (too many slack messages flying around)? Avoiding checkmark until confirmed so we're not merge-happy.

**Comment by raimis** [comment]
@loriab, I haven't had time to look at this recently. I hope, eventually, MKL package will be fixed.

**Comment by loriab** [comment]
@raimis, ok to push to v1.4 milestone?

**Comment by raimis** [comment]
Yes, it could be move to v1.4! Meanwhile, I'll try if any new changes.

**Comment by raimis** [comment]
This was obsoleted by #1571

**Pull request closed without merging**
