### PR TITLE
Fix some issues with ERD

### PR DESCRIPTION
**Pull request by bennybp**
## Description
Fixes some of the issues with ERD in Psi4

Moves a piece of the normalization from ERD to Psi4. This prevents multiplication by zero inside ERD, which results in incorrect integral values.

Note that the multiplication by zero doesn't happen in Psi4, as the normalization routine doesn't get called for a "zero" basis set (ie, in density fitting).

**Warning** I don't know how well-tested ERD in Psi4 is. I still get some failing tests, although there is certainly an improvement from before. Ideas for why this might be are welcome.

## Status
- [ ]  Ready to go

### CODE REVIEW

**Comment by loriab** [comment]
Was gdma1 one of the tests you expected to fail with erd, Ben? I just saw an oddity with it myself where it runs fine explicitly but through ctest issues a string truncated error and gives up (but does not fail).

**Comment by bennybp** [comment]
I haven't tested with gdma. You mean you see this behavior with this PR?

I wouldn't "expect" any of the tests to fail (erd should more or less be a drop-in replacement for libint). But, at least for me, but many tests still fail.

**Comment by loriab** [comment]
gdma1 is the test that's failing on Travis. (For once, timeout is not at fault.)

**Comment by bennybp** [comment]
I just pushed some changes that make most of the tests pass for me (at least the ones that have run so far). I will run a more complete set and let you know how it goes

**Comment by bennybp** [comment]
These tests are still failing with erd. Maybe I wasn't too clear before, but these are what fail when I set integral_package to erd in my psi4rc file. 

 12 - cbs-xtpl-freq (Failed)
114 - dfccd-grad1 (Failed)
117 - dfccsd-grad1 (Failed)
122 - dfmp2-3 (Failed)
124 - dfmp2-grad1 (Failed)
125 - dfmp2-grad2 (Failed)
126 - dfmp2-grad3 (Failed)
127 - dfmp2-grad4 (Failed)
132 - dfomp2-grad1 (Failed)
133 - dfomp2-grad2 (Failed)
136 - dfomp3-grad1 (Failed)
137 - dfomp3-grad2 (Failed)
140 - dfomp2p5-grad1 (Failed)
141 - dfomp2p5-grad2 (Failed)
146 - dft-freq (Failed)
147 - dft-grad (Failed)
151 - dft1 (Failed)
152 - dft1-alt (Failed)
154 - dft3 (Failed)
157 - extern1 (Failed)
165 - fd-freq-energy-large (Failed)
168 - fd-gradient (Failed)
188 - mints9 (Failed)
196 - mp2-module (Failed)
229 - opt-lindep-change (Failed)
237 - opt6 (Failed)
238 - opt7 (Failed)
239 - opt8 (Failed)
240 - opt9 (Failed)
241 - opt11 (Failed)
242 - opt12 (Failed)
243 - opt13 (Timeout)
245 - opt-irc-1 (Failed)
246 - opt-irc-2 (Failed)
247 - opt_freeze_coords (Failed)
261 - pubchem1 (Failed)
268 - pywrap-checkrun-rhf (Failed)
269 - pywrap-checkrun-rohf (Failed)
270 - pywrap-checkrun-uhf (Failed)
272 - pywrap-db2 (Failed)
309 - tu3-h2o-opt (Failed)
310 - tu4-h2o-freq (Failed)
322 - cubeprop-esp (Failed)

**Comment by loriab** [comment]
You've noticed that gradients or omega/long-range-corrected functionals are a common thread among the failing tests? The mp2-module test might be helpful for debugging as it's running mp2 variations in all the different mp2-capable modules. When I comment out the failing compare_matrices statements so that it all passes, you'll see that the conventional (4-lines pass blocks below) gradients are working while the df (3-lines pass (1-line commented out) blocks below) are failing in both dfocc and dfmp2 modules. Does that help any?

```
	mp2 rhf conv: 3 occ*..............................................PASSED
	mp2 rhf conv: 3 occ*..............................................PASSED
...
*** mp2 energies all pass ***
...
	mp2 grad rhf conv nfc: 1 occ*.....................................PASSED
	mp2 grad rhf conv nfc: 1 occ*.....................................PASSED
	mp2 grad rhf conv nfc: 1 occ*.....................................PASSED
	mp2 grad rhf conv nfc: 1 occ*.....................................PASSED
	mp2 grad rhf df fc: 2 occ.........................................PASSED
	mp2 grad rhf df fc: 2 occ.........................................PASSED
	mp2 grad rhf df fc: 2 occ.........................................PASSED
	mp2 grad rhf df fc: 2 dfmp2*......................................PASSED
	mp2 grad rhf df fc: 2 dfmp2*......................................PASSED
	mp2 grad rhf df fc: 2 dfmp2*......................................PASSED
	mp2 grad rhf df nfc: 2 occ........................................PASSED
	mp2 grad rhf df nfc: 2 occ........................................PASSED
	mp2 grad rhf df nfc: 2 occ........................................PASSED
	mp2 grad rhf df nfc: 2 dfmp2*.....................................PASSED
	mp2 grad rhf df nfc: 2 dfmp2*.....................................PASSED
	mp2 grad rhf df nfc: 2 dfmp2*.....................................PASSED
	mp2 grad uhf conv nfc: 1 occ*.....................................PASSED
	mp2 grad uhf conv nfc: 1 occ*.....................................PASSED
	mp2 grad uhf conv nfc: 1 occ*.....................................PASSED
	mp2 grad uhf conv nfc: 1 occ*.....................................PASSED
	mp2 grad uhf df fc: 1 occ*........................................PASSED
	mp2 grad uhf df fc: 1 occ*........................................PASSED
	mp2 grad uhf df fc: 1 occ*........................................PASSED
	mp2 grad uhf df nfc: 1 occ*.......................................PASSED
	mp2 grad uhf df nfc: 1 occ*.......................................PASSED
	mp2 grad uhf df nfc: 1 occ*.......................................PASSED
Performing finite difference calculations
 13 displacements needed ... 1 2 3 4 5 6 7 8 9 10 11 12 13
	mp2 grad rohf df nfc: findif......................................PASSED
...
*** findif gradient passes ***
```

**Comment by loriab** [comment]
##### Summary

With a couple changes, as below, I think this can be ready to go.

##### Testing Setup

* in `~/.psi4rc`: `psi4.set_global_option("INTEGRAL_PACKAGE", "ERD")`
* in `psi4/driver/driver.py`: the catch from the section below, only with `sys.exit(0)` to force smooth exit from test, rather than the ValidationError
* Under these conditions, only the below fail from full tests. Ignoring the can't-find-exe, the known-failures, and the sow/reap, the ailing test cases involved either LRC functionals or ESP.
```
The following tests FAILED:
	151 - dft1 (Failed)
	152 - dft1-alt (Failed)
	154 - dft3 (Failed)
	188 - mints9 (Failed)
	272 - pywrap-db2 (Failed)
	275 - pywrap-freq-g-sowreap (Failed)
	322 - cubeprop-esp (Failed)
	333 - dftd3-version (Failed)
	341 - mrcc-ccsdt (Failed)
	342 - mrcc-ccsd_t_ (Failed)
	343 - mrcc-ccsdt_q_ (Failed)
	344 - mrcc-optfreq (Failed)
Errors while running CTest
```

##### Recc. TODO

* In main CM, change erd warning to `    message(WARNING "ERD will build, link, and run in Psi4 just fine. However, it has not been hooked into Psi4 in all roles, notably gradients, LRC DFT energies, and ESP. So upon activating through ``set integral_package erd``, gradients will be caught and halted, but LRC DFT, ESP, and perhaps other types not tested and identified will give *wrong* answers. Consider this your warning.")`

* In `psi4/driver/driver.py`, apply patch below

```
--- a/psi4/driver/driver.py
+++ b/psi4/driver/driver.py
@@ -82,6 +82,9 @@ def _find_derivative_type(ptype, method_name, user_dertype):
             raise ValidationError("_find_derivative_type: user_dertype should only be None or int!")
         dertype = user_dertype
 
+    if (core.get_global_option('INTEGRAL_PACKAGE') == 'ERD') and (dertype != 0):
+        raise ValidationError("INTEGRAL_PACKAGE ERD does not play nicely with gradients, so stopping.")
+
     # Summary validation
     if (dertype == 2) and (method_name in procedures['hessian']):
         pass
```

* Running this yield the following list (30% failure rate).
```
The following tests FAILED:
	 12 - cbs-xtpl-freq (Failed)
	 13 - cbs-xtpl-gradient (Failed)
	 14 - cbs-xtpl-opt (Failed)
	 16 - cbs-xtpl-wrapper (Failed)
	 17 - cc1 (Failed)
	 21 - cc13 (Failed)
	 22 - cc13a (Failed)
	 23 - cc14 (Failed)
	 30 - cc21 (Failed)
	 32 - cc23 (Failed)
	 33 - cc24 (Failed)
	 34 - cc25 (Failed)
	 35 - cc26 (Failed)
	 36 - cc27 (Failed)
	 39 - cc3 (Failed)
	 78 - cepa0-grad1 (Failed)
	 79 - cepa0-grad2 (Failed)
	 95 - dcft-grad1 (Failed)
	 96 - dcft-grad2 (Failed)
	 97 - dcft-grad3 (Failed)
	 98 - dcft-grad4 (Failed)
	103 - dcft5 (Failed)
	114 - dfccd-grad1 (Failed)
	117 - dfccsd-grad1 (Failed)
	122 - dfmp2-3 (Failed)
	124 - dfmp2-grad1 (Failed)
	125 - dfmp2-grad2 (Failed)
	126 - dfmp2-grad3 (Failed)
	127 - dfmp2-grad4 (Failed)
	132 - dfomp2-grad1 (Failed)
	133 - dfomp2-grad2 (Failed)
	136 - dfomp3-grad1 (Failed)
	137 - dfomp3-grad2 (Failed)
	140 - dfomp2p5-grad1 (Failed)
	141 - dfomp2p5-grad2 (Failed)
	146 - dft-freq (Failed)
	147 - dft-grad (Failed)
	151 - dft1 (Failed)
	152 - dft1-alt (Failed)
	154 - dft3 (Failed)
	157 - extern1 (Failed)
	165 - fd-freq-energy-large (Failed)
	166 - fd-freq-gradient (Failed)
	167 - fd-freq-gradient-large (Failed)
	168 - fd-gradient (Failed)
	169 - freq-isotope (Failed)
	171 - fnocc2 (Failed)
	176 - gibbs (Failed)
	188 - mints9 (Failed)
	192 - mp2-1 (Failed)
	194 - mp2-grad1 (Failed)
	195 - mp2-grad2 (Failed)
	196 - mp2-module (Failed)
	197 - mp2_5-grad1 (Failed)
	198 - mp2_5-grad2 (Failed)
	199 - mp3-grad1 (Failed)
	200 - mp3-grad2 (Failed)
	206 - ocepa-grad1 (Failed)
	207 - ocepa-grad2 (Failed)
	216 - omp2-grad1 (Failed)
	217 - omp2-grad2 (Failed)
	220 - omp2_5-grad1 (Failed)
	221 - omp2_5-grad2 (Failed)
	227 - omp3-grad1 (Failed)
	228 - omp3-grad2 (Failed)
	229 - opt-lindep-change (Failed)
	230 - opt1 (Failed)
	232 - opt2 (Failed)
	233 - opt2-fd (Failed)
	234 - opt3 (Failed)
	235 - opt4 (Failed)
	236 - opt5 (Failed)
	237 - opt6 (Failed)
	238 - opt7 (Failed)
	239 - opt8 (Failed)
	240 - opt9 (Failed)
	241 - opt11 (Failed)
	242 - opt12 (Failed)
	243 - opt13 (Failed)
	244 - opt14 (Failed)
	245 - opt-irc-1 (Failed)
	246 - opt-irc-2 (Failed)
	247 - opt_freeze_coords (Failed)
	261 - pubchem1 (Failed)
	263 - pywrap-alias (Failed)
	264 - pywrap-all (Failed)
	268 - pywrap-checkrun-rhf (Failed)
	269 - pywrap-checkrun-rohf (Failed)
	270 - pywrap-checkrun-uhf (Failed)
	272 - pywrap-db2 (Failed)
	275 - pywrap-freq-g-sowreap (Failed)
	301 - scf6 (Failed)
	309 - tu3-h2o-opt (Failed)
	310 - tu4-h2o-freq (Failed)
	322 - cubeprop-esp (Failed)
	331 - dftd3-grad (Failed)
	333 - dftd3-version (Failed)
	341 - mrcc-ccsdt (Failed)
	342 - mrcc-ccsd_t_ (Failed)
	343 - mrcc-ccsdt_q_ (Failed)
	344 - mrcc-optfreq (Failed)
Errors while running CTest
```

**Comment by loriab** [comment]
@bennybp, the coefficients array for the FCHK file has changed (see below) even with integrals_package libint. Key area is [here](https://github.com/psi4/psi4/blob/master/psi4/src/psi4/libmints/writer.cc#L788-L794), I'd think. Once this is fixed, I think these ERD PRs can go through. FYI, @andysim 

```
Contraction coefficients                   R   N=          42						Contraction coefficients                   R   N=          42
  5.20198307e-04  4.02334478e-03  2.07290833e-02  8.10823271e-02  2.36226352e-01		   |	  7.16680438e-01  1.33580012e+00  2.26507441e+00  3.42829563e+00  4.27751198e+00
  4.43518209e-01  3.58670589e-01 -8.34979724e-03 -1.97236012e-04 -1.53501070e-03		   |	  3.67381232e+00  1.41044798e+00 -6.30902038e-03 -2.71733278e-01 -5.09642498e-01
 -7.95118391e-03 -3.21134529e-02 -1.00269643e-01 -2.34047112e-01 -3.01410928e-01		   |	 -8.68828733e-01 -1.35781019e+00 -1.81565094e+00 -1.93869191e+00 -1.18527822e+00
  1.03491965e+00  1.00000000e+00  1.00000000e+00  4.11634896e-02  2.57762836e-01		   |	  7.81974577e-01  1.52282703e+00  3.41176955e-01  3.43681595e+00  3.33255540e+00
  8.02419274e-01  1.00000000e+00  1.00000000e+00  1.00000000e+00  1.00000000e+00		   |	  2.24812218e+00  6.58169745e-01  1.45551678e-01  4.34146067e+00  4.64226043e-01
  1.00000000e+00  2.54948632e-02  1.90362766e-01  8.52162022e-01  1.00000000e+00		   |	  2.22914576e+00  3.57943173e-01  6.45565254e-01  9.51885590e-01  4.31234313e-01
  1.00000000e+00  1.00000000e+00  1.00000000e+00  1.00000000e+00  2.54948632e-02		   |	  1.81416938e-01  1.53238405e+00  3.06224305e-01  1.10187220e+00  3.57943173e-01
  1.90362766e-01  8.52162022e-01  1.00000000e+00  1.00000000e+00  1.00000000e+00		   |	  6.45565254e-01  9.51885590e-01  4.31234313e-01  1.81416938e-01  1.53238405e+00
  1.00000000e+00  1.00000000e+00								   |	  3.06224305e-01  1.10187220e+00
```

**Comment by bennybp** [comment]
If I'm reading this right, only the erd coefficients are stored and the libint coefficients determined from those?

**Comment by loriab** [comment]
Well, the libint coeffs are around (`s.coef`, as opposed to `s.erd_coef`), but yes, looks like erd coeffs were used to manipulate libint coeffs into fchk coeffs.

**Comment by bennybp** [comment]
See if this latest commit fixes the issue

**Comment by loriab** [comment]
Indeed it does, for both libint and erd. _Thank you._ (I'm still getting a `WARNING: string truncated` error when run through CTest, but that won't have anything to do with the code. I'll work on it. Just a warning that the CI may still fail.)

Do you want to cherry-pick my commits over from #605? Or shall I cherry-pick this last fix over to there, and merge from there?

**Comment by bennybp** [comment]
I'd say cherry pick this one. It's small enough and should be no problem

**Comment by loriab** [comment]
Very good, we should get this in this weekend.

**Comment by loriab** [comment]
subsumed by #605

**Pull request closed without merging**
