### PR TITLE
Remove built-in ADC module

### LINKED ISSUE #1033: Problems with ADC(2) in Psi4?
Hi everyone,

I was testing the ADC(2) code in Psi4 on small molecules and noticed that the results I obtained were significantly different from Q-Chem. The SCF and MP2 energies match very well.

For N2 (r = 1.2 A) with cc-pVDZ basis, here's a summary of the energies for the 8 lowest-lying singlet states from Q-Chem 4.4.1 compared to Psi4 1.1:

Q-Chem 4.4.1:
MP2 ground-state energy: -109.2579498247
  Excitation energy:                                               8.385211 eV
  Excitation energy:                                               8.385211 eV
  Excitation energy:                                               8.832813 eV
  Excitation energy:                                               9.441957 eV
  Excitation energy:                                               9.441957 eV
  Excitation energy:                                              13.868446 eV
  Excitation energy:                                              13.868446 eV
  Excitation energy:                                              14.791430 eV

Psi4 1.1: 
MP2 ground-state energy: -109.25794982519506
->	1  A state   :  0.3113289 (a.u.),  8.4716885 (eV)
->	2  A state   :  0.3113289 (a.u.),  8.4716885 (eV)
->	3  A state   :  0.3343892 (a.u.),  9.0991916 (eV)
->	4  A state   :  0.3565394 (a.u.),  9.7019279 (eV)
->	5  A state   :  0.3565394 (a.u.),  9.7019279 (eV)
->	6  A state   :  0.5069575 (a.u.), 13.7950140 (eV)
->	7  A state   :  0.5069575 (a.u.), 13.7950140 (eV)
->	8  A state   :  0.5127312 (a.u.), 13.9521243 (eV)

The Q-Chem energies agree with my standalone code. For N2 with STO-3G basis I simply get zero excitation energies with Psi4:

    ==> ADC(2) Computation <==                       
                                                     
->  1  A state   :  0.0000000 (a.u.),  0.0000000 (eV)
    Non-iterative:  0.3864160 (a.u.), 10.5149136 (eV)
       ┆   ┆ Occ Vir        Coefficient              
    ---------------------------------------------    
                                                     
    Converged in   2 iteration.                      
    Squared norm of the S component:  1.0000000      
    The S vector is rotated up to 90.000 (deg.)      
    #WARNING: Strongly rotated from the CIS state!   
                                                     
->  2  A state   :  0.0000000 (a.u.),  0.0000000 (eV)
    Non-iterative:  0.4145495 (a.u.), 11.2804653 (eV)
       ┆   ┆ Occ Vir        Coefficient              
    ---------------------------------------------    
                                                     
    Converged in   2 iteration.                      
    Squared norm of the S component:  1.0000000      
    The S vector is rotated up to 90.000 (deg.)      
    #WARNING: Strongly rotated from the CIS state!   

Any idea about what's going on? 

My input files for cc-pvdz:

**Psi4:**
molecule {                                
0 1                                       
N     0.000000      0.000000      0.000000
N     0.000000      0.000000      1.200000
symmetry c1                               
}                                         
                                          
set {                                     
basis cc-pvdz                             
guess sad                                 
reference rhf                             
scf_type pk                               
roots_per_irrep [8]                       
}                                         
                                          
set_num_threads(12)                       
energy('adc')                             

**Q-Chem:**
$molecule                  
0 1                        
N 0.0 0.0 0.0              
N 0.0 0.0 1.2              
$end                       
                           
$rem                       
jobtype             sp     
method              adc(2) 
basis               cc-pvdz
mem_total           4000   
mem_static          100    
cc_symmetry         false  
ee_singlets           8    
$end

### PR DESCRIPTION
**Pull request by maxscheurer**
## Description
This PR removes Psi's internal ADC module, so that all ADC calculations are run through `adcc` from now on.
Closes #1033.

## User API & Changelog headlines

- [x] remove built-in ADC module (does not remove any ADC features), closing #1033.

## Dev notes & details

- [x] remove built-in ADC code
- [x] update `proc.py`
- [x] update docs

## Questions
- [ ] Question1

## Checklist
- [x] Tests added for any new features
- [ ] [All or relevant fraction of full tests run](http://psicode.org/psi4manual/master/build_planning.html#how-to-run-a-subset-of-tests)

## Status
- [x] Ready for review
- [x] Ready for merge

### CODE REVIEW

**Comment by loriab** [comment]
For methods (or methods in certain circumstances, say reference or conv/df) only available through an external add-on, do we want those opt-in? That is, certainly the external must be (1) installed and detectable. But do we also want to (2) require the user to `set qc_module=mrcc|adcc|chemps2` ? CheMPS2 has a long history of not requiring (2). ADCC has a shorter history of being the preferred backend and automatic choice, if present. I just switched MRCC syntax in #2731 to yes require (2). That was in keeping with the user opt-ing in via `energy("mrccsd")`.

I can go either way, and I guess I'm now leaning toward not requiring (2) and adjusting MRCC accordingly. But it seems like something to discuss and settle on a consistent treatment.

**Comment by maxscheurer** [comment]
I think in the case of ADC, it makes little sense to require an explicit `qc_module` keyword as of now. In my opinion, it would just create another hurdle for users, not having an *actual* choice in that case. I cannot say much about a policy for the other modules though 😄

**Comment by loriab** [comment]
> I removed the MEMORY option from the ADC section, but now some tests using fnocc are failing, because apparently, the option was only provided by the ADC part in read_options.cc... What should I do about this? adcc does not take any input on available memory, so where should the MEMORY option live from now on?

My best guess at why fnocc is using MEMORY is so that it can get more memory under default  conditions (1gb instead of 0.5gb). Better handling would probably be to have a `FNOCC_TRIPLES_FACTOR` to manipulate input memory. I think comment out those `MEMORY` blocks in triples and lowmemory_triples, and we'll put up an issue. Those aren't running by default, and fnocc doesn't own MEMORY (as you discovered).

**Comment by JonathonMisiewicz** [comment]
Please mark this PR as closing #1033.

**Comment by JonathonMisiewicz** [comment]
Will `adc` be moved to the attic?

**Comment by maxscheurer** [comment]
> Will `adc` be moved to the attic?

I can do that, sure 👍🏻

**Review by JonathonMisiewicz — APPROVED** [review]
Hooray!

Remember to move the ADC code (including the equation PDF!) to the attic. @loriab will need to file that `fnocc` issue.

**Review by loriab — APPROVED** [review]

**Review by hokru — APPROVED** [review]
lgtm

**Pull request merged**
