### PR TITLE
Fix for cc14 test case

### PR DESCRIPTION
**Pull request by andysim**
## Description

Fixes cc14 by assigning SOCC and DOCC, which previously changed during the optimization.

## Status
- [x]  Ready to go

### CODE REVIEW

**Comment by loriab** [comment]
Splendid, LGTM. Now I'm the only stumbling block with mints9.

**Comment by dgasmith** [comment]
Great you found this! The occupation origination code did change when we removed boost, an issue about it is [here](https://github.com/psi4/psi4/issues/483). 

It looks like the behavior changed for this case. So, is this an issue with the input or with the new occupation code?

**Comment by andysim** [comment]
I guess it's an issue with the occupation code, but I think it gets corrected as the optimization proceeds (which changes dimensioning, which causes the psio problems we were observing).  In the long term we should do a check for the occupation within the optimizer, and issue a `psiclean()` if it changes, so that DPD doesn't choke, but that's beyond the scope of what I have time for right now sadly.

**Comment by andysim** [comment]
@dgasmith has a better fix, which actually addresses the underlying ROHF problem, so I'm going to close this in favor of his fix.

**Pull request closed without merging**
