### PR TITLE
Lapack

### PR DESCRIPTION
**Pull request by loriab**
## Description
This is a stab at fixing #537.

## Todos
Notable points that this PR has either accomplished or will accomplish.
* **Developer Interest**
  - [x] Kills off `BLAS_LIBRARIES`, `LAPACK_LIBRARIES`, `LAPACKBLAS_LIBRARIES` in favor of finding math libs, making a target for them and installing it into the stage tree. By using a target instead of a var:
    * Any linker `-Wl,` directives (start/end-group, as-needed) should be invulnerable to CMake link line optimization that rearranges them beyond usefulness.
    * targets can be passed into externals so that psi4 and externals use exactly same math libs.
  - [x] Same thing with HDF5. Both now in `external/common`
  - [x] Added `-liomp5` into MKL detection.
  - [ ] Haven't dealt with GCC+MKL OMP
  - [ ] Haven't looked at how this may change exporting Psi4 as target
* **User-Facing for Release Notes**
  - [x] OpenBLAS now found by the math detection system thanks to a patch from a friendly sysadmin
  - [x] Unless `ENABLE_GENERIC` is on, math detection for MKL searches for `mkl_rt.so` before any layered multi-lib scheme. Adapted from @ryanmrichard PRs. Also tacks on `-ldl` to the end of BLAS patterns, since the link-line advisor says so.

## Questions
- @robertodr, @bast, anyone who knows CMake, comments welcome.

## Status
- [x]  Ready to go

### CODE REVIEW

**Comment by bast** [comment]
Looks good to me from the CMake/math point of view. The foreach [here](https://github.com/psi4/psi4/pull/591/commits/242c33255741ca6783ce13d4143ed7096ef79766) looks a bit overkill. Will it be possible for me to take these changes over to Autocmake? The grand plan there is to split up the math detection monolith into individual modules. I am asking this because this now becomes GPL code and Autocmake is BSD. Advantage of taking it to Autocmake would be more testing exposure to other codes.

**Comment by loriab** [comment]
Yes, that foreach is overkill. I'll remove it if it looks like there's nothing more to add. You're welcome to take any of this back to autocmake. @robertodr's already mentioned putting together a backport. I wouldn't call this a thorough overhaul of the mkl detection, just a patch of some known deficiencies (mkl_rt, iomp5). And with all the `-Wl,`s mkl requires, I highly recommend ConfigMath/autocmake use targets, if it isn't already.

**Comment by bast** [comment]
I am discussing this with Roberto now. Roberto explains me now the motivation behind targets.

**Comment by bast** [comment]
Lori, if you have time, could you please describe briefly what the main reasons were for switching to targets as the mechanism to link to external libraries? What becomes easier? Are there known pitfalls/gotchas? I think targets look more robust than a string which could be (accidentally) modified on the way. In the initial math detection implementation we wanted to be close to how CMake finds libraries. Later I went a bit off course to make it easier for CMake-unaware colleagues to extend the detection. Now I feel I want to go back to more modular and CMake-like but I want to do it "right" this time so I would love to learn the advantages of using targets for this. Maybe you have a document you can point me to.

**Comment by loriab** [comment]
So I'm not a CMake expert, and most of what I know has been gleaned in the last six months just by reading the docs and listserve posts over and over again. CMake _does_ have a set of best practices in mind, but they don't (to my impression) do a good job of telling you what those practices are. And CMake is so flexible that it's easy to just ignore them. But insofar as they give explicit guidance, I've tried to follow it. So a few of my thoughts:

* Targets are to objects (OOP) as cmakevars (e.g., `${HDF5_LIBRARIES}`) are to data arrays. `Find<module>` or `<module>Config` that return <module>_LIBRARIES, _LIBRARY, _INCLUDE_DIR, _INCULDE_DIRS, _DEFINITIONS, _VERSION, _EXECUTABE, etc. are easy to relate to and not so hard to stick into `target_include_directories()`, `target_link_libraries()`, `target_compile_definitions()`, etc. in the consuming project. But it's so much nicer if the <module> author knows what his dependencies are, where his include directories are, whether they need to be used just to compile <module> or whether they need to be used by a consuming project, what compile definitions should be carried along. If all that gets packaged up in a target, then the consuming project need only `target_link_libraries(<tgt> <module>)` and not worry about the other stuff.

* CMake tries to be too smart. The items that get put into `target_link_libraries()`, it (pretty reasonably) treats according to the rules of linking libraries and makes bold to rearrange them. Only problem is that when we put linker directives (start-group, as-needed, etc.) and especially when they get repeated in the grand final linking, CMake optimizes them away. So `-la -Wl,--whole-archive -lb, -Wl,--no-whole-archive -lc -Wl,--whole-archive -ld -Wl,--no-whole-archive` merrily becomes `-la -lb, -lc -Wl,--whole-archive -ld -Wl,--no-whole-archive` which is Bad Indeed. However, CMake promises (somewhere) to keep target link libraries properties intact and not to optimize across them.

* I think https://github.com/eruffaldi/cmakego/blob/master/cmakego.cmake is a rather nice pattern, and I've emulated it a bit in the external/common/TargetLAPACK

* Targets make all the external projects we link to in psi4 look fairly clean. Below are all the CMakeLists.txt interactions

```
>>> grep -r '::' psi4/ | grep CMakeList
psi4/CMakeLists.txt:    get_property(_loc TARGET CheMPS2::chemps2 PROPERTY LOCATION)
psi4/CMakeLists.txt:    get_property(_loc TARGET dkh::dkh PROPERTY LOCATION)
psi4/CMakeLists.txt:get_property(_loc TARGET libefp::efp PROPERTY LOCATION)
psi4/CMakeLists.txt:    get_property(_loc TARGET erd::erd PROPERTY LOCATION)
psi4/CMakeLists.txt:    get_property(_loc TARGET gdma::gdma PROPERTY LOCATION)
psi4/CMakeLists.txt:get_property(_loc TARGET libint::int PROPERTY LOCATION)
psi4/CMakeLists.txt:    #get_property(_loc TARGET PCMSolver::PCMSolver PROPERTY LOCATION)
psi4/src/CMakeLists.txt:if(TARGET dkh::dkh)
psi4/src/CMakeLists.txt:    target_compile_definitions(core PRIVATE $<TARGET_PROPERTY:dkh::dkh,INTERFACE_COMPILE_DEFINITIONS>)
psi4/src/CMakeLists.txt:target_link_libraries(core PUBLIC pybind11::module)
psi4/src/CMakeLists.txt:target_link_libraries(core PRIVATE Threads::Threads)
psi4/src/CMakeLists.txt:target_include_directories(core PRIVATE $<TARGET_PROPERTY:libint::libint,INTERFACE_INCLUDE_DIRECTORIES>)  # comp def instead? only b/c boost export here not w/i mints
psi4/src/CMakeLists.txt:        NAMESPACE "psi4::"
psi4/src/psi4/libmints/CMakeLists.txt:target_link_libraries(mints PRIVATE libint::libint)
psi4/src/psi4/libmints/CMakeLists.txt:if(TARGET dkh::dkh)
psi4/src/psi4/libmints/CMakeLists.txt:    target_link_libraries(mints PRIVATE dkh::dkh)
psi4/src/psi4/libmints/CMakeLists.txt:if(TARGET erd::erd)
psi4/src/psi4/libmints/CMakeLists.txt:    target_link_libraries(mints PRIVATE erd::erd)
psi4/src/psi4/libscf_solver/CMakeLists.txt:if(TARGET PCMSolver::PCMSolver)
psi4/src/psi4/libscf_solver/CMakeLists.txt:    target_compile_definitions(scf_solver PRIVATE $<TARGET_PROPERTY:PCMSolver::PCMSolver,INTERFACE_COMPILE_DEFINITIONS>)
psi4/src/psi4/gdma_interface/CMakeLists.txt:if(TARGET gdma::gdma)
psi4/src/psi4/gdma_interface/CMakeLists.txt:    target_link_libraries(gdma_interface PUBLIC gdma::gdma)
psi4/src/psi4/dmrg/CMakeLists.txt:if(TARGET CheMPS2::chemps2)
psi4/src/psi4/dmrg/CMakeLists.txt:    target_link_libraries(dmrg PUBLIC CheMPS2::chemps2)
psi4/src/psi4/libefp_solver/CMakeLists.txt:target_link_libraries(efp_solver PUBLIC libefp::efp)
psi4/src/psi4/libpsipcm/CMakeLists.txt:if(TARGET PCMSolver::PCMSolver)
psi4/src/psi4/libpsipcm/CMakeLists.txt:    target_link_libraries(psipcm PRIVATE PCMSolver::PCMSolver)
```

These are a few tabs I had open that are at least a bit relevant.

* [listserve on imported targets](http://public.kitware.com/pipermail/cmake/2011-March/043148.html)
* [docs on relocatable packages](https://cmake.org/cmake/help/v3.7/manual/cmake-packages.7.html#creating-relocatable-packages)
* [really long thread about getting pybind11 to export a target](https://github.com/pybind/pybind11/pull/506)

**Comment by bast** [comment]
Thank you for the explanation! I really like how dependencies become more explicit (greppable).

**Comment by bast** [comment]
extern1 test fails for me (Arch Linux, gcc (GCC) 6.3.1, native BLAS/LAPACK):
```
Output:
----------------------------------------------------------
Performing finite difference calculations
 19 displacements needed ... 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19
        Finite difference (3-pt.) vs. analytic gradient to 10^-5..........PASSED
        Finite difference energy..........................................PASSED
        Analytic energy...................................................PASSED
Exit Status: infile ( -6 ); autotest ( None ); sowreap ( None ); overall ( 1 )
<end of output>
Test time =  29.12 sec
----------------------------------------------------------
Test Failed.
"extern1" end time: Jan 30 20:51 CET
"extern1" time elapsed: 00:00:29
```

**Comment by robertodr** [comment]
I've built on Ubuntu 15.10, using GCC 5.2.1 and MKL 11.3 with OpenMP enabled. Building worked smoothly and all quicktests passed.

**Comment by bast** [comment]
Indeed. Thumbs up. Very impressed and taking notes and learning.

**Comment by loriab** [comment]
@bast, could you post the end of the output file for the failed test case `<objdir>/tests/extern1/output.dat`? I'm perplexed as to what went wrong since the end of the test is simply:
```
    total time  =          6 seconds =       0.10 minutes
    Finite difference (3-pt.) vs. analytic gradient to 10^-5..........PASSED
    Finite difference energy..........................................PASSED
    Analytic energy...................................................PASSED

*** Psi4 exiting successfully. Buy a developer a beer!
```

**Comment by bast** [comment]
This is what I got and that looks good to me, too:
```
*** tstop() called on larry at Mon Jan 30 20:51:46 2017
Module time:
        user time   =       0.35 seconds =       0.01 minutes
        system time =       0.02 seconds =       0.00 minutes
        total time  =          1 seconds =       0.02 minutes
Total time:
        user time   =      24.96 seconds =       0.42 minutes
        system time =       0.20 seconds =       0.00 minutes
        total time  =         28 seconds =       0.47 minutes
        Finite difference (3-pt.) vs. analytic gradient to 10^-5..........PASSED
        Finite difference energy..........................................PASSED
        Analytic energy...................................................PASSED

*** Psi4 exiting successfully. Buy a developer a beer!
```

What does this mean: `Exit Status: infile ( -6 )`?

**Comment by loriab** [comment]
@psi-rking, you're one of the two people I know for whom this PR will actually solve a problem. That is, with this version of the code, Psi4's math detection should properly find your ACML libraries and forward them on to CheMPS2 and libefp without you fiddling with `LAPACKBLAS_LIBRARIES` or pointing to any special upstream branches. If you have a chance, I'd like to know if this works for you. Easiest way to get the code is a fresh checkout `git clone https://github.com/loriab/psi4.git` followed by branch switch `git checkout lapack`, then build as normal, giving none to minimal math hints. Also, don't use a `CMAKE_INSTALL_PREFIX` that has an existing psi4 in it (CMake's shown itself overzealous in finding and using old pybind11's). And, if you would, add `ENABLE_CheMPS2=ON` (you'll need hdf5 somewhere) to test that AddON + ACML, too.

**Comment by loriab** [comment]
@bast, the -6 is the return code from the subprocess call that ran the test case. Usually it reflects success (0) or failure (anything else). Not sure what's going off here, but since your job gave every other appearance of success, I won't worry about it unless more evidence surfaces. Thanks for testing it with an exotic (for us) setup.

**Comment by hokru** [comment]
I also ran into lapack issues with libefp when trying to compile psi4 with the latest PGI compiler (16.10 community edition). I just checked your branch @loriab and libefp configures+builds normally, both with MKL and PGI blas (basically system_native).

There are unrelated PGI issues that prevent a full psi4 build, but those are for another time.

**Comment by loriab** [comment]
Oh splendid, thanks for the report @hokru.

**Comment by psi-rking** [comment]
Lori, I just compiled a clone of your repository with no problems.
I had the following in my environment.
setenv MATH_ROOT /opt/acml6/gfortran64_mp/lib
Otherwise, everything was automatic and psi4 runs fine.

**Comment by loriab** [comment]
This has had favorable reports and no problems. And I just tried it with gcc/g++/gfortran+MKL and it gave the below, no problems. So I'm offering this as ready-to-go. Will rebase when its turn comes.

```
>>> ldd -v stage/path/to/hrw-temp/install-psi4/lib/psi4/core.so 
	linux-vdso.so.1 =>  (0x00007ffd40bdd000)
	libpcm.so.1 => /path/to/hrw-temp/objdir29/stage//path/to/hrw-temp/install-psi4/lib/libpcm.so.1 (0x00007f84bb67f000)
	libgdma.so => /path/to/miniconda/envs/texternals/lib/libgdma.so (0x00007f84bb2c1000)
	libderiv.so => /path/to/miniconda/envs/texternals/lib/libderiv.so (0x00007f84b4f3a000)
	libint.so => /path/to/miniconda/envs/texternals/lib/libint.so (0x00007f84b35b4000)
	libdkh.so => /path/to/hrw-temp/objdir29/stage//path/to/hrw-temp/install-psi4/lib/libdkh.so (0x00007f84b33a2000)
	libefp.so => /path/to/miniconda/envs/texternals/lib/libefp.so (0x00007f84b2847000)
	libmkl_rt.so => /path/to/miniconda/envs/texternals/lib/libmkl_rt.so (0x00007f84b221f000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f84b1fdd000)
	libm.so.6 => /path/to/miniconda/lib/libm.so.6 (0x00007f84b1d59000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f84b1b55000)
	libstdc++.so.6 => /path/to/miniconda/envs/texternals/lib/libstdc++.so.6 (0x00007f84b17c8000)
	libgomp.so.1 => /path/to/miniconda/envs/texternals/lib/libgomp.so.1 (0x00007f84b15a6000)
	libgcc_s.so.1 => /path/to/miniconda/envs/texternals/lib/libgcc_s.so.1 (0x00007f84b1390000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f84b0fcf000)
	libz.so.1 => /path/to/miniconda/envs/texternals/lib/libz.so.1 (0x00007f84b0db8000)
	libgfortran.so.3 => /path/to/miniconda/envs/texternals/lib/libgfortran.so.3 (0x00007f84b0a98000)
	libquadmath.so.0 => /path/to/miniconda/envs/texternals/lib/libquadmath.so.0 (0x00007f84b085a000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f84c3771000)
	librt.so.1 => /lib64/librt.so.1 (0x00007f84b0651000)
```

**Pull request merged**
