### PR TITLE
Fix some memory leaks

### PR DESCRIPTION
**Pull request by JonathonMisiewicz**
## Description
I was testing a trick I had heard of to clean up valgrind output (which alas, didn't work). I got carried away fixing the memory leaks it reported before deciding that continuing was not the best way to use my time. Don't expect this work to be continued in the immediate future. A "Valgrind Day" just like "LGTM Day" or "Documentation Day" would be very useful.

## Checklist
- [x] Because this was just fixing memory leaks, I'll leave testing to Azure. I can do more if anybody thinks there would be use in it?

## Status
- [x] Ready for review
- [x] Ready for merge

### CODE REVIEW

**Comment by susilehtola** [comment]
Has the code been run extensively through cppcheck? It is also pretty good at finding leaks.

**Comment by JonathonMisiewicz** [comment]
No, there has been no extensive or systematic cppcheck sweep of Psi code in my memory. I think Lori encouraged us to valgrind new code at a PsiCon several years back? I saw the slide.

**Comment by susilehtola** [comment]
Valgrinding is runtime and terribly slow. Cppcheck is static and quite fast.

**Comment by andysim** [comment]
I ran the code through cppcheck in [this PR](https://github.com/psi4/psi4/pull/1534).  It found some memory leaks, but not as many as I'd expected.  I second the call to have a valgrind/cleanup day at some point - there are still a number of mismatched new/malloc/free/delete pairs in the code that should be replaced with a RAII solution.

**Pull request merged**
