### PR TITLE
Threadmisc

### LINKED ISSUE #1016: ghost atom naming consolidation for input/output
`N(Gh)` in the output versus `Gh(N)` in the input.

Just a quality of life thing, but is it possible to decide upon one version so we can easily copy&paste from the output file?

### PR DESCRIPTION
**Pull request by loriab**
## Description
more misc.

## Todos
Notable points that this PR has either accomplished or will accomplish.
* **Developer Interest**
  - [x] CMake: patches OMP detection for conda GCC, coderefinery/autocmake#247
  - [x] Adds a script to probe threading
  - [x] Mol: output ghosts from E(Gh) --> Gh(E)  closes #1016 
  - [x] Fix up some license headers
  - [x] repoints GH:loriab/libxc --> GH:psi4/libxc

## Status
- [x] Ready for review
- [x] Ready for merge

### CODE REVIEW

**Comment by andysim** [comment]
Looks like this closes #1016

**Comment by loriab** [comment]
Good point, @andysim. I added the closes signal. And yes, mirroring `printf` `%` is very convenient.

**Comment by andysim** [comment]
Just out of interest, do you know if the tag that I added would have been sufficient to close the issue?  Not sure if it's possible to do it through comments on others' PRs.

**Comment by andysim** [comment]
Perhaps not - the `closes` in your comment is linked as a close action, but mine is not.

**Comment by loriab** [comment]
I think not. I removed my "closes" and the signal went away.

But with write access, you can edit the PR post and add it yourself. Go for it.

**Comment by andysim** [comment]
Ah, yes, that's how it's done - good call.  Just wanted to know for future PRs.  I hate asking people to do things in review that I could do myself in 2 seconds.

**Comment by loriab** [comment]
Yes, that "allow edits by maintainers" checkbox confers surprising powers.

**Pull request merged**
