### PR TITLE
More distelli testing

### PR DESCRIPTION
**Pull request by dgasmith**
This is a test branch.

### CODE REVIEW

**Comment by dgasmith** [comment]
Well, besides RAS failing looks like we have a new mac CI server.

**Comment by andysim** [comment]
Fantastic!

**Comment by andysim** [comment]
I made a disteli account when I saw your experimentation last week.  When I click "details" to see the test output, I get a 404 page.  Are there settings to increase the visibility of the test outputs?

**Comment by dgasmith** [comment]
Can you see [this](https://www.distelli.com/macpsinet/builds/76656)?

**Comment by dgasmith** [comment]
Looks like the non-CI Distelli hook is wrong.

**Comment by andysim** [comment]
Nope, can't see that.  I takes me to the login page and, after I login, it sends me to the 404 page (with poetry on it).

**Comment by dgasmith** [comment]
Well, thats not good-- I don't see any switches to flip inside the project. If we have to we can host the output ourselves somewhere.

**Comment by dgasmith** [comment]
@andysim They do not allow this for now, but its on their roadmap. Took about a week for them to get my last requested feature in.

If you send me your username I can add you to the Psi account.

**Comment by andysim** [comment]
Ah, ok.  Thanks for checking into that.  It'll be a useful feature when it's added, but it's great to have OSX coverage regardless.  My username is also andysim on Disteli.

**Comment by dgasmith** [comment]
@andysim Try now.

I can understand where they are coming from on the security side. There are not too many layers between log printing and security tokens. Very powerful tool however.

**Comment by andysim** [comment]
Negative.  I can't see any of the parent directories either, sadly.

**Comment by dgasmith** [comment]
Hey Distelli testing is now passing!

**Comment by andysim** [comment]
That's great!  I can see the log now, at least for the continuous-integration/Distelli link.  Not the Disteli-CI link; that could just be the malformed URL causing a problem though.  What's the difference between those hooks?

**Comment by andysim** [comment]
Now that I can see the log, I notice that you're building with AM=5.  If you plan to add some CBS tests that need *h* functions, we should bump the Travis setup.  If not, we should reduce Disteli's AM, to speed it up.

**Comment by dgasmith** [comment]
@andysim Good point, bumped down AM requirements. The "Distelli CI" link should be dead as its an incorrect hook configuration, shouldn't show up in the future.

**Comment by dgasmith** [comment]
Knocked about 10% off the total time to limit AM to 4. Going to close this for now, not sure a test branch will help us much more. Time to see how this fares in the wild.

**Pull request closed without merging**
