### PR TITLE
WIP: Repulsive potentials with Psi4

### PR DESCRIPTION
**Pull request by susilehtola**
## Description
The idea is to try to extend Psi4 to the calculation of repulsive potentials. Unfortunately, some of Psi4's machinery is preventing such calculations to be run due to chemists' short-sightedness ;)

## Todos
Notable points (developer or user-interest) that this PR has or will accomplish.
- [x] Change cutoffs so that close-lying atoms are accepted by the program (the cutoffs / disabling them should be an input parameter)
- [ ] Fix problem with the code putting atoms on top of each other

## Questions
- [ ] Question1

## Checklist
- [ ] Tests added for any new features
- [ ] [All or relevant fraction of full tests run](http://psicode.org/psi4manual/master/build_planning.html#how-to-run-a-subset-of-tests)

## Status
- [ ] Ready for review
- [ ] Ready for merge

### CODE REVIEW

**Comment by susilehtola** [comment]
The following calculation
```
molecule {
0 1
He 0.0 0.0 -0.01
Gh(Be) 0.0 0.0 0.0
He 0.0 0.0 0.01
}

set basis ugbs
energy('scf')
```
crashes with
```
qcelemental.exceptions.ValidationError: Following atoms are too close: [(0, 1, 0.0), (0, 2, 0.0), (1, 2, 0.0)]
```
Something in the code (QCElemental?) is bastardizing the input so that the atoms that are well-separated are placed on top of each other. @loriab @dgasmith

**Comment by susilehtola** [comment]
Also
```
mol = psi4.core.Molecule.from_arrays([0, 0, -0.01, 0, 0, 0.01], elez=[2,2])
activate(mol)
set basis ugbs
energy('scf')
```
fails with
```
  File "/home/work/psi4/install.susi/lib/qcelemental/molparse/from_arrays.py", line 597, in validate_and_fill_geometry
    for i, j, dist in tooclose_inds]))

qcelemental.exceptions.ValidationError: Following atoms are too close: [(0, 1, 0.0)]
```

**Comment by loriab** [comment]
this will get past molecule

```
diff --git a/psi4/driver/qcdb/molecule.py b/psi4/driver/qcdb/molecule.py
index f8f7ea6..361f059 100644
--- a/psi4/driver/qcdb/molecule.py
+++ b/psi4/driver/qcdb/molecule.py
@@ -1171,7 +1171,7 @@ class Molecule(LibmintsMolecule):
                     provenance=None,
                     connectivity=None,
                     missing_enabled_return='error',
-                    tooclose=0.1,
+                    tooclose=1.e-6, #0.1,
                     zero_ghost_fragments=False,
                     nonphysical=False,
                     mtol=1.e-3,
@@ -1465,7 +1465,7 @@ class Molecule(LibmintsMolecule):
         #   to_dict, but is included as a check. in practice, only fills in mass
         #   numbers and heals user chgmult.
         try:
-            validated_molrec = qcel.molparse.from_arrays(speclabel=False, verbose=0, domain='qm', **molrec)
+            validated_molrec = qcel.molparse.from_arrays(speclabel=False, verbose=0, domain='qm', tooclose=1.e-6, **molrec)
         except qcel.ValidationError as err:
             # * this can legitimately happen if total chg or mult has been set
             #   independently b/c fragment chg/mult not reset. so try again.
@@ -1474,7 +1474,7 @@ class Molecule(LibmintsMolecule):
             )
             molrec['fragment_charges'] = [None] * len(fragments)
             molrec['fragment_multiplicities'] = [None] * len(fragments)
-            validated_molrec = qcel.molparse.from_arrays(speclabel=False, verbose=0, domain='qm', **molrec)
+            validated_molrec = qcel.molparse.from_arrays(speclabel=False, verbose=0, domain='qm', tooclose=1.e-6, **molrec)
             forgive.append('fragment_charges')
             forgive.append('fragment_multiplicities')
         compare_molrecs(validated_molrec, molrec, 'to_dict', atol=1.e-6, forgive=forgive, verbose=0)
 
diff --git a/psi4/src/psi4/libmints/molecule.h b/psi4/src/psi4/libmints/molecule.h
index 30ef61e..6129121 100644
--- a/psi4/src/psi4/libmints/molecule.h
+++ b/psi4/src/psi4/libmints/molecule.h
@@ -317,9 +317,9 @@ class PSI_API Molecule {
 
     /// @{
     /// Tests to see of an atom is at the passed position with a given tolerance
-    int atom_at_position1(double*, double tol = 0.05) const;
-    int atom_at_position2(Vector3&, double tol = 0.05) const;
-    int atom_at_position3(const std::array<double, 3>&, const double tol = 0.05) const;
+    int atom_at_position1(double*, double tol = 1.e-6) const;
+    int atom_at_position2(Vector3&, double tol = 1.e-6) const;
+    int atom_at_position3(const std::array<double, 3>&, const double tol = 1.e-6) const;
     /// @}
 
     /// Do we reinterpret coordentries during a call to update_geometry?
@@ -505,7 +505,7 @@ class PSI_API Molecule {
      * Force the molecule to have the symmetry specified in pg_.
      * This is to handle noise coming in from optking.
      */
-    void symmetrize(double tol = 0.05, bool suppress_mol_print_in_exc = false);
+    void symmetrize(double tol = 1.e-6, bool suppress_mol_print_in_exc = false);
     /// @}
 
     /**
@@ -668,7 +668,7 @@ class PSI_API Molecule {
     /// Returns the Schoenflies symbol
     std::string schoenflies_symbol() const;
     /// Check if current geometry fits current point group
-    bool valid_atom_map(double tol = 0.05) const;
+    bool valid_atom_map(double tol = 1.e-6) const;
     /// Return point group name such as C3v or S8.
     std::string full_point_group() const;
     /// Return point group name such as Cnv or Sn.
```

input
```
import psi4

mol = psi4.core.Molecule.from_arrays(
    elez=[2, 4, 2],
    #fix_com=True,
    #fix_orientation=True,
    fix_symmetry='c1',
    tooclose=1.e-6,
    real=[True, False, True],
    geom=[
        1.0, 0.0, -0.01,
        1.0, 0.0,  0.0,
        1.0, 0.0,  0.01])
activate(mol)

set basis cc-pvdz #ugbs
energy('scf')

# fix_symmetry needed to avoid:
#Program received signal SIGFPE, Arithmetic exception.
#0x00007fffe1b5700e in psi::PetiteList::init (this=0x0, tol=0) at /home/psilocaluser/gits/hrw-direct/psi4/src/psi4/libmints/petitelist.cc:567
#567             lamij_[ij] = (char)(ng_ / nij);

# now ends with
#Fatal Error: SOBasis::SOBasis: shell changed
#Error occurred in file: /home/psilocaluser/gits/hrw-direct/psi4/src/psi4/libmints/sobasis.cc on line: 257
```

**Comment by loriab** [comment]
Main thing to watch for mol-wise is that if atoms are near and all the tolerances aren't even, internal molecule processing will take in all your coordinates, then effectively zero them without warning, so `geometry()` is an array of zeros, and downstream is right to protest that atoms are overlapping.

**Comment by susilehtola** [comment]
Okay, I got something to run, but it's getting inf's and nan's. Looks like built-in basis sets cause errors, while with custom ones the calculation runs, but something weird happens. The matrices look alright: the Cholesky procedure builds MOs, the Fock matrix is built and looks fine, but in the next iteration the density and Fock matrices are full of NaNs....
```
import psi4

mol = psi4.core.Molecule.from_arrays(
        elez=[2, 4, 2],
        #fix_com=True,
        #fix_orientation=True,
        fix_symmetry='c1',
        tooclose=1.e-6,
        real=[True, False, True],
        geom=[
                    1.0, 0.0, -0.05,
                    1.0, 0.0,  0.0,
                    1.0, 0.0,  0.05])
activate(mol)
set s_orthogonalization partialcholesky
set df_scf_guess false
set scf_type direct
set basis ugbs
#set basis cc-pvdz # fails with SOBasis: shell changed
#set basis cc-pvdz-decon # fails with SOBasis: shell changed
set debug 10
set guess core
energy('scf')
```

**Comment by susilehtola** [comment]
Well, I'm closing this for now since the problems seem non-trivial and the calculations can be run in PySCF.

**Pull request closed without merging**
