### PR TITLE
misc, incl. x2c grad warning

### PR DESCRIPTION
**Pull request by loriab**
## Description
A few items I ran across. addresses #2197 

## Status
- [x] Ready for review
- [ ] Ready for merge

### CODE REVIEW

**Comment by JonathonMisiewicz** [comment]
What happens if a user runs a computation, toggles whether X2C is on, and then calls the wavefunction's `compute_gradient` method?

**Comment by loriab** [comment]
> What happens if a user runs a computation, toggles whether X2C is on, and then calls the wavefunction's compute_gradient method?

Apparently even the non-rel returns a `psi4.core.RHF`, and since that hasn't had it's `compute_gradient` implemented, the parent `Wavefunction`'s `Analytic gradients are not available for this wavefunction.` is thrown.

Not what I was expecting (or probably what someone using a C++ API was expecting), but it does shut down a way to get the wrong answer by evading the Py APi.

**Comment by JonathonMisiewicz** [comment]
Because I'm actively trying to break this: `x2c` can be applied for correlated methods as well. It's great that we've caught it in `run_scf_gradient`, but what stops the x2c gradients for other electronic structure methods?

**Comment by loriab** [comment]
`compute_gradient` after a `energy("ccsd")` and `gradient("scf")` also throw the wfn.h error, so no worries there.

py-side `gradient("ccsd")` is what this PR misses catching, as I see it.

**Comment by loriab** [comment]
How about diverting to findif, like PCM? This'll need changing for DDD, but at least we'll notice.

(Note that PR not in self-consistent state at present. test needs replacing.)

**Comment by JonathonMisiewicz** [comment]
Great idea! I still have some concerns about potential ways to abuse `compute_gradient`, but my test cases won't even run for reasons far beyond the scope of this PR. Issue list is about to grow, but I'll be happy with the PR once the tests are updated.

Thanks for this, Lori.

**Comment by loriab** [comment]
This is RTG, imo.

**Review by JonathonMisiewicz — APPROVED** [review]

**Review by jturney — APPROVED** [review]

**Review by PeterKraus — APPROVED** [review]

**Pull request merged**
