### PR TITLE
Psi4 Inversion

### PR DESCRIPTION
**Pull request by dgasmith**
## Description
Converts Psi4 from a binary that calls Python to a Python module that calls a shared object as discussed in #468. 

## Features
- "psi4" is now a python module, the entire driver and suite of C++ functions is now behind this interface.
- The "bin/psi4" binary is now a python script that parses Psithon input to support the current Psi4 interface.
- For any conventional python script the following now works: `import psi4`.
- C++ no longer calls python, all python objects must be passed in from the driver.
   - BasisSet objects are the primary objects effected here. The Wavefunction now stores BasisSets constructed by python and can be accessed by `wfn->get_basis(*basis*)`.
- The C++ side of psi4 is now compiled to the a shared library with python access named "core.so".

## Remaining issues
- There are several outstanding issues, a list of which can be found [here](https://github.com/dgasmith/psi4/projects/1). All issues may not be cleaned up by the time this PR goes through, current full suite coverage of 99%.
- HF: Broken Symmetry guess is currently broken, apparently no test case for this.
- BasisSet is not final with regard to construct_combined and handling of user defined basis sets.
- SAD does not work due to basis set creation.

## Status
- [x]  Ready to go

### CODE REVIEW

**Comment by dgasmith** [comment]
Rebased through USAPT0 changes.

**Comment by dgasmith** [comment]
Getting pretty close to merging this in. Failing tests case should be limited to the following:

```
	 22 - cc14 (Failed)
	155 - docs-psimod (Failed)
	187 - mints9 (Failed)
```

Docs and mints both require changes to the test case. `cc14` remains the only undiagnosed test failure.

**Comment by andysim** [comment]
682 changed files!  GitHub struggled with this one.  I think the risk we introduce by delaying and making merges harder is far greater than the couple of failing tests, so I'm going to say LGTM.  Fantastic work to make this happen; sorry I couldn't help out.  Hopefully I'll be able to help the hunt for cc14's issue soon.

**Comment by jturney** [comment]
LGTM

**Comment by loriab** [comment]
``sapt7`` also in temporary broken list. LGTM

**Pull request merged**
