### PR TITLE
DFOCC Header Cleanup

### PR DESCRIPTION
**Pull request by andysim**
## Description
Remove some includes from DFOCC, to try and speed up compilation

## Todos
Notable points that this PR has either accomplished or will accomplish.
* **Developer Interest**
  - [x] Removed some includes from DFOCC header files.

## Questions
- [x]  Does this look reasonable @bozkaya?

## Status
- [x]  Ready to go (pending approval from @bozkaya)

…clarations.

### CODE REVIEW

**Comment by bozkaya** [comment]
The changes made LGTM! Thank you very much Andy!

**Comment by dgasmith** [comment]
LGTM

**Comment by jturney** [comment]
LGTM

**Comment by amjames** [comment]
LGTM

**Pull request merged**
