### PR TITLE
Fix #1998.

### LINKED ISSUE #1998: Dipole polarizabilities error when linear dependencies are removed
From forum: http://forum.psicode.org/t/polarizability-error-ao-mux-has-an-unrecognized-shape/1916/3

The error is `ERROR: "AO Mux" has an unrecognized shape. Must be either (36, 36) or (5, 31)`
https://github.com/psi4/psi4/blob/master/psi4/driver/procrouting/response/scf_response.py#L176
The `vector` here, has still the original size. DIdn't trace it any further.

Made up example for testing:
```
molecule mol {
0 1
O 0.44260 -0.88720 -0.29490
H 0.73940 -0.26640 -0.96690
H 0.79240 -0.54630 0.53350
}


basis {
assign verydiff
[verydiff]
spherical
****
H     0
S   4   1.00
      1.301000D+01           1.968500D-02
      1.962000D+00           1.379770D-01
      4.446000D-01           4.781480D-01
      1.220000D-01           5.012400D-01
S   1   1.00
      1.220000D-01           1.000000D+00
S   1   1.00
      0.0297400              1.0000000
P   1   1.00
      7.270000D-01           1.0000000
P   1   1.00
      0.1410000              1.0000000
****
O     0
S   9   1.00
      1.172000D+04           7.100000D-04
      1.759000D+03           5.470000D-03
      4.008000D+02           2.783700D-02
      1.137000D+02           1.048000D-01
      3.703000D+01           2.830620D-01
      1.327000D+01           4.487190D-01
      5.025000D+00           2.709520D-01
      1.013000D+00           1.545800D-02
      3.023000D-01          -2.585000D-03
S   9   1.00
      1.172000D+04          -1.600000D-04
      1.759000D+03          -1.263000D-03
      4.008000D+02          -6.267000D-03
      1.137000D+02          -2.571600D-02
      3.703000D+01          -7.092400D-02
      1.327000D+01          -1.654110D-01
      5.025000D+00          -1.169550D-01
      1.013000D+00           5.573680D-01
      3.023000D-01           5.727590D-01
S   1   1.00
      3.023000D-01           1.000000D+00
S   1   1.00
      0.0189600              1.0000000
P   4   1.00
      1.770000D+01           4.301800D-02
      3.854000D+00           2.289130D-01
      1.046000D+00           5.087280D-01
      2.753000D-01           4.605310D-01
P   1   1.00
      2.753000D-01           1.000000D+00
P   1   1.00
      0.0185600              1.0000000
D   1   1.00
      0.1000              1.0000000
D   1   1.00
      0.1000              1.0000000
****
}
```

### PR DESCRIPTION
**Pull request by susilehtola**
## Description
The size check in the scf response code was wrong.

## Todos
Notable points (developer or user-interest) that this PR has or will accomplish.
- [ ] Feature1
- [ ] Feature2

## Questions
- [ ] Question1

## Checklist
- [x] Tests added for any new features
- [ ] [All or relevant fraction of full tests run](http://psicode.org/psi4manual/master/build_planning.html#how-to-run-a-subset-of-tests)

## Status
- [x] Ready for review
- [x] Ready for merge

### CODE REVIEW

**Comment by susilehtola** [comment]
@loriab you mean as a new test case?

**Comment by loriab** [comment]
yes, please

**Comment by susilehtola** [comment]
Done. I simplified the test case further.

**Review by hokru — APPROVED** [review]
Thanks!

**Pull request merged**
