### PR TITLE
Fix energy return value of optimize() for IRC jobs.

### PR DESCRIPTION
**Pull request by avcopan**
Previously, this was returning the last computed energy.  Now, it returns the energy of the last IRC point.  This should fix the test cases, which were failing on some systems.

### CODE REVIEW

**Comment by loriab** [comment]
Thanks, @avcopan. On my system, your changes make it an order of magnitude closer to the check. If I back the compare_values up to 4, it passes.
```
    Energy of last IRC point: computed value (-92.874363) does not match (-92.874374) to 5 decimal places.
```

The only other thing that concerns me is `thisenergy = old_wfn.energy()`. Though `.energy()` is definitely the future, preferable way, right now `thisenergy = psi4.get_variable('CURRENT ENERGY')`, as you see right above at the gradient() call, is far more reliable, as so few methods properly set the energy member datum of Wavefunction.

So if the `4` and `CURRENT ENERGY` changes sound good to you, go ahead and make them. If you put "fixes psi4/psi4#290" in the commit message, it'll close the ticket when it gets merged.

**Comment by dgasmith** [comment]
Listing a fix to a blank change is probably not good practice incase we ever want to go back and check these. Can you please [squash](http://docs.scipy.org/doc/numpy-1.10.1/dev/gitwash/development_workflow.html#rewriting-commit-history) these into a single commit? Perhaps use the title of the first with the fixes tag at the end.

**Comment by avcopan** [comment]
Sorry about that -- I am a complete and utter dunce when it comes to Git.  Is what I just did okay, @dgasmith?

**Comment by dgasmith** [comment]
Unfortunately it looks like you just repushed the same changes. 

First run, `git rebase -i HEAD~7`. You should see all of your changes plus a few more.

Change all of your commits from "pick" to "squash" *except* for your very first one where you want to switch to "reword" so that you can rephrase this message. Save this file, you will then get a chance to reword the squashed commits (I would).

You can then run `git log --oneline` to make sure the history looks right. Also, examine a few files to make sure the correct changes are there. When you are ready to push, `git push origin master --force` will overwrite the history on the remote.

If something goes wrong before you push you can reset these changes by `git reset --hard origin/master`.

**Comment by avcopan** [comment]
Thanks for the help!  I didn't know about `git push origin master --force`.

**Pull request merged**
