### PR TITLE
Remove unused solvers

### PR DESCRIPTION
**Pull request by JonathonMisiewicz**
## Description
Removes over 4000 unused LoC that I don't think anybody knows how to maintain. DGAS said this was deprecated in favor of Python solvers anyways.

## Checklist
- [x] Quick tests pass

## Status
- [x] Ready for review
- [x] Ready for merge

### CODE REVIEW

**Comment by jturney** [comment]
I guess we can be confident that no plugins use this since these classes were not tagged with PSI_API?

**Comment by JonathonMisiewicz** [comment]
Not tagged PSI_API and not exported means there's no risk of breaking downstream.

**Review by jturney — APPROVED** [review]
Looks good!

**Review by loriab — APPROVED** [review]
worth sending to psi4attic?

**Comment by JonathonMisiewicz** [comment]
> worth sending to psi4attic?

Might as well. Do I make a PR to the attic repo, or is there some other procedure?

**Comment by loriab** [comment]
> Might as well. Do I make a PR to the attic repo, or is there some other procedure?

feel free to commit directly. lmk if you don't have write access -- it isn't much in demand.

**Review by andysim — APPROVED** [review]
I agree with the removal, but will let @JonathonMisiewicz merge when he's comfortable with the situation regarding the attic.

**Comment by JonathonMisiewicz** [comment]
Added the relevant files to attic. Thanks, Andy.

**Pull request merged**
