### PR TITLE
Bump PCMSolver tag

### PR DESCRIPTION
**Pull request by robertodr**
## Description
Bump git tag for PCMSolver to v1.1.2

## Todos
Notable points that this PR has either accomplished or will accomplish.
- [x] Bump git tag for PCMSolver to v1.1.2
- [x] Fix definition of `host_writer` function within Psi4

## Status
- [x]  Ready to go

### CODE REVIEW

**Comment by loriab** [comment]
I must have been confused, because I really thought PCMSolver needed a tag bump. But you're right, all the needed changes are psi4-side. Sorry about that– I wouldn't have asked you for psi4-side-only changes, but thanks for the PR.

**Comment by robertodr** [comment]
As a matter of fact, I was confused too :smile: What is the policy you plan on following for external projects? Upgrade the `GIT_TAG` anytime the external project is updated or a more conservative approach? I assumed the latter, hence the lack of changes in Psi4.

**Comment by loriab** [comment]
Sorry for the confusion. What you're doing with PCMSolver is working just fine. What broke down was me not realizing that the `1.1.2` tag had what I needed, and I didn't need `HEAD`. Below is what I wrote to someone recently. External projects for psi4 can choose one of the below (or propose a new scheme), and PCMSolver is doing (2).

If the below seems clear, I'll explicitly add it to the wiki.

External Project Versioning (choose one)
----------------------------

0. Tag a release “0.2”, “v0.2”, or whatever. Let me know and I’ll (i) build the conda package and (ii) bump the `Add_ExternalProject` tag (for non-plugins). Repeat in a few months with “0.3”, etc. This way is handy if you want to settle on stable commits while possibly breaking the repo in interim commits. You may be asked to bump the tag after resolving psi4+externalproj interface or build issues. If you move the tag to a later commit, you'll have to let me know so I rebuild the conda package with the same version but a later build number. This is what CheMPS2 and PCMSolver do.

0. Tag a release “0.2”, and I’ll (i) tell psinet to do nightly builds that increment micro on each git commit so versions will be "tag.micro" (e.g., 0.2.43) and (ii) remove git tag from `Add_ExternalProject` )for non-plugins). When you’re ready for 0.3, just make the new tag, no communication with me necessary. Strongly recommended not to mix light and annotated tags; the latter are always preferred; the former are what you get if you go through the github website tag-making interface. If the repo breaks such that “make” or any “make tests” you devise break, then no package will get uploaded, but otherwise the most recent will always be available. This is what Psi4 itself does.

0. hybrid– do 2. but have the version that ships with the psi4 binary be pinned to a certain stable build unless user deliberately installs another.

**Comment by robertodr** [comment]
@loriab The external projects versioning policy is clear, but I am still confused. Am I not doing (1)? It is no problem for me to take care of fixing Psi4 build/test for new PCMSolver version and then let you know _via_ a PR.

**Comment by loriab** [comment]
Yes, you're doing (1); I must be losing all semblance of accuracy in communication. Thanks, notification of bump via PR will continue to do nicely.

**Comment by robertodr** [comment]
@loriab OK, cool. I am now wondering how the problem came to be in the first place. Is the conda builder automatically checking out the latest commit from PCMSolver's own GitHub repository? It might then be safer (and save you some headaches) to hook it up to a given tag or commit you know works with Psi4.

**Comment by loriab** [comment]
The problem came about just because, in parallel, I'm (i) learning to build Mac conda packages for the half-dozen add-ons, (ii) bumping all the add-ons to their latest tag, (iii) determining a good package set (boost, libgcc, etc.) for a full-featured psi4 Mac binary for both users and developers, and (iv) trying out some new conda packaging and distribution tools. The conda package _does_ point to a git tag (hopefully the same git tag as in psi4's externalproject), but I had bumped the conda tag to `1.1.2`, got the conda pkg working, then fixed up psi4 to work with the detected conda pkg. Unfortunately, by the time I worked through some library issues and tried to build pcmsolver internally to psi4, with the `int` fix, I had forgotten the tagging details, leading to this whole mistaken first place. :-)

So yes, in future when someone informs me of a new version or bumps the externalproject tag, I'll bump the conda tags in sync.

**Comment by robertodr** [comment]
Thanks for the clarification :smile:

**Pull request merged**
