### PR TITLE
Add SCAN family of functionals

### PR DESCRIPTION
**Pull request by PeterKraus**
## Description
Adds a few functionals (SCAN0, revSCAN0, SCAN, revSCAN, BMK, revM06-L).
~Enables `dft_bench_i*` tests for SCAN, SCAN0, revPBE, SOGGA, SOGGA11, MN12-SX, MGGA_MS2h, MN12-L, BMK, N12, MGGA_MVS, PKZB, MN15-L, PBE50, MGGA_MVSh, SOGGA11-X, M06-L, N12-SX, PBEOP, MPW1LYP and GAM.~
Enables all reference values in `dft_bench_i*` tests, now sorted alphabetically. Functionals not present in Psi4 are automatically ~marked with `xfail`~ skipped - this currently includes B3TLAP, BP86VWN, LRC-BOP, PBEsol, t-HCTH, t-HCTHh, wM05-D and wM06-D3, in addition to wB97X-D3 which was already marked `xfail`.

## Todos
Notable points (developer or user-interest) that this PR has or will accomplish.
- [x] adds SCAN and SCAN0
- [ ] tests for revSCAN, revSCAN0, revM06-L are missing - if anyone has access to these in other codes, I'd appreciate reference values!

## Checklist
- [x] Tests added for functionals, where available
- [x] `dft_bench_interaction` and `dft_bench_ionization` pass.

## Status
- [x] Ready for review
- [ ] Ready for merge

### CODE REVIEW

**Comment by susilehtola** [comment]
The functional interface should be modified in such a way that Psi4 pulls the info about the functionals (i.e. the citations) from libxc; there's little sense in duplicating this information.

**Comment by dgasmith** [comment]
This is already the case in `libxc_functionals.py`. This list simply needs an expansion I believe.

**Comment by loriab** [comment]
Good call on alphabetizing. Like code formatting, better sooner than later. 

I think turn xfail into skip to better reflect non implemented.

**Comment by susilehtola** [comment]
@loriab it should be pretty straightforward for psi4 to pull in the citations for the exhange and correlation part separately from libxc. For the case of SCAN0, it appears the hybrid exchange functional doesn't cite the SCAN paper, but this can be fixed in libxc.

**Comment by dgasmith** [comment]
@psi4/admins Lets get a final review here.

**Pull request merged**
