### PR TITLE
Safer memory operations

### PR DESCRIPTION
**Pull request by susilehtola**
## Description
This PR 
(a) adds checks that alloc's have been succesful in optking
(b) rewrites detci's print_config routine to use dynamic memory allocation instead of static arrays, which I believe caused issue #606.

## Status
- [x]  Ready to go

### CODE REVIEW

**Comment by susilehtola** [comment]
I opted to use std::string and ostringstream instead of just increasing the size of the static arrays, because this is not bottleneck code. I'm not sure why they were used in the original code, but that seemed to be over 20 years old, i.e. originally C code?

**Comment by loriab** [comment]
Thanks, `char *` --> `std::string` always welcome.

**Comment by dgasmith** [comment]
I looked at the original error and thought that the debugger was throwing on the wrong line, so this is a really great catch!

Yes, most of the CI code was overhauled last year; however, most parts that deal with determinants have not been touched in awhile. I need to pull it down and double check, but I think this all looks great. Thanks for the contribution.

**Comment by susilehtola** [comment]
Yeah I'm still trying to check if #606 is solved by this, but I'm pretty sure the static arrays were overflown and caused memory corruption.

**Comment by susilehtola** [comment]
But this can be merged regardless.

**Pull request merged**
