### PR TITLE
OH to c1 for test consistency

### PR DESCRIPTION
**Pull request by loriab**
## Description
OH molden tests were getting tripped up in conda packages on B1 vs. B2. Specifying `c2vz` and playing with convergence didn't help.

## Checklist
- [ ] Tests added for any new features
- [x] [All or relevant fraction of full tests run](http://psicode.org/psi4manual/master/build_planning.html#how-to-run-a-subset-of-tests)

## Status
- [x] Ready for review
- [x] Ready for merge

### CODE REVIEW

**Comment by JonathonMisiewicz** [comment]
Can you elaborate on "tripped up"? While I'm willing to sacrifice to get 1.4 out, I'm not happy about losing any of the symmetry test coverage.

**Comment by loriab** [comment]
ah, sure, see below. iirc, this often happens when we try to have OH in tests. output files look innocent.

```
   compare_moldenfiles...................................................................PASSED
    text line:  Sym= A1...................................................................PASSED
    float value:  Ene=        -2.0635785811e+01...........................................PASSED
    text line:  Spin= Alpha...............................................................PASSED
    float value:  Occup=         1.0000000000e+00.........................................PASSED
    int value:   1         5.8058355073e-01...............................................PASSED
    float value:   1         5.8058355073e-01.............................................PASSED
    int value:   2         4.6124354140e-01...............................................PASSED
    float value:   2         4.6124354140e-01.............................................PASSED
    int value:   3         1.0895933039e-03...............................................PASSED
    float value:   3         1.0895933039e-03.............................................PASSED
    int value:   4         1.2480807951e-03...............................................PASSED
    float value:   4         1.2480807951e-03.............................................PASSED
    int value:   5         0.0000000000e+00...............................................PASSED
    float value:   5         0.0000000000e+00.............................................PASSED
    int value:   6         0.0000000000e+00...............................................PASSED
    float value:   6         0.0000000000e+00.............................................PASSED
    int value:   7         1.4041668951e-03...............................................PASSED
    float value:   7         1.4041668951e-03.............................................PASSED
    int value:   8         0.0000000000e+00...............................................PASSED
    float value:   8         0.0000000000e+00.............................................PASSED
    int value:   9         0.0000000000e+00...............................................PASSED
    float value:   9         0.0000000000e+00.............................................PASSED
    int value:  10        -4.7012559882e-04...............................................PASSED
    float value:  10        -4.7012559882e-04.............................................PASSED
    int value:  11        -5.6124862466e-05...............................................PASSED
    float value:  11        -5.6124862466e-05.............................................PASSED
    int value:  12         4.9588594630e-05...............................................PASSED
    float value:  12         4.9588594630e-05.............................................PASSED
    text line:  Sym= A1...................................................................PASSED
    float value:  Ene=        -1.3925838658e+00...........................................PASSED
    text line:  Spin= Alpha...............................................................PASSED
    float value:  Occup=         1.0000000000e+00.........................................PASSED
    int value:   1         1.3886909270e-01...............................................PASSED
    float value:   1         1.3886909270e-01.............................................PASSED
    int value:   2         1.9292546210e-01...............................................PASSED
    float value:   2         1.9292546210e-01.............................................PASSED
    int value:   3        -5.6245285794e-01...............................................PASSED
    float value:   3        -5.6245285794e-01.............................................PASSED
    int value:   4        -4.7557649147e-01...............................................PASSED
    float value:   4        -4.7557649147e-01.............................................PASSED
    int value:   5         0.0000000000e+00...............................................PASSED
    float value:   5         0.0000000000e+00.............................................PASSED
    int value:   6         0.0000000000e+00...............................................PASSED
    float value:   6         0.0000000000e+00.............................................PASSED
    int value:   7        -1.1617963684e-01...............................................PASSED
    float value:   7        -1.1617963684e-01.............................................PASSED
    int value:   8         0.0000000000e+00...............................................PASSED
    float value:   8         0.0000000000e+00.............................................PASSED
    int value:   9         0.0000000000e+00...............................................PASSED
    float value:   9         0.0000000000e+00.............................................PASSED
    int value:  10        -3.0428440687e-02...............................................PASSED
    float value:  10        -3.0428440687e-02.............................................PASSED
    int value:  11        -1.4386690569e-01...............................................PASSED
    float value:  11        -1.4386690569e-01.............................................PASSED
    int value:  12         1.5057099421e-03...............................................PASSED
    float value:  12         1.5057099421e-03.............................................PASSED
    text line:  Sym= A1...................................................................PASSED
    float value:  Ene=        -6.7350891493e-01...........................................PASSED
    text line:  Spin= Alpha...............................................................PASSED
    float value:  Occup=         1.0000000000e+00.........................................PASSED
    int value:   1         4.1992024616e-02...............................................PASSED
    float value:   1         4.1992024616e-02.............................................PASSED
    int value:   2         5.8179443767e-02...............................................PASSED
    float value:   2         5.8179443767e-02.............................................PASSED
    int value:   3        -1.7188377750e-01...............................................PASSED
    float value:   3        -1.7188377750e-01.............................................PASSED
    int value:   4        -2.5608498525e-01...............................................PASSED
    float value:   4        -2.5608498525e-01.............................................PASSED
    int value:   5         0.0000000000e+00...............................................PASSED
    float value:   5         0.0000000000e+00.............................................PASSED
    int value:   6         0.0000000000e+00...............................................PASSED
    float value:   6         0.0000000000e+00.............................................PASSED
    int value:   7         6.2339094000e-01...............................................PASSED
    float value:   7         6.2339094000e-01.............................................PASSED
    int value:   8         0.0000000000e+00...............................................PASSED
    float value:   8         0.0000000000e+00.............................................PASSED
    int value:   9         0.0000000000e+00...............................................PASSED
    float value:   9         0.0000000000e+00.............................................PASSED
    int value:  10         2.3283823492e-01...............................................PASSED
    float value:  10         2.3283823492e-01.............................................PASSED
    int value:  11         2.8055889891e-01...............................................PASSED
    float value:  11         2.8055889891e-01.............................................PASSED
    int value:  12         1.2367881234e-01...............................................PASSED
    float value:  12         1.2367881234e-01.............................................PASSED
    text line:  Sym= B2...................................................................FAILED

E           psi4.driver.p4util.exceptions.TestComparisonError: 	text line:  Sym= B2: computed value (B2) does not match (B1) by difference ((n/a)).
```

```
Scratch directory: /tmp/										Scratch directory: /tmp/

*** tstart() called on psinet										*** tstart() called on psinet
*** at Sun Aug  1 18:19:38 2021									   |	*** at Sun Aug  1 18:26:41 2021

   => Loading Basis Set <=										   => Loading Basis Set <=

    Name: DZ												    Name: DZ
    Role: ORBITAL											    Role: ORBITAL
    Keyword: BASIS											    Keyword: BASIS
    atoms 1 entry O          line   107 file /scratch/psilocaluser/conda-builds/psi4-multiout_16   |	    atoms 1 entry O          line   107 file /psi/gits/hrw-testgcc/objdir36-75/stage/share/psi4/
    atoms 2 entry H          line    12 file /scratch/psilocaluser/conda-builds/psi4-multiout_16   |	    atoms 2 entry H          line    12 file /psi/gits/hrw-testgcc/objdir36-75/stage/share/psi4/


         ---------------------------------------------------------					         ---------------------------------------------------------
                                   SCF									                                   SCF
               by Justin Turney, Rob Parrish, Andy Simmonett						               by Justin Turney, Rob Parrish, Andy Simmonett
                          and Daniel G. A. Smith							                          and Daniel G. A. Smith
                              UHF Reference								                              UHF Reference
                        1 Threads,    500 MiB Core							                        1 Threads,    500 MiB Core
         ---------------------------------------------------------					         ---------------------------------------------------------

  ==> Geometry <==											  ==> Geometry <==

    Molecular point group: c2v										    Molecular point group: c2v
    Full point group: C_inf_v										    Full point group: C_inf_v

    Geometry (in Angstrom), charge = 0, multiplicity = 2:						    Geometry (in Angstrom), charge = 0, multiplicity = 2:

       Center              X                  Y                   Z               Mass       		       Center              X                  Y                   Z               Mass       
    ------------   -----------------  -----------------  -----------------  -----------------		    ------------   -----------------  -----------------  -----------------  -----------------
         O            0.000000000000     0.000000000000    -0.057517917037    15.994914619570		         O            0.000000000000     0.000000000000    -0.057517917037    15.994914619570
         H            0.000000000000     0.000000000000     0.912851082963     1.007825032230		         H            0.000000000000     0.000000000000     0.912851082963     1.007825032230

  Running in c2v symmetry.										  Running in c2v symmetry.

  Rotational constants: A = ************  B =     18.88315  C =     18.88315 [cm^-1]			  Rotational constants: A = ************  B =     18.88315  C =     18.88315 [cm^-1]
  Rotational constants: A = ************  B = 566102.67788  C = 566102.67788 [MHz]			  Rotational constants: A = ************  B = 566102.67788  C = 566102.67788 [MHz]
  Nuclear repulsion =    4.362688508557055								  Nuclear repulsion =    4.362688508557055

  Charge       = 0											  Charge       = 0
  Multiplicity = 2											  Multiplicity = 2
  Electrons    = 9											  Electrons    = 9
  Nalpha       = 5											  Nalpha       = 5
  Nbeta        = 4											  Nbeta        = 4

  ==> Algorithm <==											  ==> Algorithm <==

  SCF Algorithm Type is PK.										  SCF Algorithm Type is PK.
  DIIS enabled.												  DIIS enabled.
  MOM disabled.												  MOM disabled.
  Fractional occupation disabled.									  Fractional occupation disabled.
  Guess Type is SAD.											  Guess Type is SAD.
  Energy threshold   = 1.00e-06										  Energy threshold   = 1.00e-06
  Density threshold  = 1.00e-06										  Density threshold  = 1.00e-06
  Integral threshold = 1.00e-12										  Integral threshold = 1.00e-12

  ==> Primary Basis <==											  ==> Primary Basis <==

  Basis Set: DZ												  Basis Set: DZ
    Blend: DZ												    Blend: DZ
    Number of shells: 8											    Number of shells: 8
    Number of basis functions: 12									    Number of basis functions: 12
    Number of Cartesian functions: 12									    Number of Cartesian functions: 12
    Spherical Harmonics?: false										    Spherical Harmonics?: false
    Max angular momentum: 1										    Max angular momentum: 1

  ==> Integral Setup <==										  ==> Integral Setup <==

  Using in-core PK algorithm.										  Using in-core PK algorithm.
   Calculation information:										   Calculation information:
      Number of atoms:                   2								      Number of atoms:                   2
      Number of AO shells:               8								      Number of AO shells:               8
      Number of primitives:             18								      Number of primitives:             18
      Number of atomic orbitals:        12								      Number of atomic orbitals:        12
      Number of basis functions:        12								      Number of basis functions:        12

      Integral cutoff                 1.00e-12								      Integral cutoff                 1.00e-12
      Number of threads:                 1								      Number of threads:                 1

  Performing in-core PK											  Performing in-core PK
  Using 6162 doubles for integral storage.								  Using 6162 doubles for integral storage.
  We computed 666 shell quartets total.									  We computed 666 shell quartets total.
  Whereas there are 666 unique shell quartets.								  Whereas there are 666 unique shell quartets.

  ==> DiskJK: Disk-Based J/K Matrices <==								  ==> DiskJK: Disk-Based J/K Matrices <==

    J tasked:                  Yes									    J tasked:                  Yes
    K tasked:                  Yes									    K tasked:                  Yes
    wK tasked:                  No									    wK tasked:                  No
    Memory [MiB]:              375									    Memory [MiB]:              375
    Schwarz Cutoff:          1E-12									    Schwarz Cutoff:          1E-12

    OpenMP threads:              1									    OpenMP threads:              1

  Minimum eigenvalue in the overlap matrix is 6.5615359192E-02.						  Minimum eigenvalue in the overlap matrix is 6.5615359192E-02.
  Reciprocal condition number of the overlap matrix is 2.1736231954E-02.				  Reciprocal condition number of the overlap matrix is 2.1736231954E-02.
    Using symmetric orthogonalization.									    Using symmetric orthogonalization.

  ==> Pre-Iterations <==										  ==> Pre-Iterations <==

  SCF Guess: Superposition of Atomic Densities via on-the-fly atomic UHF (no occupation informat	  SCF Guess: Superposition of Atomic Densities via on-the-fly atomic UHF (no occupation informat

   -------------------------										   -------------------------
    Irrep   Nso     Nmo    										    Irrep   Nso     Nmo    
   -------------------------										   -------------------------
     A1         8       8 										     A1         8       8 
     A2         0       0 										     A2         0       0 
     B1         2       2 										     B1         2       2 
     B2         2       2 										     B2         2       2 
   -------------------------										   -------------------------
    Total      12      12										    Total      12      12
   -------------------------										   -------------------------

  ==> Iterations <==											  ==> Iterations <==

                        Total Energy        Delta E     RMS |[F,P]|					                        Total Energy        Delta E     RMS |[F,P]|

   @UHF iter SAD:   -74.69099268118431   -7.46910e+01   0.00000e+00 				   |	   @UHF iter SAD:   -74.69099268118434   -7.46910e+01   0.00000e+00 
   @UHF iter   1:   -75.36638207835102   -6.75389e-01   2.07053e-02 DIIS			   |	   @UHF iter   1:   -75.36638207835099   -6.75389e-01   2.07053e-02 DIIS
   @UHF iter   2:   -75.38394424152470   -1.75622e-02   7.43115e-03 DIIS			   |	   @UHF iter   2:   -75.38394424152474   -1.75622e-02   7.43115e-03 DIIS
   @UHF iter   3:   -75.38582621410333   -1.88197e-03   2.33008e-03 DIIS			   |	   @UHF iter   3:   -75.38582621410339   -1.88197e-03   2.33008e-03 DIIS
   @UHF iter   4:   -75.38619478049240   -3.68566e-04   9.29768e-04 DIIS			   |	   @UHF iter   4:   -75.38619478049243   -3.68566e-04   9.29768e-04 DIIS
   @UHF iter   5:   -75.38629447046014   -9.96900e-05   3.08853e-04 DIIS			   |	   @UHF iter   5:   -75.38629447046023   -9.96900e-05   3.08853e-04 DIIS
   @UHF iter   6:   -75.38630883426671   -1.43638e-05   1.16185e-04 DIIS			   |	   @UHF iter   6:   -75.38630883426674   -1.43638e-05   1.16185e-04 DIIS
   @UHF iter   7:   -75.38631113759388   -2.30333e-06   2.55403e-05 DIIS			   |	   @UHF iter   7:   -75.38631113759392   -2.30333e-06   2.55403e-05 DIIS
   @UHF iter   8:   -75.38631121690256   -7.93087e-08   5.57003e-06 DIIS			   |	   @UHF iter   8:   -75.38631121690257   -7.93086e-08   5.57003e-06 DIIS
   @UHF iter   9:   -75.38631122050272   -3.60016e-09   6.77022e-07 DIIS			   |	   @UHF iter   9:   -75.38631122050275   -3.60018e-09   6.77022e-07 DIIS
  Energy and wave function converged.									  Energy and wave function converged.


  ==> Post-Iterations <==										  ==> Post-Iterations <==

   @Spin Contamination Metric:   4.301100511E-03							   @Spin Contamination Metric:   4.301100511E-03
   @S^2 Expected:                7.500000000E-01							   @S^2 Expected:                7.500000000E-01
   @S^2 Observed:                7.543011005E-01							   @S^2 Observed:                7.543011005E-01
   @S   Expected:                5.000000000E-01							   @S   Expected:                5.000000000E-01
   @S   Observed:                5.000000000E-01							   @S   Observed:                5.000000000E-01

    Orbital Energies [Eh]										    Orbital Energies [Eh]
    ---------------------										    ---------------------

    Alpha Occupied:                                                       				    Alpha Occupied:                                                       

       1A1   -20.635786     2A1    -1.392584     3A1    -0.673509  					       1A1   -20.635786     2A1    -1.392584     3A1    -0.673509  
       1B2    -0.647734     1B1    -0.561066  							   |	       1B1    -0.647734     1B2    -0.561066  

    Alpha Virtual:                                                        				    Alpha Virtual:                                                        

       4A1     0.223681     2B2     0.784656     2B1     0.835171  				   |	       4A1     0.223681     2B1     0.784656     2B2     0.835171  
       5A1     0.887882     6A1     1.122186     7A1     1.471866  					       5A1     0.887882     6A1     1.122186     7A1     1.471866  
       8A1    43.203538  										       8A1    43.203538  

    Beta Occupied:                                                        				    Beta Occupied:                                                        

       1A1   -20.594556     2A1    -1.235213     3A1    -0.621110  					       1A1   -20.594556     2A1    -1.235213     3A1    -0.621110  
       1B1    -0.505839  									   |	       1B2    -0.505839  

    Beta Virtual:                                                         				    Beta Virtual:                                                         

       1B2     0.107995     4A1     0.237507     2B1     0.858087  				   |	       1B1     0.107995     4A1     0.237507     2B2     0.858087  
       5A1     0.910618     2B2     0.972383     6A1     1.128016  				   |	       5A1     0.910618     2B1     0.972383     6A1     1.128016  
       7A1     1.521957     8A1    43.228970  								       7A1     1.521957     8A1    43.228970  

    Final Occupation by Irrep:										    Final Occupation by Irrep:
             A1    A2    B1    B2 									             A1    A2    B1    B2 
    DOCC [     3,    0,    1,    0 ]								   |	    DOCC [     3,    0,    0,    1 ]
    SOCC [     0,    0,    0,    1 ]								   |	    SOCC [     0,    0,    1,    0 ]

  @UHF Final Energy:   -75.38631122050272							   |	  @UHF Final Energy:   -75.38631122050275

   => Energetics <=											   => Energetics <=

    Nuclear Repulsion Energy =              4.3626885085570546						    Nuclear Repulsion Energy =              4.3626885085570546
    One-Electron Energy =                -112.6306119634574259					   |	    One-Electron Energy =                -112.6306119634574543
    Two-Electron Energy =                  32.8816122343976502					   |	    Two-Electron Energy =                  32.8816122343976573
    Total Energy =                        -75.3863112205027193					   |	    Total Energy =                        -75.3863112205027335

  UHF NO Occupations:											  UHF NO Occupations:
  HONO-2 :    1 B1 1.9996187									   |	  HONO-2 :    1 B2 1.9996187
  HONO-1 :    3 A1 1.9985538										  HONO-1 :    3 A1 1.9985538
  HONO-0 :    1 B2 1.0000000									   |	  HONO-0 :    1 B1 1.0000000
  LUNO+0 :    4 A1 0.0014462										  LUNO+0 :    4 A1 0.0014462
  LUNO+1 :    2 B1 0.0003813									   |	  LUNO+1 :    2 B2 0.0003813
  LUNO+2 :    5 A1 0.0003240										  LUNO+2 :    5 A1 0.0003240
  LUNO+3 :    6 A1 0.0000002										  LUNO+3 :    6 A1 0.0000002


Computation Completed											Computation Completed


Properties will be evaluated at   0.000000,   0.000000,   0.000000 [a0]					Properties will be evaluated at   0.000000,   0.000000,   0.000000 [a0]

Properties computed using the SCF density matrix							Properties computed using the SCF density matrix

  Nuclear Dipole Moment: [e a0]										  Nuclear Dipole Moment: [e a0]
     X:     0.0000      Y:     0.0000      Z:     0.8555						     X:     0.0000      Y:     0.0000      Z:     0.8555

  Electronic Dipole Moment: [e a0]									  Electronic Dipole Moment: [e a0]
     X:     0.0000      Y:     0.0000      Z:     0.0063						     X:     0.0000      Y:     0.0000      Z:     0.0063

  Dipole Moment: [e a0]											  Dipole Moment: [e a0]
     X:     0.0000      Y:     0.0000      Z:     0.8618     Total:     0.8618				     X:     0.0000      Y:     0.0000      Z:     0.8618     Total:     0.8618

  Dipole Moment: [D]											  Dipole Moment: [D]
     X:     0.0000      Y:     0.0000      Z:     2.1904     Total:     2.1904				     X:     0.0000      Y:     0.0000      Z:     2.1904     Total:     2.1904


*** tstop() called on psinet at Sun Aug  1 18:19:38 2021					   |	*** tstop() called on psinet at Sun Aug  1 18:26:41 2021
Module time:												Module time:
	user time   =       0.18 seconds =       0.00 minutes					   |		user time   =       0.19 seconds =       0.00 minutes
	system time =       0.01 seconds =       0.00 minutes							system time =       0.01 seconds =       0.00 minutes
	total time  =          0 seconds =       0.00 minutes							total time  =          0 seconds =       0.00 minutes
Total time:												Total time:
	user time   =       0.18 seconds =       0.00 minutes					   |		user time   =       0.19 seconds =       0.00 minutes
	system time =       0.01 seconds =       0.00 minutes							system time =       0.01 seconds =       0.00 minutes
	total time  =          0 seconds =       0.00 minutes							total time  =          0 seconds =       0.00 minutes
```

**Review by JonathonMisiewicz — APPROVED** [review]
I see, for linear molecules (at least), how Psi decides which axis is the B1 axis and which is the B2 axis is non-deterministic. By symmetry, there isn't a "physical" way to determine this.

Longer term, I'd prefer to fix the output parser, but this is definitely good enough for now. Thanks for the investigation!

**Review by hokru — APPROVED** [review]

**Review by dgasmith — APPROVED** [review]
LGTM!

**Pull request merged**
