### PR TITLE
Disable libint2 Primitive Screening

### PR DESCRIPTION
**Pull request by zachglick**
## Description

Disables libint2's primitive screening via the `engine_precision` parameter. This integral screening provided a minor speedup, but in rare cases led to disastrously wrong SCF behavior as noted in #2114 and [here](https://github.com/edeprince3/hilbert/issues/8). This pull request closes those issues.

Note that this primitive screening is independent of the shell-pair level Schwarz and CSAM screening performed in Psi4. The previous workaround to this problem, which was to set the `ints_tolerance` keyword to 0.0, is no longer necessary.

## Todos

- [x] Change precision

## Checklist
- [x] all ctests are unaffected by this change

## Status
- [x] Ready for review
- [ ] Ready for merge

### CODE REVIEW

**Review by andysim — APPROVED** [review]
I completely agree with this change.  Thanks for figuring out all of the problems related to the primitive screening; I think a lot of the confusion comes from my initial implementation so sorry for the wasted time!  LGTM

**Comment by andysim** [comment]
Could you quickly grep for any tests that specify the `ints_tolerance` keyword, and check to see whether they still need it, please?

**Comment by loriab** [comment]
Thank you, Zach. I'm sorry you hit the results of my loose precision choice, but thanks for investigating. I'll run a conda-build to avoid surprises.

**Comment by JonathonMisiewicz** [comment]
Will this close #2114 ?

**Comment by zachglick** [comment]
No worries, this was easy compared to the actual libint2 interface that you all had to write and test. I've updated the post to clarify that this PR closes #2114.

**Comment by susilehtola** [comment]
Looks good

**Comment by JonathonMisiewicz** [comment]
Did you check if the `ints_tolerance  1e-14` in `ao-casscf-sp` is necessary?

**Review by loriab — APPROVED** [review]
four full tests are clean, lgtm!

**Comment by zachglick** [comment]
I don't think `ints_tolerance` is set in the `ao-casscf-sp` test. grep might've picked up the reference output file, which apparently was generated using tighter settings than the actual test.

**Pull request merged**
