### PR TITLE
Don't build ambit plugin if it's not found.

### PR DESCRIPTION
**Pull request by wpoely86**
## Description
Don't build the ambit plugin if ambit is not present.

### CODE REVIEW

**Comment by loriab** [comment]
the one failure is just our old friend `stability1`, so merging anyway.

**Comment by wpoely86** [comment]
@loriab do you run the tests with Intel MPI at one point? They're failing here for me because CMake picks `mpiexec` over `mpirun` to execute the tests. I'm currently forcing it by `-DMPIEXEC=mpirun`.

**Comment by loriab** [comment]
No, I don't run tests with _any_ MPI, and my test-running is the only one that counts for binary-building. Others (https://testboard.org/cdash/index.php?project=Psi) _may_ run with MPI, but I wouldn't bet on it.

Our cmake build system is getting another re-write by the one person invested in MPI and Psi4 so it's possible the `mpiexec` vs. `mpirun` is addressed (though I think he's testing with gcc tools). Flagging @ryanmrichard so he knows this is an issue.

**Comment by wpoely86** [comment]
@loriab I've tried running the tests with Intel MPI but lots of them hang or fail...

**Comment by wpoely86** [comment]
If you're gonna change things with CMake, I've got two items on the wish lists:
- respect `-DCMAKE_C_FLAGS` (and CXX). If CMake gets flags, they should be used (and not ignore as currently happens)
- Make it possible to build plugins after installing PSI4. Currently, the `--new-makefile` generate a makefile with points to the build dir of psi4 (instead of install). We have to patch and work around that every time.

**Comment by loriab** [comment]
Noted. In the current system, on the first point, you may have to use "extra" or "custom" prefixes to c_flags to get them noticed. The new cmake system will require installation, so the second point should be fixed. It was partially fixed in #410 , but you're probably wanting the add-on headers, too, that weren't addressed in that ticket.

**Comment by ryanmrichard** [comment]
@wpoely86 Yes one of the huge things I wanted to address with the new rewrite is the fact that things like CMAKE_C_FLAGS wasn't being respected.  Admittedly we were ignorant of the CMake way to do things when we wrote the first pass.  This second pass should be substantially more aligned with CMake philosophy, although by means of disclaimer I do not claim to be a CMake expert.  

As for the plugin issue I suspect it will go away.  I'm switching us to a superbuild strategy that relies on having things installed.

Finally, the way we run tests has completely changed since the last time I tested them with MPI.  Taking a quick glance at the scripts I think that the problem might be that the actual tests are run with a Python script and I suspect that the usual CTest options are not being passed to it.  For what it's worth, MPI has been removed from Psi4 in my rewrite.  The idea going forward is to make plugins responsible for it; we have a similar strategy in Pulsar that I think works nicely.

**Pull request merged**
