### PR TITLE
Use libecpint as the ECP engine

### PR DESCRIPTION
**Pull request by andysim**
## Description
This PR builds on the start that @PeterKraus made to get the libecpint library from @robashaw up and running as Psi4's ECP engine.

## Todos
Notable points (developer or user-interest) that this PR has or will accomplish.
- Improve the speed and stability of the ECP integrals.

## Questions
- [ ] @robashaw are the derivative integrals ready to go in Libecpint yet?  If not, do you have any idea how much work it will be to implement them?

## Checklist
- [x] Make libecpint play nicely with our CMake infrastructure
- [ ] Write wrappers for ECP integral code, making the new code path optional for now
- [ ] Tests added for any new features

## Status
- [ ] Ready for review
- [ ] Ready for merge

### CODE REVIEW

**Comment by robashaw** [comment]
Sorry, I’m out of action due to serious illness so probably can’t be much help. I was working on derivatives but they were buggy. They should in theory be simple, but I don’t know when I’ll be in a position to get back to them.

Sorry again :/

**Comment by andysim** [comment]
@robashaw I'm really sorry to hear that.  You should focus on your health, of course, and I wish you a speedy recovery.  I have been able to follow your examples very easily, so getting the library shoehorned into Psi4 is going very well so far.  Even without derivatives it will be a big boost for us because of the efficiency gains from screening, so thanks for taking the time to write this and make it available.  Thanks also for providing clear examples for me to follow.  All the best

Andy.

**Comment by robashaw** [comment]
A (much overdue) update! There is a very significant update to libecpint coming early next week (99% already available on libecpint/readecp branch) with: 

- analytical 1st and 2nd derivatives
- general performance improvements
- much better API
- more robust testing

I will have a look at @andysim previous attempts and see if I can get it working, but I will probably need help hooking in the derivatives to Psi4.

**Comment by andysim** [comment]
Fantastic news!  I think we can probably kill this branch and concentrate on getting the latest and greatest in instead.  We're doing a massive rewrite of the integrals right now, so best to wait until that's merged before working on the ECPs I think - we don't want to have any merge problems.  When we have the new integrals code in (very soon, hopefully), I'll ping you and try to coordinate the ECP rewrite.  Thanks for the very positive update :)

**Pull request closed without merging**
