### PR TITLE
Reduce code triplication in Molecule::atom_at_position

### PR DESCRIPTION
**Pull request by TiborGY**
## Description
Some code triplication may be eliminated.

## Todos

-  [X] Yay for negative LOC

## Checklist
- [X] No new features
- [ ] [All or relevant fraction of full tests run](http://psicode.org/psi4manual/master/build_planning.html#how-to-run-a-subset-of-tests)

## Status
- [x] Ready for review
- [x] Ready for merge

### CODE REVIEW

**Review by JonathonMisiewicz — APPROVED** [review]
FWIW, it would be better to have all these functions simply be `atom_at_position`, but that can be for another day.

**Comment by JonathonMisiewicz** [comment]
> > FWIW, it would be better to have all these functions simply be `atom_at_position`, but that can be for another day.
> 
> Indeed, but I think they are used at a couple of places. My first instinct was to turn it into a function template, but I think these fns are exported to Pyside via pybind right? Not sure how that would handle a C++ template.

Templating is overcomplicated. Change the function names where they are called, C-side. In pybind, you specify which function you want to export with a typedef. For example, here is how we specify which of the three signatures for `Localizer::build` to export.
```
    typedef std::shared_ptr<Localizer> (*localizer_with_type)(const std::string&, std::shared_ptr<BasisSet>,
                                                              std::shared_ptr<Matrix>);

    py::class_<Localizer, std::shared_ptr<Localizer>>(m, "Localizer",
                                                      "Class containing orbital localization procedures")
        .def_static("build", localizer_with_type(&Localizer::build), "Build the localization scheme");
```

**Comment by JonathonMisiewicz** [comment]
Making the first argument to `atom_at_position2` const should resolve the build fail. C is rightly complaining that modifying a temporary is not a sane thing to do.

**Comment by maxscheurer** [comment]
One could also use `py::overload_cast` instead of typedefs 😊

**Comment by JonathonMisiewicz** [comment]
We can merge this in once you say it's ready for merge.

**Comment by TiborGY** [comment]
> We can merge this in once you say it's ready for merge.

This one is good to go.
I think I found a corner case in the current code that may be worth discussing, but that will be a new PR.

**Pull request merged**
