### PR TITLE
DF bases for dzvp

### PR DESCRIPTION
**Pull request by leeping**
## Description
This adds new DF basis files for dzvp.  dgauss-dzvp-autoaux was generated using the autoaux program (courtesy Susi Lehtola).  This is a short-term solution for the current problem that there is no working DF basis for dzvp, as it is an all-electron basis for elements going beyond Kr.

dgauss-dzvp-mix contains a mixture of the previous default, def2-qzvpp-jkfit for H-Br, and dgauss-dzvp-autoaux for heavier elements.  The purpose of this DF basis is to avoid the performance decrease (without affecting accuracy) that comes with using dgauss-dzvp-autoaux for all elements.

`basislistother.py` has also been updated to use dgauss-dzvp-mix for jkfit and dgauss-dzvp-autoaux for rifit.

## Status
- [x] Ready for review
- [x] Ready for merge

## Benchmark of basis sets and DF basis sets for conformational energies
[combined-results.pdf](https://github.com/psi4/psi4/files/6167929/combined-results.pdf)

### CODE REVIEW

**Review by loriab — APPROVED** [review]
lgtm! ultimately, we'll want to pull this generated basis from BSE or run @susilehtola's autoaux code internally. but this'll be a short-term sol'n to get some datasets going again as well as be a validation point for the aforementioned proper efforts.

**Review by hokru — APPROVED** [review]
Thanks for adding this and doing an error analysis.

**Review by andysim — APPROVED** [review]
This is a good short-term solution - thanks for the fix!  LGTM

**Comment by PeterKraus** [comment]
@leeping is there a reason you didn't tick "ready to merge", or can this PR be merged?

**Comment by leeping** [comment]
@PeterKraus I just added the autoabs basis for J fitting as suggested by Susi. Should be good to merge now.

**Review by PeterKraus — APPROVED** [review]
Nice work, thanks!

**Pull request merged**
