### PR TITLE
Prevents the user from using C++ keywords for plugin names.

### PR DESCRIPTION
**Pull request by jturney**
## Description
Prevents the user from using a C++ keyword as a name for a new plugin. It came up on [this](http://forum.psicode.org/t/trouble-in-build-plugin-for-psi4/349) forum post.

## Todos
Notable points that this PR has either accomplished or will accomplish.
* **User-Facing for Release Notes**
  - [x] Prevents the user from using a C++ reserved keyword as a name for a new plugin.

## Status
- [ ]  Ready to go

### CODE REVIEW

**Comment by dgasmith** [comment]
While im thinking of it could you replace all the `type` and `file` variable names to something else so they are not Python reserved objects/types?

**Comment by andysim** [comment]
LGTM

**Comment by loriab** [comment]
LGTM

**Comment by psi-rking** [comment]
Friend, using this true - not void.  Continue.

**Comment by jturney** [comment]
Hold off merging this, please. I'm going to rename the variables that @dgasmith mentioned today when I get a chance.

**Comment by dgasmith** [comment]
@jturney Switched the names and updated the branch. Is there anything else needed here?

**Comment by jturney** [comment]
No, nothing else needed.

**Pull request merged**
