### PR TITLE
Stability bugfix and SAPT output update

### PR DESCRIPTION
**Pull request by jgonthier**
Fixed a bug in the stability analysis: some rotation parameters for the orbitals were not correct, it should be easier to converge on a stable solution now.

SAPT: changed the output according to Friday's meeting. Updated the tests for SAPT and the Sphinx manual as well.
@CDSherrill : you can have a look at the updated output.ref to make sure the output looks good to you.
@loriab : I did not modify the Psivars yet. Do you want to do it by passing a SCALE_FACTOR PsiVars to your code computing all the other variables, or do you prefer some other way?

### CODE REVIEW

**Comment by loriab** [comment]
Well, I wholly approve of this sentence: "Please note that 
 sSAPT0 is thus not the same as requesting ``exch_scale_alpha 3.0``." For the psivars, I think I'll just compute from the keyword in the driver, same as you do and pass it along the the qcdb routine (which doesn't access `psi4` commands. Below is what you're doing I think.

```python
alpha = psi4.get_option('SAPT', 'EXCH_SCAL_ALPHA')
scale = 1.0 if alpha is True else (0.0 if alpha is False else alpha)
```

**Comment by dgasmith** [comment]
@loriab You can just do:
```python
alpha = psi4.get_option('SAPT', 'EXCH_SCAL_ALPHA')
scale = float(alpha)
```

**Comment by CDSherrill** [comment]
Looks good to me.

David

**Comment by jgonthier** [comment]
Ok, I am now updating the branch and then I'll merge it.

**Comment by dgasmith** [comment]
Test of @psi4/p4pub-rw. Jerome says this is ready to merge when travis is complete.

**Pull request merged**
