### PR TITLE
Use a finalized version of the SAP potential and add relevant citations.

### PR DESCRIPTION
**Pull request by susilehtola**
## Description
The paper describing the finite element calculations for the SAP potentials used in Psi4 is now in preprint, so it's a good time to switch to fully converged potentials.

## Todos
Notable points (developer or user-interest) that this PR has or will accomplish.
- [ ] Feature1
- [ ] Feature2

## Questions
- [ ] Question1

## Checklist
- [ ] Tests added for any new features
- [ ] [All or relevant fraction of full tests run](http://psicode.org/psi4manual/master/build_planning.html#how-to-run-a-subset-of-tests)

## Status
- [x] Ready for review
- [x] Ready for merge

### CODE REVIEW

**Comment by loriab** [comment]
save others scanning the logs: https://travis-ci.org/psi4/psi4/jobs/571932399#L1608-L1630

**Comment by susilehtola** [comment]
Sorry.. that's what I get for trusting scripts I had apparently not finished modifying, but I though I'd save time by letting Travis check if it works or not. Should have more luck now.

**Comment by susilehtola** [comment]
Travis is crashing in
```______________________ test_dft_mp2[mp2d-gradient-findif] ______________________```
which is unrelated to the present PR.

**Comment by loriab** [comment]
please either rebase or [change this one character](https://github.com/psi4/psi4/pull/1712/files) to get travis passing. sorry for the trouble.

**Comment by dgasmith** [comment]
Hmm, looks like a libint failure?

**Comment by susilehtola** [comment]
I’m traveling but I’ll have a look when I get back home next week.

**Comment by loriab** [comment]
No need, @susilehtola, as the azure error has to do with azure, clang-cl, and gau2grid, not SAP.

**Comment by susilehtola** [comment]
OK, this is good to go on my behalf.

**Pull request merged**
