### PR TITLE
CIWavefunction updates

### LINKED ISSUE #83: FullCI H2 fails in loop
I've got trouble calculation H2:
```python
import numpy as np
memory 50 Gb

molecule H2 {
    0 1
    H
    H  1  R
    units au
}

set {
    SCF_TYPE PK
    diag_method rsp
    MAXITER 40
    NUM_ROOTS 5
    basis cc-pvdz
}

rlist = np.arange(1.00, 10.1, 0.1)

for r in rlist:
    H2.R = r
    energy('fci')
```
It calculates the first point and then I get:
```python
PSIO_ERROR: unit = 53, errval = 13
PSIO_ERROR: 13 (no such TOC entry)
Traceback (most recent call last):
  File "<string>", line 36, in <module>
  File "share/psi/python/driver.py", line 576, in energy
    procedures['energy'][lowername](lowername, **kwargs)
  File "share/psi/python/proc.py", line 1969, in run_detci
    psi4.detci()
RuntimeError: PSIO Error
```
This is done with 14c78eab

### PR DESCRIPTION
**Pull request by dgasmith**
## Description
Modernization, efficiency, and flexibility improvements for the CI code.

## Todos
- [x] RSP Diagonalization now writes out CIVectors for OPDM, TPDM, etc uses. Fixes #83.
- [x] Removes several deprecated features such as exporting of CI Vectors in an old format.
- [x] The Numpy interface has been updated. Now uses a single `std::vector` instead of a `double *`. This change has been propagated throughout the entire code.
- [x] More CI routines have been exported to the python layer allowing the creation of complex python-based CI methods.
- [x] Adds a new Matrix routine that removes irreps.

## Status
- [x]  Ready to go

### CODE REVIEW

**Comment by CDSherrill** [comment]
I will be reviewing this.  Some of the changes appear trivial and
unnecessary

**Comment by loriab** [comment]
It could be nice to agree on a white space and formatting standard (Jet had an indentation standard once but I've forgotten the number) once, impose it, then reject any future cosmetic changes. There is a git diff command to ignore white space changed.

**Comment by jturney** [comment]
I like 4 spaces :)

**Comment by loriab** [comment]
Me, too. I try to keep the driver mostly to pep8, and that's what it decrees.

**Comment by CDSherrill** [comment]
The initial bit of code I spot checked was not representative --- not many
trivial changes except formatting.  I think everything looks good.

I could resign myself to 4 spaces, which seems to be pretty popular in Psi4.

**Comment by dgasmith** [comment]
Ah, I run a lot of the CI code that hasn't been touched since Psi3 through clang-format with google style options so that I can read it a bit better. I do wish the ignore white-space option was available online as well.

I do like the idea of a style guide for the code, but it isn't particularly high on any list.

**Comment by ryanmrichard** [comment]
Google's style is starting to become C++ standard from what I've seen and
would be my vote.

**Pull request merged**
