### PR TITLE
Implemented PW86 exchange and PW86PBE functional

### PR DESCRIPTION
**Pull request by aoterodelaroza**
## Description
The semilocal PW86 exchange functional (PRB 33:8800(R), 1986) is implemented. The dft1 test case includes four test cases for this functional on a water molecule. The energies are compared against the nwchem reference implementation. The PW86PBE exchange-correlation functional (keyword: pw86pbe), built as the combination of PW86 exchange and PBE correlation, is also made available.

## Status
- [x]  Ready to go

### CODE REVIEW

**Comment by jturney** [comment]
Great! Can you also update ```output.ref``` in ```tests/dft1```?

**Comment by aoterodelaroza** [comment]
Sure, it's done. Thanks! :)

**Comment by loriab** [comment]
LGTM

**Comment by jturney** [comment]
LGTM

The plan is to wait for the "cmake rewrite" to be finalized and merged before we do this one.

**Comment by loriab** [comment]
replaced by #471 after rebasing through CMakeRewrite-KillTheBoost

**Pull request closed without merging**
