### PR TITLE
WIP: Simint integration in Psi4

### PR DESCRIPTION
**Pull request by bennybp**
## Description
**Currently a work-in-progress**

**Currently requires intel compiler**

Implements the simint two-electron integral library into Psi4.

## Todos
Notable points that this PR has either accomplished or will accomplish.
* **Developer Interest**
  - [X] Implement ENABLE_SIMINT option
  - [X] Download & build via ExternalProject_Add
  - [ ] Download & use precompiled library
  - [X] Simint is being used rather than libint
  - [ ] Batching interface to interface classes in libmints (partially done)
  - [ ] Use batching in JK objects (partially done)
  - [ ] Fix some GCC issues in simint
  - [ ] Port new batching interface to libint & erd
  - [ ] Higher AM, or split between simint and erd
  - [ ] Derivatives (WIP in simint...)

* **User-Facing for Release Notes**
  - [ ] Hmmm

## Questions
- [ ]  Where to put tarballs (that is more permanent for psi4). Git is probably not a good idea

## Status
- [ ]  Ready to go

### CODE REVIEW

**Comment by loriab** [comment]
I take it the tarball is because of the whole pain-to-compile aspect? I think any of psicode, vergil, or github repo of tarballs is open for consideration. Not larger than 100MB, I hope?

**Comment by bennybp** [comment]
The tarball contains generated code at the moment. Building isn't too bad (yet), although there are lingering issues with gcc.

Because it is generated code, any sort of git repo is probably overkill.

I will work on precompiled binaries soon as well.

On November 29, 2016 6:21:19 PM EST, "Lori A. Burns" <notifications@github.com> wrote:
>I take it the tarball is because of the whole pain-to-compile aspect? I
>think any of psicode, vergil, or github repo of tarballs is open for
>consideration. Not larger than 100MB, I hope?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/psi4/psi4/pull/533#issuecomment-263732497

-- 
Benjamin Pritchard
ben@bennyp.org

**Comment by loriab** [comment]
If it's generated code, would something like the libint ExternalProject w/i ExternalProject work? Or is it processor-tuned generated code? But we should probably just talk in person someday.

**Comment by loriab** [comment]
For consistency's sake regarding Psi4 AddOns, I'd really like to keep `ENABLE_simint` as a boolean and have something like `SIMINT_TARGET_ARCH` as an optional variable. Would something like [this](https://github.com/tunabrain/tungsten/blob/master/cmake/OptimizeForArchitecture.cmake) allow selecting a good default for `SIMINT_TARGET_ARCH`?

**Pull request closed without merging**
