### PR TITLE
Added save_xyz() to qcdb.Molecule

### PR DESCRIPTION
**Pull request by dsirianni**
## Description
Added `save_xyz()` function to `qcdb.Molecule` with `save_natom` as additional argument.
Will supersede `LibmintsMolecule.save_xyz()`.  

* **User Interest**
  - [x] Able to save .xyz file of QCDB molecule with (default) or without number of atoms as first line of file.

## Status
- [x]  Ready to go

### CODE REVIEW

**Comment by andysim** [comment]
lgtm

**Comment by CDSherrill** [comment]
I think this is a very useful little addition.  Will be very convenient for
our users.

**Comment by jturney** [comment]
Isn't this functionality (minus the save_natom) already in the parent class? 
https://github.com/psi4/psi4/blob/master/psi4/driver/qcdb/libmintsmolecule.py#L1989

**Comment by loriab** [comment]
Right, @jturney, this is just making the `save_natom`-enabled `save_xyz()` available.

**Comment by loriab** [comment]
If future, we should all probably use the context syntax:

```
with open(filename, 'w') as outfile:
    outfile.write(self.save_string_xyz(save_ghosts, save_natom))
```

But perfectly good, as-is. LGTM

**Pull request merged**
