### PR TITLE
OCC Densities to Wavefunction

### PR DESCRIPTION
**Pull request by nlk36701**
## Description
 
Fixes a couple of minor issues for a research project of mine. See todos.

## Todos

- [x] Within the OCC module, updating the opdm to  the wavefunction
- [x] Exposed a function to update the num_frozen_uocc global

## Checklist

- [x] quick tests, occ module tests, standard suite tests

## Status
- [x] Ready for review
- [x] Ready for merge

### CODE REVIEW

**Review by JonathonMisiewicz — APPROVED** [review]
For the record, this is a CCQC project, and I was the consultant for adding densities to the wavefunction and changing occ - both things I've gotten experience with, recently.

**Comment by hokru** [comment]
Could you add to the description how correctness was tested?

So writing densities for FCHK files should work with these changes?
So far OCC is turned off now: https://github.com/psi4/psi4/blob/master/psi4/driver/driver.py#L1984
(Should then probably be enabled in another PR, perhaps with test)

**Comment by loriab** [comment]
Add a test that checks something this fixes, then lgtm. Thanks for the contribution!

**Comment by loriab** [comment]
Please do add or suggest a test for this when you get a chance. If fchk is appropriate to enable, that testing structure is in place.

**Comment by JonathonMisiewicz** [comment]
Between the two of you, the two of us are confused about what kinds of tests you want.

* Holger asked about correctness tests. Lori hasn't raised the issue. This issue wasn't raised during my earlier "density to wavefunction" PRs, so I don't understand why we're doubting its correctness now. This is the same code as I used to bring densities over then. If there is a bug, that's the fault of `occ` and outside the scope of this PR. (And while we _could_ test correctness for the 1RDM, that requires adding occ properties. Which we could do, but is outside the scope of this PR.)
* Holger asked if FCHK can be enabled but said that would be for a different PR. Lori says that may be appropriate for this PR. This is a straight contradiction, and we're confused which you want.
* While it's also possible to test `compute_fvpi`, I cannot recall one other case of a simple Pybind requiring a test, so I'm not sure what we'd be testing. Correctness? That this function can be called Python side?

**Comment by loriab** [comment]
Sorry for the confusion. Right, no testing needed for a pybinding. For the densities, I was looking for "is this code exercised in the test suite?" and "if not, how can we avert someone breaking this later?". If such a test is tricky to construct and you're regarding this as more a better-process than a new-numbers PR, then plausible to wait for any occ bugs to crawl out later.

**Comment by JonathonMisiewicz** [comment]
This isn't a new numbers PR. This is a "make numbers that area already computed accessible" PR.

I know how to test this one: hook up `occ` properties, and add this to `test_dipoles`. I can do that, but that's involved enough to be a separate PR, and one for me, not for Nate.

**Review by loriab — APPROVED** [review]

**Comment by hokru** [comment]
> * Holger asked about correctness tests

Sorry if I was unclear. I only wanted a sentence about how correctness was tested (or which other code was followed) for completeness of the PR body. Just in case one has to track something down.
Maybe in this more trivial case it's not needed, I don't think I looked at the code changes then.

**Comment by JonathonMisiewicz** [comment]
Indeed, in this trivial case, it's not needed. All the density-setting side of the code does is take the same operations done on the OEProp object and move them to being done on the density-set wavefunction. If there was a bug in the density, the properties would already have been wrong.

**Review by hokru — APPROVED** [review]

**Review by andysim — APPROVED** [review]
Weird that the old code was setting the SO density matrix as the MO quantity in OEProp.  This looks much better to me - thanks!

**Pull request merged**
