### PR TITLE
Added dashparams from Goerigk and missing functionals from Peverati and Truhlar.

### PR DESCRIPTION
**Pull request by PeterKraus**
Added dashparams for -D3(0) and -D3(BJ) for 7 functionals from L. Goerigk (JPC:L 6 (2015) 3891).
Added three functionals from Peverati and Truhlar (PCCP 14 (2012) 16187; JCTC 8 (2012) 2310). The functionals still need tests.

## Description
Added missing dashparams and functionals. Could someone please run the Q-Chem tests for N12, N12-SX and MN12-SX?

## Todos
Notable points that this PR has either accomplished or will accomplish.
* **User-Facing for Release Notes**
  - [x] Added -D3(0) and -D3(BJ) params for M11-L, MN12-L, N12, SOGGA11-X, and M11
  - [ ] Added functionals N12, N12-SX and MN12-SX
  - [x] Added -D3(0) and -D3(BJ) params for N12-SX and MN12-SX

## Status
- [ ] Tests for N12, N12-SX and MN12-SX
- [x] Ready to go

### CODE REVIEW

**Comment by hokru** [comment]
While you are at it. Could you change `camb3lyp` to `cam-b3lyp` and remove one of the `b2gpplyp-d3bj` entries. (my fault to add it twice). And I guess `lcwpbe` is `lcr-wpbe` in libxc?
I think these are the remaining name inconsistencies.

Adding the citation where the parameters are from is a nice touch!

**Comment by PeterKraus** [comment]
I fixed the `cam-b3lyp` and removed duplicate `b2gpplyp`. However, I'm not sure about the `LC-wPBE` vs `LRC-wPBE` question: the first one is by [Vydrov and Scuseria](https://doi.org/10.1063/1.2409292), the second one is by [Rohrdanz et al.]( https://doi.org/10.1063/1.3073302). Confusing nomenclature.

Also, it might be helpful to merge PR #880 before merging this one, tests for N12, N12-SX ans MN12-SX are in there.

**Comment by PeterKraus** [comment]
All three of the new functionals now pass the water + water dimer test from PR #880.

**Comment by susilehtola** [comment]
Instead of hard-coding the values for alpha, beta and omega, you could just get them from libxc. Little sense in duplicating stuff.

**Comment by PeterKraus** [comment]
@susilehtola I appreciate that most of this work will probably have to be re-done once psi4 is compatible with LibXC 4. But it isn't yet and I need to use these funcs now...

**Comment by susilehtola** [comment]
But.. those parameters are available also in the presently used version of libxc. Just query cam_omega, cam_alpha and cam_beta from libxc, these will give you all the range separation parameters.

**Comment by PeterKraus** [comment]
The reason why I didn't do it that way is that: a) I don't know how, b) what psi4 expects as x_beta (-0.25) doesn't match what is in libxc as cam_beta (0) - this functional is weird as it has 25% HFX at short range and 0% at long range with omega = 0.11. There must be something else going on here, as eg. in erkale, just setting "HYB_GGA_X_N12_SX-GGA_C_N12_SX" works fine.

**Comment by susilehtola** [comment]
libxc defines cam_alpha = full exact exchange and cam_beta = short-range only exact exchange.
So, in the long range you have cam_alpha, and in the short range you have cam_alpha+cam_beta.

For N12-SX the code in libxc reads
```
  case XC_HYB_GGA_X_N12_SX:
    params->CC = CC_N12_SX;
    p->cam_alpha = 0.00;
    p->cam_beta  = 0.25;
    p->cam_omega = 0.11;
```
where cam_beta is the one you have above, and the minus sign comes from the convention used in Psi4. (You can define F = H0 + J(P) + K(P), or F = H0 + J(P) - K(P), depending how you define your exchange matirx. The former choice is more physical as it includes the minus sign within K.)

**Comment by susilehtola** [comment]
The cam parameters can be extracted by calling the libxc function ```XC(hyb_cam_coef(&func,&omega,&alpha,&beta));```

**Comment by dgasmith** [comment]
N12 is not defined as a full XC functional as shown so Psi4 doesn’t add it automatically. We pull these parameters out often for other fully defined XC functionals. 

-Daniel Smith

**Comment by PeterKraus** [comment]
Closing as it doesn't make sense to commit in lieu of pull request #922 .

**Pull request closed without merging**
